### ISSUE TITLE
CustomEase import problem with GSAP 3 on nuxt

### ISSUE THREAD

**Issue by abdullahkrdnz** [greensock/GSAP#326]
Hi. When I'm upgrading gsap2 to gsap3, I got an error like this:

`TypeError: Cannot assign to read only property 'window' of object '#<Window>'

I'm checking `process.client` when importing. It was working with gsap2 like that.

```javascript
if(process.client) {
  require('@/vendor/gsap/plugins/umd/CustomEase');
}
declare var CustomEase: any
```

Is there any other way to import this?

**Comment by OSUblake** [comment]
Can you make simple repo showing the problem?

And are you using v3 of CustomEase? Why isn't CustomEase being imported from gsap? You should use npm to install the tarball from your member download.
https://greensock.com/docs/v3/Installation#npm

```
npm install ./gsap-bonus.tgz
```
```js
if(process.client) {
  require('gsap/dist/CustomEase');
}
```

**Comment by abdullahkrdnz** [comment]
I couldn't make a nuxt repo with bonus package easily. But I changed the import method according to docs. Now we have a new error:

Code:
```javascript
if(process.client) {
  var gsap = require("gsap/dist/gsap").gsap;
  var CustomEase = require("gsap/dist/CustomEase").CustomEase;
}
```

Error:
```
TypeError: Cannot read property 'registerEase' of undefined
    at CustomEase.setData (CustomEase.js?ffe0:609)
    at new CustomEase (CustomEase.js?ffe0:459)
    at Function.create (CustomEase.js?ffe0:620)
```
```

**Comment by OSUblake** [comment]
Can you make something? I can add the bonus stuff myself. I just need to see the problem.

**Comment by abdullahkrdnz** [comment]
Hi again. I made a repo on [github](https://github.com/abdullahkrdnz/gsap3-custom-ease). May be some typescript error on production mode, but you can ignore these. You can see the problem when you run `yarn run dev`. Also you have to add bonus package.

**Comment by OSUblake** [comment]
TypeScript errors wouldn't let me run dev either, but I got working like this in JavaScript.

```js
import Vue, { PropOptions } from 'vue'

import { TweenMax, gsap } from 'gsap/dist/gsap';
import { CustomEase } from 'gsap/dist/CustomEase';
gsap.registerPlugin(CustomEase);

// if(process.client) {
//   var gsap = require("gsap/dist/gsap").gsap;
//   var CustomEase = require("gsap/dist/CustomEase").CustomEase;
// }

export default Vue.extend({
  
  mounted() {
    const ease = CustomEase.create("custom", "M0,0 C0.4,0 0.5,1 1,1");

    TweenMax.to(this.$refs.myBox, 3, {
      width: "100%",
      ease: ease
    });
  }
})
```

And you don't need TweenMax anymore.
```js
import Vue, { PropOptions } from 'vue'

import { gsap } from 'gsap/dist/gsap';
import { CustomEase } from 'gsap/dist/CustomEase';
gsap.registerPlugin(CustomEase);

export default Vue.extend({
  
  mounted() {
    const ease = CustomEase.create("custom", "M0,0 C0.4,0 0.5,1 1,1");

    gsap.to(this.$refs.myBox, {
      duration: 3,
      width: "100%",
      ease: ease
    });
  }
})
```

**Comment by abdullahkrdnz** [comment]
Ok. `registerPlugin` solves my problem. And checking process.client is no longer needed with gsap3. Thanks for quick replies @OSUblake.
