### ISSUE TITLE
Import extra eases like ExpoScale in GSAP v3

### ISSUE THREAD

**Issue by iDVB** [greensock/GSAP#328]
We've been all over google and the GSAP docs and can't seem to find any references as how to import extra eases like `ExpoScale` now in GSAP v3.

**Previously:**
```
import TimelineMax, { ExpoScaleEase } from 'gsap';
...
{ ease: ExpoScaleEase.config(1, 10, Expo.easeOut) }
...
```

**Now:**
```
import gsap, { ExpoScaleEase } from 'gsap';
...
{ ease: 'expoScale(1, 10, expo.out)' }
...
```

Is this correct for the import? Seems odd to import an object and then never use it. 
Also, it does not seem to work.

**Comment by OSUblake** [comment]
```js
import { gsap } from "gsap";
import { EasePack } from "gsap/EasePack";
gsap.registerPlugin(EasePack);

// using webpack or rollup
import { gsap, EasePack } from "gsap/all;
gsap.registerPlugin(EasePack);
```

**Comment by OSUblake** [comment]
> Seems odd to import an object and then never use it.

v3 doesn't use side effects anymore. That's what `registerPlugin()` is for.

**Comment by iDVB** [comment]
@OSUblake Thanks for the quick reply!
What does the usage look like then? Just the string values?

```
import gsap, { ExpoScaleEase } from 'gsap';
...
{ ease: 'expoScale(1, 10, expo.out)' }
...
```

**Comment by OSUblake** [comment]
```js
import gsap, { ExpoScaleEase } from 'gsap';
```
I did not say to import like that.

Usage is just like you had it.
```js
ease: "expoScale(0.5, 3, 'power2.inOut')"
```
Or 
```js
ExpoScaleEase.config(0.5, 3, "power2.inOut");
```

**Comment by OSUblake** [comment]
>...and do we re-register and import for each webpack component, or just globally.
Yes. Wherever you import a plugin, you should register it. In v3, imports are not global.

**Comment by jackdoyle** [comment]
Sorry about the lack of clarity there - we'll add some notes to the docs. 

Also, for the record, you don't need to import the actual EasePack object itself (though you're welcome to) - you can import the ease directly if you prefer (thus making the other eases able to be tree-shook), as @OSUblake showed in his second example: 

```javascript
import { ExpoScaleEase } from "gsap/EasePack";
```

**Comment by iDVB** [comment]
Thanks! Understood. 
Sorry, I mis-pasted my last and did not use the proper import. 
We are now doing it the way you suggested...

```
import { gsap, EasePack } from "gsap/all;
gsap.registerPlugin(EasePack);

"expoScale(0.5, 3, 'power2.inOut')"
```

We're still having quite a bit of a difference in our animations, 
mainly around durations...even though we're now doing this...

```
  tl.fromTo(layerEl, fromObj, {
    duration: 2,
    scale: 0.3,
  });
```

**Comment by jackdoyle** [comment]
@iDVB when you register something, yes, it makes GSAP aware of it, thus anything that taps into that feature thereafter is enabled - is that what you mean by "global"? It's just not "global" in the sense that the modules don't add a global variable (like to the window object). See what I mean? 

And you said it's all working properly now, right? I'm not sure why it wouldn't work when using it with gsap/all - perhaps you forgot to call gsap.registerPlugin( ExpoScaleEase ) in that case(?)

**Comment by yuyoo0508** [comment]
gsap.to(a,10,{b:8700900,onUpdate:()=>{console.log(a.b)},roundProps:'b'})

**Comment by yuyoo0508** [comment]
gsap.to(a,10,{b:8700900,onUpdate:()=>{console.log(a.b)},roundProps:'b'})    the prop 'b' is not update accurate  and the end value is wrong

**Comment by yuyoo0508** [comment]
var a={b:0}; gsap.to(a,10,{b:8700900,onUpdate:()=>{console.log(a.b)},roundProps:'b'})                           
the prop 'b' is not update accurate and the end value is wrong

**Comment by OSUblake** [comment]
>understood that the "imports are not global.... but it seems like the register IS?
the moment we registered it.... many of our other components that do not yet have registering... seem to work now??

That might work, but it's a good practice to do `registerPlugin()` everywhere you import. What happens if you decide to remove the file that does the all the registering? Then it will break your other code. And only registering once means you have to make sure your files are run in a certain order.

**Comment by FilipGrebowski** [comment]
> 

You are missing closing quotations in your example.
