### ISSUE TITLE
problem of  GSDevTools

### ISSUE THREAD

**Issue by yuyoo0508** [greensock/GSAP#331]
gsap and GSDevTools of v2;  "timeline.reverse()"   can work correct ; but in v3 work wrong                      
  for example of v2   https://codepen.io/yuyoo0508/pen/JjjxGQz                                                                 
for example of v3 https://codepen.io/yuyoo0508/pen/gOOqPyP

**Comment by jackdoyle** [comment]
Thanks for pointing that out - it should be resolved in the upcoming release. I have already updated the Codepen file, so your demo should work if you reload (you may need to clear your cache).
