### ISSUE TITLE
Problem with zero values/durations in GSAP3

### ISSUE THREAD

**Issue by chototoro** [greensock/GSAP#332]
Hi, after upgrading to GSAP3, i've noticed several bugs, which i think are all related to zero values and durations:

- when calling seek(0) (or progress(0), or totalTime(0)) on a paused timeline, the playhead is correctly updated. But then, a call to play() (or play(0)) will get the timeline to restart where it was before the seek() call. You can observe this in this reduced case: https://codepen.io/chototoro/pen/MWWLOvW
If you remove the pause() call, or replace the seek(0) call by seek(0.0001), or replace the play() call by play(0.0001), the behavior is normal as expected.

- a zero duration child timeline (for example only setting values or making immediate callbacks) will be ignored when playing the parent timeline. Reduced case: https://codepen.io/chototoro/pen/zYYepoE
If you make sure the child timeline has a duration > 0, (setting the position parameter to 0.001 for example) the behavior is normal as expected.

**Comment by djmisterjon** [comment]
i also noticed those thing after upgrading to GSAP3.
i add some `tl.to({},{})` everywhere for a temp fix.

Am pretty sure it related here 
https://greensock.com/forums/topic/21930-tlset-tlcall-bug
but i was not succeed to explain to the team with my english.
On my side i refactoring with some `tl.to({},{})` to fix my controller.
gl with this. :)

**Comment by chototoro** [comment]
@djmisterjon Ah, thanks for the `tl.to({},{})` tip! It's definitely cleaner than adding 0.0001 everywhere :)

**Comment by jackdoyle** [comment]
Thanks for reporting this - it should be fixed in the upcoming release which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

Sorry about any hassle that caused.
