### ISSUE TITLE
Is there any way to use onCompleteAll callback for staggers in GSAP3

### ISSUE THREAD

**Issue by abdullahkrdnz** [greensock/GSAP#333]
In GSAP2, we were listening onCompleteAll callback. How can we do this in GSAP3?

**Comment by ZachSaucier** [comment]
You should be able to use an `onComplete` inside of the stagger object, like this:

```
gsap.to(".foo", {stagger: {onComplete: bar}});
```

**Comment by jackdoyle** [comment]
I think Zach meant the opposite - an onComplete on the tween should give you exactly what you want. If you nest it inside the stagger object, it'll fire for each sub-tween.

**Comment by ZachSaucier** [comment]
Oops, yes. Sorry about that.

```
gsap.to(".foo", {onComplete: bar, stagger: { ... }});
```

**Comment by abdullahkrdnz** [comment]
Ok. It is working good. Thanks so much.
