### ISSUE TITLE
Regression in filter transitions in GSAP3

### ISSUE THREAD

**Issue by zslabs** [greensock/GSAP#334]
👋 I have two sites, https://zslabs.com/ (GSAP 2) and https://list.zslabs.com/ (GSAP 3.01). When visiting the first (GSAP 2) and clicking on the three-line menu icon at the top-center, the `backdropFilter: 'blur(2px)'` works as intended with the offcanvas slide out, but in the second site (GSAP 3.01) with the three-line menu icon on the top-right, the filter transition only works "after" the offcanvas panel slides out.

**Comment by ZachSaucier** [comment]
Hey @zslabs. Could you please also share the code that you're using to create this effect?

**Comment by zslabs** [comment]
@ZachSaucier Appreciate the response! GSAP 2 version can be found [here](https://github.com/gremlin/chaoskit/blob/master/src/components/OffCanvas.js#L54) and [here](https://github.com/gremlin/chaoskit/blob/feature/emotion/src/components/OffCanvas.js#L63) is the GSAP3 version.

**Comment by OSUblake** [comment]
Works fine.
https://codepen.io/osublake/pen/dd0d54c6d2429c0fa271816a34a1cbb1

You don't have backdrop-filter set in your css. GSAP can't animate from "none" to "blur(2px)". Check your version 2, it's not animating either.

**Comment by zslabs** [comment]
> Works fine.
> https://codepen.io/osublake/pen/dd0d54c6d2429c0fa271816a34a1cbb1
> 
> You don't have backdrop-filter set in your css. GSAP can't animate from "none" to "blur(2px)". Check your version 2, it's not animating either.

@OSUblake Here's a `.gif` of the GSAP 2 version https://drive.google.com/open?id=1fQDjIRMx_qv7ZwTt-AemPbOjubaY9o3y that shows the blur working.

And here's the GSAP 3 version https://drive.google.com/open?id=1sbWFA6AvGQRIf-8h0Wy6a0diAswWvDO5 that shows the blur not working. 

Let me know if you see otherwise.

**Comment by OSUblake** [comment]
I saw your examples. Inspect the backdrop in your dev console. The blur is not animating in either one. The difference is that gsap is setting the backdrop filter at the start of the animation in v2, and setting the backdrop filter at the end of the animation in v3. That might be a separate issue.

**Comment by zslabs** [comment]
Gotcha - thanks for clarifying. Since I believe the only difference in either example is just the GSAP version; I'd imagine there's something a bit funky going on there. Potentially related to https://github.com/greensock/GSAP/issues/330#issuecomment-555696053 at all with inline styles?

**Comment by OSUblake** [comment]
If you set the backdrop filter to blur(0px), it should work, just like in the demo I posted.

**Comment by jackdoyle** [comment]
Yep, Blake is right and I also added some code to the upcoming release that should handle this even better so you probably don't even need to add the blur(0px) initially (though that's not a bad idea). 

Check it out at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

**Comment by OSUblake** [comment]
That file doesn't work. There is no gsap object.

**Comment by zslabs** [comment]
Thanks both @OSUblake and @jackdoyle for the insight here; 100% makes sense why the blur shouldn't work since I wasn't setting a default, but yeah maybe just an ordering thing with "when" it's being applied compared to GSAP 2 that Jack's update may solve. Appreciated as always!

**Comment by jackdoyle** [comment]
Yep, sorry about that - in my late-night foggy brain I uploaded a file before I went to bed that worked in the uncompressed version and I incorrectly assumed it'd be fine minified but missed one little detail in a new find-and-replace script I had just implemented. Fixed now. The minified beta file should work now.
