### ISSUE TITLE
array tweening bug

### ISSUE THREAD

**Issue by 17b0080** [greensock/GSAP#335]
bug reproduce:
```javascript
import { TimelineLite } from 'gsap';
const a = [1, 2, 3];
new TimelineLite().from(a, 1, [2, 3, 4]);
```

In version **2.1.3** this will work as expected. But in the **latest** verion this will throw an error:
> gsap-core.js:2840 Uncaught TypeError: Cannot read property 'harness' of undefined

**Comment by jackdoyle** [comment]
Yes, I believe this is fixed in the next release which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

(By the way, I think you had a typo in your code - you probably meant TweenLite, not TweenlineLite, right?)

**Comment by 17b0080** [comment]
@jackdoyle 
Oh, thx, i've updated my issue.

**Comment by jackdoyle** [comment]
@17b0080 did you check the beta version I linked to?
