### ISSUE TITLE
IE11: Object doesn't support property or method 'indexOf'

### ISSUE THREAD

**Issue by mdominguez** [greensock/GSAP#343]
Hi

I'm getting an 'Object doesn't support property or method 'indexOf'' error on IE11 when testing my animation.

I've made a codepen: [codepen debug view](https://cdpn.io/mdominguez/debug/xxbOerw/wQMPozbqLaOk) (check on IE11)
[codepen with code](https://codepen.io/mdominguez/pen/xxbOerw)

Any idea what I'm doing wrong? This works perfectly on Chrome, Safari, MS Edge, .but I still need to support IE11 :/

Screenshot of the line of the error => [screenshot](https://www.dropbox.com/s/gpjdgkn8dl9ywjk/Dashboard.png?dl=0)

Thanks!

**Comment by jackdoyle** [comment]
Very interesting. Yeah, it looks like IE11 is returning an unusual value type, but I think I've got a fix that's in the next release which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js - better? 

And thanks so much for the reduced test case (codepen)! I wish everyone was as thoughtful as you. Makes troubleshooting much faster.

**Comment by mdominguez** [comment]
Works like a charm :) Thanks for looking into this so fast! Any idea when this fix will be released?

Np for the codepen, it's the least I can do!

**Comment by jackdoyle** [comment]
> Any idea when this fix will be released?

I'm not sure yet, but you're welcome to use that beta file I provided in the mean time.
