### ISSUE TITLE
gsap show reference from CodeLens in vscode!  bug

### ISSUE THREAD

**Issue by djmisterjon** [greensock/GSAP#344]
Hey guys i get very weird and strange issue with gsap CodeLens.!
This shouldn't happen, we should not see references from create and assign variable!

![image](https://user-images.githubusercontent.com/24865815/70789990-171d0600-1d62-11ea-8f3c-e521f5cacff8.png)
![image](https://user-images.githubusercontent.com/24865815/70790062-45024a80-1d62-11ea-80b0-049f24c4e68c.png)

---
## How to reproduce ?

- `npm i gsap`

- add to your `settings.json` for vscode

```json
"typescript.referencesCodeLens.enabled": true,
"javascript.referencesCodeLens.enabled": true,
```

**Comment by OSUblake** [comment]
And why shouldn't that happen? Show what the references are.

**Comment by djmisterjon** [comment]
i don't know how explain this well in english, sorry,  but this made a big visual mess !
And all reference make no sense.
Gsap seem the only one do this.
![image](https://user-images.githubusercontent.com/24865815/70801314-8c95d000-1d7c-11ea-9883-548116b1abbb.png)

All my other depenci work fine.
```json
    "dat.gui": "^0.7.6",
    "draggable": "^4.2.0",
    "gsap": "^3.0.4", // buggy reference
    "izitoast": "^1.4.0",
    "mn-accordion": "^1.0.3",
    "nw": "^0.39.0-sdk",
    "pixi-filters": "^2.7.1",
    "pixi-layers": "^0.2.2",
    "pixi-lights": "^2.0.3",
    "pixi-projection": "^0.2.8",
    "pixi-sound": "^3.0.3",
    "pixi-spine": "~1.5.7",
    "pixi.js": "^4.8.7",
    "recursive-readdir": "^2.2.2"
```
If i need reference from those, i just need click right and select `find all reference`.
I don't know what happen here. 

Example i never seen this before and this make no sense for me.
![image](https://user-images.githubusercontent.com/24865815/70801566-38d7b680-1d7d-11ea-8082-14c7d75c4358.png)
Reference should no show on method, but only from constructor if am not wrong.
like this
![image](https://user-images.githubusercontent.com/24865815/70801729-a7b50f80-1d7d-11ea-9956-df2f69394ebf.png)
A change make this ?
I can not read my code anymore, it's just unreadable. Especially if i use regions colors !

**Comment by OSUblake** [comment]
> Reference should no show on method, but only from constructor if am not wrong.
like this

No.
![image](https://user-images.githubusercontent.com/3779991/70843486-18e9d680-1e01-11ea-9d7f-7db119f79a34.png)

> This shouldn't happen, we should not see references from create and assign variable!

Why not? It's coming from TypeScript. That's how VS Code works. It uses the TypeScript language service under the hood. That provides you with IntelliSense (autocomplete). A lot of new TypeScript stuff has been added since v 3.0.1. 
https://code.visualstudio.com/docs/nodejs/working-with-javascript

**Comment by djmisterjon** [comment]
Hey first thanks for your time and try help me.
Yes the printScreen you show upper are perfect for me, it normal behavior from referencesCodeLens.

I succeed to get back a hold printscreen.
This is was the ergonomy i was get before, with `"javascript.referencesCodeLens.enabled": true,`.
![image](https://user-images.githubusercontent.com/24865815/70845155-27dc8300-1e19-11ea-94c3-27980cb821e6.png)
and this, is the ergonomy now.
![image](https://user-images.githubusercontent.com/24865815/70845167-4e9ab980-1e19-11ea-9150-2ae84943d066.png)

I admit that I do not understand what is happening, these happened during the update gsap with npm.
i also try get back to 3.0.1 i get same behavior.
And now i try clean all with npm 
```
npm uninstall gsap
npm uninstall @type/gsap
npm uninstall gsap -g
npm uninstall @type/gsap -g
```
I also added special flag to be sure gsap not install automatically by the vscode @type server `"typescript.disableAutomaticTypeAcquisition": true,`

---

But nothing to do, i alway get references line upper gsap method !!!
Or maybe it's a vscode bug, something weird happened?
I don't know if your understand me, i try hard to explain, i hope i can get help to fix this.
For me it very annoying.
I am trying to understand what could have happened and produce this.

---

But this it also very strange, `referencesCodeLens`  now seem show reference on methods with {} as param.
It can maybe related or it was a bug before and vscode make a auto-update to fix this bug that I haven't seen ?
![image](https://user-images.githubusercontent.com/24865815/70845354-97ec0880-1e1b-11ea-8ffa-d654b01b1f24.png)
Do you get the same behavior here, on your side if you add `foo({fooo})` ?
if not, the problem may be from vscode ?, I will take a closer look at the configuration of my project and maybe ask vscode github what happened.

thank you for your intervention.

**Comment by djmisterjon** [comment]
ho maybe related 
https://github.com/microsoft/vscode/issues/86956
dammit, i think it can be more related to vscode. sorry for that's
It because gsap use a lot of reference like thats `{{}}`, i will look on microsoft side.
