### ISSUE TITLE
The last 2.1.3 release contains an outdated version of Draggable vs the one you can download from gsap business green.

### ISSUE THREAD

**Issue by supermoos** [greensock/GSAP#345]
The last 2.1.3 release contains an outdated version of Draggable ( * VERSION: 0.17.1 * DATE: 2019-02-28) vs. the one you get if you download this latest release from your site: GSAP with Business Green bonus (2.1.3 + 3.0.0-beta.11), which is version: ( * VERSION: 0.17.2 * DATE: 2019-08-14) - notably the latter version contains a number of important fixes for iOS 13.

Anyway this could be released so that people installing version 2 from NPM get this version with fixes?

**Comment by jackdoyle** [comment]
@supermoos I'm curious - is there a particular reason you're not updating to the latest version (3.0.4)? I'd certainly recommend that. I don't think we can push an older version up to NPM without negative side effects.

**Comment by supermoos** [comment]
I guess mostly because it's a project that was started before 3 was released, and I didn't wan't to bother updating with any potentail code changes I might have to make - looking at the release note changes it seems like it might be minor what I need to do (stop using classnames a few places, etc.). But in general it might be worth noting this to people who use 2.1.3 for other reasons - as draggable is behaving quite differently on iOS 13 if you rely on it blocking the scroll direction when in use. Is the browser support still the same in gsap 3, mainly thinking about IE 11 here?

**Comment by jackdoyle** [comment]
Yeah, GSAP 3 supports all major browsers back to IE9. Technically GSAP 2.x supported IE back to version 6 (for features that browser supports at least - you couldn't do 3D transforms in IE6 of course). The latest Draggable has all fixes in place and should work great for you (better than any previous version). Plus it's smaller.

I totally understand the hesitation to update an old project that's humming along perfectly with GSAP 2.x. You're welcome to keep using it, but we don't plan to push out other 2.x releases at this point. We're all-in on GSAP 3. Hopefully you'll find that it's even more enjoyable to use than 2.x once you adjust to the minor syntax changes (though you can still use the old syntax if you prefer).
