### ISSUE TITLE
Do you have a version of AS3 now？

### ISSUE THREAD

**Issue by G1xuan** [greensock/GSAP#346]
my old version is this one.
/**
 * VERSION: 1.693
 * DATE: 2011-11-08
 * AS3 (AS2 version is also available)
 * UPDATES AND DOCS AT: http://www.greensock.com/timelinemax/
 **/

if i set the param(useFrames=true) ,but i can't control the fps.
i find the new version can set the Tween.ticker.fps(),but old version can not support !
so,can you give me a new version for AS3? thx

**Comment by jackdoyle** [comment]
Yikes! That's a really old version from ActionScript. You're posting this in the JavaScript repository. I think you may be looking for this: https://github.com/greensock/GreenSock-AS3

Right? 

We haven't maintained the ActionScript version for years since Flash has largely died. You're welcome to use the old AS3/AS2 files, of course. As far as we know, they work great.

**Comment by G1xuan** [comment]
Thx for reply~
After i download the https://github.com/greensock/GreenSock-AS3 , i find the ticker param.
but haven't  ticker.fps()  function.
Maybe, i can not control the fps in the old AS3 version any more.

**Comment by ZachSaucier** [comment]
Hey G1xuan. If I'm not mistaken, the FPS is Flash global. There's no way to change it for individual MovieClips with or without GSAP. Here's an article on how to change it: https://www.adobe.com/devnet/flash/learning_guide/animation/part02.html

**Comment by G1xuan** [comment]
> Hey G1xuan. If I'm not mistaken, the FPS in Flash is global. There's no way to change it for individual MovieClips with or without GSAP. Here's an article on how to change it: https://www.adobe.com/devnet/flash/learning_guide/animation/part02.html



Bro, you are right !!!
After i read the article , i find that if i want to use the param (useframe = true) , just need change the fps in Flash.
the code in AS3 is : Stage.frameRate = 60 ;
And then when i set the useframe=ture, i can control the timeline frame become 60fps now.
