### ISSUE TITLE
There is new timeline function in GSAP3

### ISSUE THREAD

**Issue by bigfanjs** [greensock/GSAP#347]
I have see in the DOCs that we can use timelines like this:
```js
//WITH Timelines (cleaner, more versatile)
var tl = gsap.timeline({repeat: 2, repeatDelay: 1});
tl.to("#id", {x: 100, duration: 1});
tl.to("#id", {y: 50, duration: 1});
tl.to("#id", {opacity: 0, duration: 1});

// then we can control the whole thing easily...
tl.pause();
tl.resume();
tl.seek(1.5);
tl.reverse();
...
```

I tried to use this in my code:
```js
import gsap from "gsap"

const tl = gsap.timeline({repeat: 2, repeatDelay: 1});
```

and also tried 
```js
import gsap, { timeline } from "gsap"

const tl = timeline({repeat: 2, repeatDelay: 1});
```

but neither of them works. I took a look into the gsap CSSPlugin it seems there is no existence of `timeline`.

how can I use timelines in GSAP3 and how can I import them? thanks

**Comment by ZachSaucier** [comment]
Hey bigfanjs,

You don't need to import timelines in GSAP 3. They are a part of the `gsap` object, your first code should work granted you're loading GSAP properly. What are you trying to use GSAP in? Depending on your other tooling it might be good to load the UMD file instead:

```
import { gsap } from "gsap/dist/gsap";
```

Our [Installation page](https://greensock.com/docs/v3/Installation) has more info.

What error(s) are you getting?

**Comment by bigfanjs** [comment]
@ZachSaucier never mind it's my bad 🤦‍♂ the upgrade kind of was failing
Thank you very much for the help. It's working like charm 😄
