### ISSUE TITLE
Calling reverse() after progress(1) in Timeline does not work the same as it did in GSAP2

### ISSUE THREAD

**Issue by zslabs** [greensock/GSAP#348]
[Demo](https://codepen.io/zslabs/pen/oNgqjZy)

I used to be able to call `progress(1)` and then `reverse()`, but this only seems to work if I call `play()` (which I'd rather not do; I'd rather it start at the end in certain cases).

**Comment by jackdoyle** [comment]
Good catch, @zslabs  - it should be resolved in 3.0.5 which I just pushed live.

**Comment by zslabs** [comment]
@jackdoyle Confirmed working! Thanks so much for squeezing this into the latest release. I really appreciate it!
