### ISSUE TITLE
a value of _ts sents the end to Infinity

### ISSUE THREAD

**Issue by Llorx** [greensock/GSAP#349]
On v3, when adding a **paused timeline to another timeline**, internally having the Timeline a value of `_ts = 0` will make its end to be `Infinity`:

![image](https://user-images.githubusercontent.com/702490/72226563-b49e6c00-3592-11ea-8e9d-0b00c6841e40.png)

That's because dividing by zero, which we all know is something bad.

**Comment by jackdoyle** [comment]
Thanks for pointing that out. It should be fixed in the next release which you can preview at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js. 

Better?
