### ISSUE TITLE
timescale

### ISSUE THREAD

**Issue by zoneblaze** [greensock/GSAP#354]
Are you going to update to 3.1.0 soon on npm? I've noticed timeScale is a bit erratic on 3.0.5, thank you! https://codepen.io/blaze747/pen/MWYZLLb

**Comment by jackdoyle** [comment]
Yes indeed, we're planning to push 3.1.0 live within the next few days. Thanks for your patience.

**Comment by jackdoyle** [comment]
....and it's live!
