### ISSUE TITLE
Build Error: export 'TweenMaxWithCSS' (reexported as 'TweenMax') was not found in './gsap-core.js'

### ISSUE THREAD

**Issue by CaelanStewart** [greensock/GSAP#355]
Version: `3.1.0`

```
WARNING in /Users/user/homestead-projects/project/node_modules/gsap/all.js 7:0-373
"export 'TweenMaxWithCSS' (reexported as 'TweenMax') was not found in './gsap-core.js'
```

When I import from `gsap/all`.

Looking at `gsap/all.js`:

There is this line:

```
export { TweenMaxWithCSS as TweenMax, TweenLite, TimelineMax, TimelineLite, Power0, Power1, Power2, Power3, Power4, Linear, Quad, Cubic, Quart, Quint, Strong, Elastic, Back, SteppedEase, Bounce, Sine, Expo, Circ, wrap, wrapYoyo, distribute, random, snap, normalize, getUnit, clamp, splitColor, toArray, mapRange, pipe, unitize, interpolate, shuffle } from "./gsap-core.js";
```

However, in `./gsap-core.js` there exists no such symbol `TweenMaxWithCSS`.

This does not prevent a build since only a warning is issued.

Might cause problems for some build configurations though.

**Comment by billdwhite** [comment]
Same problem here.  Should we still be using gsap/all for our imports?  (I'm importing into Angular 8)

**Comment by CaelanStewart** [comment]
@billdwhite - yeah I wondered as much, surprising how this would not have been caught before release, unless they use a different mechanism for import.

**Comment by ZachSaucier** [comment]
Do you get the same error when you import from "gsap" (for ES modules) or "gsap/dist/gsap" (for UMD/CommonJS)?

**Comment by billdwhite** [comment]
I had my module set to 'esnext';  changing all of the 'gsap/all' references to 'gsap' seems to fix the issue.

**Comment by jackdoyle** [comment]
Yeah, sorry about that folks - silly mistake on my part. I'll have a 3.1.1 patch out pretty soon to resolve the export issue in the "all" file.

**Comment by jackdoyle** [comment]
Should be fixed in the latest push. Again, please accept my apologies for the oversight.
