### ISSUE TITLE
killTweensOf by (stringId || tween)

### ISSUE THREAD

**Issue by djmisterjon** [greensock/GSAP#356]
Hey guys did you think it possible include a destroy with string id?
`gsap.killTweensOf('id');`
or maybe make this possible ?
`gsap.killTweensOf( gsap.getById('id') );`

I know we can do this
`gsap.getById('id').kill();` 
but in special context , if id already destroy, it will crash.

**Comment by jackdoyle** [comment]
I assume you're talking about an ID that was assigned to an animation instance (not an ID from a DOM element), right? 

It should be as easy as: 
```javascript
var animation = gsap.getById("id");
if (animation) {
  animation.kill();
}
```

**Comment by djmisterjon** [comment]
> ```js
> var animation = gsap.getById("id");
> if (animation) {
>   animation.kill();
> }
> ```

yes, and this is precisely what I want to avoid. Create a scope variable and put conditional everywhere !

**Comment by jackdoyle** [comment]
Oh, there are easy solutions for that too:
```javascript
// make your own function:
function killById(id) {
    var animation = gsap.getById(id);
    if (animation) {
        animation.kill();
    }
}

// then it's super-simple each time you want to kill something: 
killById("myID")
```
- OR - 
```javascript
// slightly less performant, but doesn't create any variables at all:
gsap.getById("id") && gsap.getById("id").kill();
```

**Comment by djmisterjon** [comment]
In fact I hoped to see it natively in gsap to avoid having to manage files, but its ok, you probably have your reasons :).
ok so i create a special file `polyfill_gsap.js`.

```js
/** kill tween by id
 * @param {string} id - the string id of the tween animation.
 * @returns {Boolean} - return true if succeed.
 */
gsap.killTweensById = function killTweensId(id=''){
    const tween = this.getById(id);
    if(tween){
         tween.kill();
         return true;
    }
    return false;
}
```

I don't know if this is the best way to do it, however, if you have a better approach for your engine, welcome :)
