### ISSUE TITLE
Typedefs for playback methods don't include "null"

### ISSUE THREAD

**Issue by Lange** [greensock/GSAP#359]
As documented [here](https://greensock.com/docs/v3/GSAP/Timeline/pause()), most (all?) of the playback methods accept `null` as their first argument, which has some special behavior. However,[ the typedef currently forbids passing in `null`](https://github.com/greensock/GSAP/blob/11445297910061db3743dfa8ce43887414d23437/types/animation.d.ts#L26).

This is something that would need to be fixed for multiple playback methods, not just for `pause`.

**Comment by jackdoyle** [comment]
Technically you're right about the TypeScript definitions, but I'm curious why it'd ever matter practically-speaking. Like...why would you ever pass null as that parameter? I can't imagine a scenario. Help?

**Comment by Lange** [comment]
Ah, sometimes I want to provide `false` for `suppressEvents` (the second argument), but still use that default `null` value for the first `atTime` argument. If there's a better way of doing that, I'm happy to change my code over to that.

**Comment by jackdoyle** [comment]
Perhaps I'm misunderstanding your goal, but there's no point in supplying any value to suppressEvents if you're not providing a numeric "from" parameter because the playhead isn't being moved elsewhere, so no events would be called anyway. See what I mean? 

In other words, suppressEvents is only relevant if the playhead is getting moved elsewhere.

**Comment by Lange** [comment]
That's fair, if I'm honest this is in code I wrote 1-2 years ago and am just now porting to GSAP 3, which is why I'm seeing this typedef stuff.

My only guess is that, for some reason, it _did_ matter if I passed `suppressEvents` or not. Unfortunately, past me was not kind enough to explain why I did this in a few places in my codebase.

**Comment by jackdoyle** [comment]
Should be fixed in the latest release (3.2.0)
