### ISSUE TITLE
Zero duration tweens don't resolve a promise.

### ISSUE THREAD

**Issue by DanislavKamenov** [greensock/GSAP#360]
When attempting to tween with a duration of 0 and calling the .then method to wait for a promise resolution before continuing, it never resolves.

The expected behavior was an instantly resolved promise.
This is useful in cases where you write generic tweens with variable duration which might occasionally be 0 but you also want to wait for them to finish in case the duration is not 0.
Codepen example here: https://codepen.io/Danisimo/pen/NWPZPvG?editors=1111

**Comment by jackdoyle** [comment]
Yes, I see what you mean and that should be fixed in the next release.

**Comment by jackdoyle** [comment]
Should be fixed in the latest release (3.2.0)
