### ISSUE TITLE
Change target 'isArray' test

### ISSUE THREAD

**Issue by MichaelChistyakov** [greensock/GSAP#362]
If I'm passing {length: 0} as a gsap.to target I get 'GSAP target [object Object] not found.' warning.

https://codepen.io/michaelchistyakov/pen/KKpVymw

I'm working on text animation module (like TextAnimation plugin but more complex). Basically it is a class with 'length' property and methods like to / fromTo etc., gsap is used to internally tween class instance properties (gsap.to(this, ..)). But I have console warning and no tweens applied.

Please fix it. 'length' can be not only Array property.

**Comment by jackdoyle** [comment]
Yeah, that complicates things with the heuristics for sensing Array-like objects (like jQuery selections). I can't think of a perfect (and performant) solution for that internally, but you can simply wrap your object in an Array: 
https://codepen.io/GreenSock/pen/3753109c56a51e640e433d27e80b8353?editors=0011

**Comment by MichaelChistyakov** [comment]
Yes, I understand that I can wrap target in array. But are you sure there is now way to work directly with target with 'length' property?

Maybe you can do something like checking if array specific methods are in target? Or 'obj instanceof jQuery'?

As for me it was a bit hard to find a reason of error. I believe that there must be some solution for such cases.

**Comment by MichaelChistyakov** [comment]
Other way you can use logic like:

{length: 0} → Object
{length: 1, '0': 'something'} → Array-like (has 'length' and first element)
{length: 0, '0': 'something'} → Object (not-array + length property)
{length: 10, '9': 'something'} → Object + console warn 'Target presented as Object' (to force it as Array-like add 'asArray: true' parameter)

**Comment by jackdoyle** [comment]
We can't check for jQuery - we can't assume it's even loaded and there are many other selector engines like jQuery that could act in a similar way. How would you distinguish a jQuery-like object that has no results, like if someone tried $(".non-existent-class") which would return an object that has a length of 0, and obj[0] of course doesn't exist? That would look a lot like your {length:0} object. See what I mean? 

Is there a reason you can't wrap your object in an Array? This is certainly an edge case and I don't see a clean solution other than just wrapping it.

**Comment by MichaelChistyakov** [comment]
Yes, I understand.

But you can check if I'm going to change 'length' property (that is atypical for any Array-like objects, right?) and, possibly, check if I'm going to tween any props **of** target object itself, not properties of array elements.

I mean if there is no elements at index keys (obj[N]) you may try to check if we can tween target itself, otherwise skip all tweens and warn in console.

**Comment by jackdoyle** [comment]
I think I managed to wedge some conditional logic in there to isolate this case. Feel free to check it out in the preview of the upcoming release at https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js

**Comment by MichaelChistyakov** [comment]
Thank you.

I can not test your build due to some troubles with adding it to project (I think it is my fault). Will be waiting for new release.

**Comment by jackdoyle** [comment]
Should be fixed in the latest release (3.2.0)
