### ISSUE TITLE
Typescript declarations for eases are strange?

### ISSUE THREAD

**Issue by jsysnowy** [greensock/GSAP#363]
Hey; so i just trying to upgrade from GSAP2 to GSAP3 in my TS project and trying to wrap my head around some weird behavior with trying to import easing.

So i got all the gsap imports working but eases seem to have two declared definitions, one as a module and one as a const - however if you select the const one then it's actually just undefined and crashes.

![image](https://user-images.githubusercontent.com/28527653/74530648-76de8b80-4f22-11ea-9862-927174986a3a.png)

Not sure why this is happening or why it's there, seems that all the eases inside `types/Ease.d.ts" are declared twice?  At the end of the day i guess it's not a huge issue as i can just make sure to pick the right one from the autocomplete options but it's a little annoying.

Made a little codebox example with the issue visible - only included gsap so I'm fairly confident it's not an environment issue. https://codesandbox.io/s/reverent-khayyam-5dwpw

Thanks in advanced

**Comment by ZachSaucier** [comment]
Hey jsysnowy.

I'm no Typescript expert (Blake is more so - he'll probably chime in once he's around), but we don't recommend importing from /all. We recommend importing all eases from `"gsap"`:

```
import { gsap, Power1, Power2 } from "gsap";
```

We highly recommend using [our install helper](https://greensock.com/docs/v3/Installation?checked=core,gsap2,Power1,Power2#modules) until you get used to the format of importing things in GSAP 3.

**Comment by jsysnowy** [comment]
Hey thanks,

I'm just using the default npm install method, and these two options in autocomplete are the only two which are shown - usually when a package exports a module then your IDE will pick these up and add them as importable modules - saves you having to manually add imports to your files.  These options are provided through the d.ts files in the "types" folder, included in the package.

You're right about importing through "gsap" instead of "/all" as you said - was a mistake on my end there; but it's not 100% what I'm having issues with; will include a quick gif if it helps, however i appreciate the response!

![gsap](https://user-images.githubusercontent.com/28527653/74537532-30912880-4f32-11ea-82ba-bb7ccaba8aab.gif)

**Comment by OSUblake** [comment]
It's fine it you import from `/all`, but you will probably need to tell TypeScript where the definitions are in your tsconfig.

```
{
  "compilerOptions": {
    ...
  },
  "files": [
    "node_modules/gsap/types/index.d.ts"
  ]
}
```

> At the end of the day i guess it's not a huge issue as i can just make sure to pick the right one from the autocomplete options but it's a little annoying.

It doesn't matter which one you choose. They are both the same. They are declared twice because gsap can be installed globally, but again, they are both the same, so it doesn't matter.

The problem shown in your gif is that you aren't importing `Power2`, so it will obviously create an error as it can't find a `Power2` object. You just need to import `Power2`, or use the new ease string format, `"power2"`.
https://greensock.com/docs/v3/Eases

**Comment by jsysnowy** [comment]
Hey thanks; fair enough - I know i wasn't importing Power2 in the gif but it was the fact the definition file was declaring that const even tho i haven't installed it globally.. so it was just undefined. I think I'll just modify my version of the definition files to not include those consts since that works for me :) Will close this.
