### ISSUE TITLE
ScrollToPlugin chokes when pointing to an anchor element

### ISSUE THREAD

**Issue by loilo** [greensock/GSAP#366]
The `ScrollToPlugin` in its current state does not work with anchor elements that have no `href` attribute (i.e. those invisible anchors that used to be popular to jump through parts of a page).

You can see it in [this CodePen](https://codepen.io/loilo/pen/ExjmjXZ).

The reason is [the `isNaN` check](https://github.com/greensock/GSAP/blob/5816f0c35428033249a6841891f4d0293f8d1a44/dist/ScrollToPlugin.js#L73) that is used to separate numbers from other values. Unfortunately, anchor elements with no `href` are coerced to `0` and therefore do *not* pass the `isNaN` check.

<details>
  <summary><strong>Expand this section if you're interested in the nitty gritty details why anchors are coerced to `0` (with links to the relevant specs)</strong></summary>

---

This is how `isNaN(el)` works if `el` is a DOM element:

- `el` is [coerced to a number](https://tc39.es/ecma262/#sec-isnan-number).
- Coercing `el` to a number first [requires it](https://tc39.es/ecma262/#sec-tonumber) to be coerced to a primitive value (hinting that a number is the desired result).
- Coercing to a primitive value with a number hint [first checks `el.valueOf()`](https://tc39.es/ecma262/#sec-ordinarytoprimitive) and uses that if it's a primitive value. However, DOM elements are objects, and the `valueOf()` of an object [is the object itself](https://tc39.es/ecma262/#sec-object.prototype.valueof). Because of that, it uses `el.toString()` as the primitive value instead.
- `el.toString()` usually returns something like `"[object HTMLDivElement]"` or the likes ([like all EcmaScript objects do](https://tc39.es/ecma262/#sec-object.prototype.tostring)).
- However, hyperlinks are special here as [they do implement](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element:concept-element-dom) the `HTMLHyperlinkElementUtils` mixin, which makes them [return their `href` value](https://html.spec.whatwg.org/multipage/links.html#api-for-a-and-area-elements) when being coerced to a string.
- If `el` does not have an `href` attribute, it [returns the empty string](https://html.spec.whatwg.org/multipage/links.html#dom-hyperlink-href).
- Now that the primitive value of `el` is known, it is coerced to a number. Coercing a string to a number follows [a bunch of rules](https://tc39.es/ecma262/#sec-tonumber-applied-to-the-string-type), but in short it can be said that coercing any `"[object ...]"` string and almost all valid `href` values returns `NaN` — except for the empty string, which is coerced to `0`.
- `0`, in fact, *is* a number.

And that's why `isNaN(document.createElement('a'))` yields `false`. 😁

</details>

**Comment by ZachSaucier** [comment]
Hey loilo and thanks for posting! 

This does indeed seem like a bug to me. I'm sure Jack will get it fixed and/or comment right away when he's around.

As a side note, I do want to point out that you can just pass in a query string as the value of the `scrollTo` - for example `scrollTo: '[name="anchor"]'` - because GSAP uses `.querySelectorAll` under the hood. This has no issues which may be helpful if you're facing this in your current project.

**Comment by loilo** [comment]
Thanks. Yes, I've realized that and already found several ways to work around the bug. But fixing this would be great for sparing others the additional research, hence the issue. (That said, 95% of that research was about finding out "why the heck does `<a>` coerce to `0`". 😉)

**Comment by jackdoyle** [comment]
Should be resolved in 3.2.2
