### ISSUE TITLE
stagger seems to be broken in 3.2.2

### ISSUE THREAD

**Issue by gerasimvol** [greensock/GSAP#367]
Sorry for no demo
but this code works choppy in 3.2.2 (ok in 3.1.1)
`tl.fromTo(els, { autoAlpha: 0, y: -15 }, { autoAlpha: 1, y: 0, duration: 0.3, stagger: 0.1 }, 0)`

It's like initial state of animation (from) applied with delay

**Comment by ZachSaucier** [comment]
Hey @gerasimvol. I [cannot reproduce](https://codepen.io/GreenSock/pen/f48e4c70f4051cbf007249d60428cbe8?editors=0010) any choppiness in 3.2.2. Can you please make a minimal demo of the issue?

**Comment by jackdoyle** [comment]
@gerasimvol I can't seem to find any problems either but I'm eager to squash any bugs that you may have stumbled upon. A reduced test case would be SUPER helpful. Got a codepen or something?

**Comment by gerasimvol** [comment]
@ZachSaucier @jackdoyle thanks for fast response and desire to help 🙏
it's perfectly fine in 3.2.3 ❤️
I have no idea about this anomaly in 3.2.2 🤯
