### ISSUE TITLE
Stagger: Grid property breaks with plain objects.

### ISSUE THREAD

**Issue by Mugen87** [greensock/GSAP#369]
I'm referring to the following official demo from [Advanced stagger effects in GSAP 3](https://www.youtube.com/watch?v=wDnUtY5KcOc).

https://codepen.io/GreenSock/pen/75c2347972d85d840f6e75bc95f33ca7?editors=0010

When you use the same gsap code with an array of objects, a runtime error occurs:

https://jsfiddle.net/dyph6gn8/

That happens because gsap seems to use `getBoundingClientRect()` which is only defined for the [Element](https://developer.mozilla.org/de/docs/Web/API/Element) interface.

**Comment by ZachSaucier** [comment]
Hey Mugen87. This is known and intended. It's impossible for GSAP to automatically detect the layout of non-DOM elements (like your WebGL objects) generically. You should pass in the grid sizes to the `grid` property via an array like so: `grid: [10, 10]`

**Comment by Mugen87** [comment]
Fantastic! This is so nice now: https://jsfiddle.net/z1rhL6vj/

I've tried to look this up in the documentation but could not find the right spot? Do you mind sharing a link to the correct page?

**Comment by ZachSaucier** [comment]
If you go to https://greensock.com/stagger/ it will forward to the docs page focused on staggers. It's an informational page at the bottom of the main navigation: 
![image](https://user-images.githubusercontent.com/3966722/76419956-a93fa500-6377-11ea-91c6-caa83c8a8696.png)

**Comment by Mugen87** [comment]
Thanks!
