### ISSUE TITLE
TweenLite branch broken

### ISSUE THREAD

**Issue by juvabien** [greensock/GSAP#371]
Hello,

I am using a html theme that uses TweenLite.min.js and which is used in the 2.1.3 branch.
This branch is no longer accessible with npm install TweenLite

Can you deliver version 2?

thank you

**Comment by ZachSaucier** [comment]
Hey juvabien.

You should be able to install version 2.1.3 of GSAP by using `npm install gsap@2.1.3`

**Comment by juvabien** [comment]
not better here is output error 

npm install --save gsap@2.1.3

This dependency was not found:
* TweenLite in ./assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.js

To install it, you can run: npm install --save TweenLite

This relative module was not found:
* ../TweenLite.min.js in ./assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.js

Thank you

**Comment by ZachSaucier** [comment]
I'm guessing it installed correctly but your project is giving you that error?

Looks like something is wrong with your importing or configuration. It should be pointing to `/node-modules/gsap/TweenLite.js`. 

How are you trying to import TweenLite? We recommend using `import TweenLite from 'gsap/TweenLite'`

Please see the [modules install video](https://vimeo.com/391314787) for how to install and import GSAP using modules and see [the install page](https://greensock.com/install) for more information.

**Comment by jackdoyle** [comment]
Yeah, it sounds like something is wrong on your end. And this looks very odd to me: "npm install --save TweenLite" because I don't think there's such a package.

**Comment by juvabien** [comment]
Absolutely, your scripts are included in the LivIconsEvo.tools.js file.

I use yarn encore dev command (under Symfony) to install all assets. 
npm try to resolve the dependances although they are already included.

I think it is not possible to tell yarn and npm to exclude or ignore your scripts already included

Here is the header of LivIconsEvo.tools.js file in which there is the inclusion of the TweenLite script :

/****************************************************************************************************
 * @name:       LivIconsEvo.tools.js - the third party libraries for LivIcons (Live Icons) Evolution
 * @version:    2.8.XXX (XXX is a total number of icons)
 * @URL:        https://livicons.com
 *
 * Content:     Snap.svg 0.5.1
 *              GreenSock TweenMax 2.1.2
 *              GreenSock DrawSVGPlugin 0.2.1
 *              GreenSock MorphSVGPlugin 0.8.11
 *              verge 1.10.2+201705300050
 *
 * @licenses:   see details in the comments for each library
*****************************************************************************************************/

**Comment by ZachSaucier** [comment]
Based on [LivIconsEvo's docs](https://livicons.com/documentation-jquery.php), it looks like the path that it's reporting is wrong. You should be able to find TweenMax under `LivIconsEvo/js/tools/TweenMax.min.js`. 

It's possible that the documentation is outdated or there is a separate modules-based file structure. Please ask the creators of that plugin for future direction/help.

Given this is unrelated to GSAP we'll likely close this issue.

**Comment by juvabien** [comment]
thank you Zach for your recommendations ;)
