### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined when registering Draggable Plugin

### ISSUE THREAD

**Issue by thegeminisociety** [greensock/GSAP#376]
Downloaded the fresh gsap-bonus.tgz this morning and tried to install and use on a Next.js project.

Getting this error after using the following code (using CommonJS, also FWIW I tested SplitText and it registered fine:

```
import { gsap } from "gsap/dist/gsap";
import { Draggable } from "gsap/dist/Draggable";

gsap.registerPlugin(Draggable);
```
error:
```
TypeError: Cannot read property 'style' of undefined

_checkPropPrefix
node_modules/gsap/dist/gsap.js:3732:15
_initCore
node_modules/gsap/dist/Draggable.js:1130:26
Function.register
node_modules/gsap/dist/Draggable.js:2810:7
_createPlugin
node_modules/gsap/dist/gsap.js:980:14
(anonymous function)
node_modules/gsap/dist/gsap.js:3370:16
registerPlugin
node_modules/gsap/dist/gsap.js:3369:12
```

**Comment by ZachSaucier** [comment]
Hey thegeminisociety.

Have you tried adding the following in your config.js?

```
build: {
  transpile: [
    "gsap"
  ]
}
```

[Similar thread](https://greensock.com/forums/topic/21961-plugin-issue-with-gsap3-npm-and-nuxtjs/) where this is discussed.

**Comment by jackdoyle** [comment]
Hm, it looks like you're using two different formats. You're importing the ES5 Draggable ("gsap/dist/Draggable") but the ES6 module of GSAP ("gsap"). You should definitely use the same format, so if you need CommonJS support then import the ES5 GSAP like: 

`import { gsap } from "gsap/dist/gsap";`

Does that clear things up?

**Comment by thegeminisociety** [comment]
Sorry, I had been experimenting.

I am using 

```
import { gsap } from "gsap/dist/gsap";
import { Draggable } from "gsap/dist/Draggable";

gsap.registerPlugin(Draggable);
```

**Comment by jackdoyle** [comment]
It's very difficult to troubleshoot blind - it sounds like in your setup the window and/or document aren't available when the code runs. If you still need some help, please provide the most reduced case possible so we can reproduce the error and see what's going on. This sounds like an issue with either your setup or Next.

Also, you're using GSAP 3.2.6 right?

**Comment by thegeminisociety** [comment]
Yes GSAP 3.2.6

I solved it, as you mentioned the window/document was not available yet.

This solution worked

```
  React.useEffect(()=> {
    gsap.registerPlugin(Draggable);
  }, []);
```
