### ISSUE TITLE
Keyframes + stagger issue in GSAP3

### ISSUE THREAD

**Issue by Djules** [greensock/GSAP#377]
Using 3.2.6, I'm trying how to use keyframes and stagger on collection of items in the same tween.
It turns out the stagger is ignored. I managed to make stagger using delay with index in the first frame, but not sure if it intended.

Here is a sample for better understanding: https://codepen.io/Djules/pen/xxwEpEy

**Comment by ZachSaucier** [comment]
Hey Djules. It's not clear to me exactly what you're wanting to do. Your tweens will be in conflict with each other the way that you have the delay. Are you wanting something like this, but using keyframes?

```
gsap.timeline({defaults: {stagger: 0.2, duration: 0.8, ease: 'cubic.inOut'}})
  .to(lines, { x:  20 })
  .to(lines, { x: -20 })
  .to(lines, { x:   0 })
```

**Comment by Djules** [comment]
Hi @ZachSaucier, thanks for your reply.
You guessed right, I'm using keyframes here like a timeline. It works indeed setting stagger in the defaults property, and it makes sense actually.
Maybe the documentation could make this a bit clearer.

**Comment by ZachSaucier** [comment]
> Maybe the documentation could make this a bit clearer.
Maybe so. Where did you look to find this information?
