### ISSUE TITLE
Middle Click issue with Draggable (GSAP 3)

### ISSUE THREAD

**Issue by KennethRobbeFrucon** [greensock/GSAP#378]
When you click on a link in a Draggable-instance with your middle mouse button (to open it in a new tab), the link opens both in the original & new tab.

You can see this behaviour [here](https://codepen.io/kennethrobbefrucon/pen/pojRaXQ). This codepen is based on the default example, I've only added links within the draggable items. 

I'm encountering this issue in Chrome 81.

**Comment by jackdoyle** [comment]
Hi @KennethRobbeFrucon - did you think this is a bug in Draggable? I'm not sure how exactly we'd alter the middle button behavior. There's nothing we're doing in Draggable specifically that's linked to a particular mouse button, but of course it's very tricky to deal with things that are supposed to be draggable AND you also want to retain their native behavior. In other words, the original event needs to have preventDefault() called...or not (and there are tradeoffs either way). If you have any specific suggestions, I'm all ears. :)

**Comment by ZachSaucier** [comment]
Seems like a minor bug to me given regular links that are middle clicked don't have this behavior.

**Comment by ZachSaucier** [comment]
You should be able to work around this by detecting if it's the middle mouse click in the onRelease:

```
onRelease: function(e) {
  if (e.which == 2 || e.button == 4 ) {
    e.preventDefault();
  }
},
```

**Comment by KennethRobbeFrucon** [comment]
Hi both, thanks for your quick feedback! The bug does seem to be related to Draggable, as this behaviour doesn't occur outside of it, but I understand it's a difficult thing to handle. The work around suggested by @ZachSaucier works!
