### ISSUE TITLE
display error when data is big

### ISSUE THREAD

**Issue by xudamin** [greensock/GSAP#379]
I use TweenLite/TimelineMax to translate 0 to 1000000, the result display wrong. 
here are some picture:
![139197F7-8C14-4b19-84D4-46D520FFFFB0](https://user-images.githubusercontent.com/17488002/81264027-529ed080-9073-11ea-8b45-0aad561cf145.png)
![9438022B-36FD-46b9-87A2-90ACA7DCC3E7](https://user-images.githubusercontent.com/17488002/81264031-53cffd80-9073-11ea-961c-32d67d6e3b9b.png)
I expect height from 0 to 1000000. the result is wrong。
but when I transform height from 0 to 100000. the result is correct。

**Comment by xudamin** [comment]
here is the bug code.
`let test = {height: 0}`
`let tl = new TimeLineLite({`
`onUpdate: function() {console.log(test.height)}`
`})`
`tl.add(TweenLite.to(test, 2, {height: 1000000}))`

**Comment by OSUblake** [comment]
Works fine here. 
https://codepen.io/osublake/pen/20c890a27a391f9d4a05b596519b2ea9

Make sure you're using the latest version. There was a bug in older version for large numbers.

**Comment by OSUblake** [comment]
BTW, TweenLite, TweenMax, TimelineLite, and TimelineMax are deprecated.

```js
gsap.timeline({
  onUpdate() {
    console.log(test.height)
  }
})
.to(test, {
  duration: 2,
  height: 1000000
})
```

**Comment by ZachSaucier** [comment]
Perhaps you're using an old version of GSAP? There was a bug in an earlier version of GSAP 3 that had this issue.
