### ISSUE TITLE
gsap/ThrowPropsPlugin

### ISSUE THREAD

**Issue by PaulieScanlon** [greensock/GSAP#381]
Hey team! can i ask a question about the `ThrowPropsPlugin`. 

I know that to use it i need to be part of Club GreenSock and i'm more than happy to sign up and pay but...

I'll be using the `ThrowPropsPlugin` in an open source project which will be published to `npm` 

What are the guidelines around using a paid for plugin in an open source project?

Kinda related to this: https://greensock.com/forums/topic/20166-using-club-greensock-perks-in-open-source-projects/

**Comment by jackdoyle** [comment]
Thanks for checking! I answered your question in the forums: https://greensock.com/forums/topic/24215-draggable-open-source/?tab=comments#comment-114829
