### ISSUE TITLE
not working reverse() and delay()

### ISSUE THREAD

**Issue by alfakrai** [greensock/GSAP#382]
Hello. It's a long-standing problem:
https://greensock.com/forums/topic/14609-on-reverse-complete-delay/.
https://greensock.com/forums/topic/10239-delay-reverse-timeline/
https://greensock.com/forums/topic/19153-reverse-timeline-with-a-delay-and-pause-event/

The delay does not work together with reverse(). All solutions suggest using delayedCall, but this is not very convenient.

It seems to me that if the delay works in play() and restart(), it must also work in reverse();

Can we expect to add this function in the next update?

**Comment by ZachSaucier** [comment]
Hey alfakrai. What do you mean it's "not very convenient"? Do you have an example that you can show us? 

Adding this would either a) be a breaking change or b) require expanding the API so we would want to have very good reason to add it to GSAP's core.

**Comment by alfakrai** [comment]
It is logical, so it has to be.

**Comment by jackdoyle** [comment]
@alfakrai it would be super helpful if you provided an example that isn't served well by the current API.

Also, I didn't understand what you meant by "delay works with play() and restart()..." but that isn't true (unless I misunderstood your point). The "delay" is only at the front end of the animation and it merely affects where the animation's startTime is on its parent timeline, so it doesn't make much sense to have that in reverse(). The restart() method is the only one that has a parameter that allows you to include the original delay when doing the restart...I don't see how that'd be expected to work with reverse(). And play() has no such ability either. Did we miss something? 

If you're looking to delay a reverse(), is there a reason you don't want to use a delayedCall()? I'm sure once we see an example from you, we'll be able to either see the problem or advise you better.

**Comment by mohamedzouine827** [comment]
hi my delay and duration is not working:
`import gsap from "gsap";
import { useGSAP } from "@gsap/react";

export default function BlurHover() {
    const elements = [
        "Email",
        "Instagram",
        "Twitter",
        "Youtube",
        "LinkedIn",
    ];

    useGSAP(() => {
        gsap.from('#text', {
            duration: 6, // Increase duration to 6 seconds
             // Increase delay to 5 seconds
            ease: "power1.inOut",
            stagger: 4,
            rotate: 0,
            y: 0, // Start from the bottom
            delay: 5,

        });
        
        
    });

    return (
        <section className="min-h-screen flex justify-center items-center">
            <div className="w-[95vw] h-[70vh] flex items-center justify-center">
                <div  className="  w-full py-24 flex flex-wrap justify-center overflow-hidden ">
                    {elements.map((element) => (
                        <span
                            id="text"
                            key={element}
                            className="relative inline-block rotate-12 translate-y-12 uppercase text-7xl mx-20 my-7  text-center font-semibold  cursor-cell break-all blur-sm opacity-35 transition-all ease-in-out duration-400 hover:opacity-100 hover:blur-none shadow-gray-400 text"
                        >
              {element}
            </span>
                    ))}
                </div>
            </div>
        </section>
    );
}
`

**Comment by jackdoyle** [comment]
@mohamedzouine827 It's typically best not to hijack an old/closed thread - please create a minimal demo (like a Stackblitz) that clearly illustrates the issue and post in the forums at https://gsap.com/community

Here's a starter template you can fork: 
https://stackblitz.com/edit/gsap-react-basic-f48716

Also, make sure you register the useGSAP hook: 
```javascript
gsap.registerPlugin(useGSAP);
```
Also, it looks like you're assigning the same ID to multiple elements which you're not supposed to do in markup. You're also using selector text in your tween, but you never defined a scope for your useGSAP() which should still work fine, but if you use multiple instances of the same component, your selectors will collide. I'd strongly recommend reading https://gsap.com/react
