### ISSUE TITLE
the 3.30 had some wrong

### ISSUE THREAD

**Issue by chuangwei** [greensock/GSAP#383]
![image](https://user-images.githubusercontent.com/5902016/83387940-2da63f00-a420-11ea-8034-abd27782f5ed.png)

**Comment by ZachSaucier** [comment]
Thanks for catching that. You can replace that line with the following and it should fix the error. We'll make sure that's in the next update.

```
path?: gsap.SVGPathValue | gsap.TweenValue | gsap.Point2D[]| gsap.PathObject[];
```

**Comment by Yanduz** [comment]
Yes, I also have this problem on Angular 9.
![Xnip2020-06-04_01-55-59](https://user-images.githubusercontent.com/27006337/83697102-c8607280-a606-11ea-98d3-d9f28794e874.jpg)

**Comment by salomontiago** [comment]
I'm with this problem too.

**Comment by jvanoostveen** [comment]
It is keeping us from updating, as I can not manually change this file on each install (build server / developer machine). As it seems such a trivial fix, please provide a patch release with it.
(I'm still very happy the typings are now shipped with GSAP) :)

**Comment by jackdoyle** [comment]
Yep, we'll be releasing a patch before the weekend. Sorry about the hassle, and thanks for your patience.

**Comment by jvanoostveen** [comment]
Great! I'll pick it up on my update-Monday.

**Comment by jackdoyle** [comment]
This should be resolved in the latest release.
