### ISSUE TITLE
Tweens added to a timeline containing an infinite tween start after the first iteration

### ISSUE THREAD

**Issue by chototoro** [greensock/GSAP#384]
Hi there, i just encountered an odd behavior with infinite tweens. It might be on purpose, but i'm not sure.

When a timeline contains an infinite tween (created with the attribute { repeat: -1 }), the next addition to that timeline will not be positioned at the end (which i think for infinite timelines is at 100000000 seconds), but at the end of the first iteration of the infinite tween.
If the infinite tween is replaced by a tween with a finite one (with a repeat attribute different than -1), the next tween is correctly positioned at the end of all the iterations.

I made a demo to illustrate the problem: https://codepen.io/chototoro/pen/jOWOPXE

I admit that adding tweens at the end of an infinite timeline doesn't necessarily make sense :)
But maybe they should simply be ignored, as in theory they would never start?

**Comment by chototoro** [comment]
No problem, thank you for taking the time to explain it one more time! ;)

**Comment by jackdoyle** [comment]
Happy to help, @chototoro !
