### ISSUE TITLE
Minification of ScrollTrigger changes plugin name 

### ISSUE THREAD

**Issue by dexster** [greensock/GSAP#385]
I'm getting an issue with a prod Angular build due to optimisation which change the class name from "ScrollTrigger" to "e". I'm not sure this is limited to Angular as most ugllify/minify packages shorten names.

In scrollTrigger.js plugin this is passed to the registerPlugin and by this stage the name has already been shortened to "e":
`_getGSAP() && gsap.registerPlugin(ScrollTrigger);`

This gets added to the globals as e which causes the  check - `_globals.ScrollTrigger` - to fail
in the _scrollTrigger function

![Screenshot 2020-06-04 at 12 17 58](https://user-images.githubusercontent.com/6392334/83748145-06d74b00-a662-11ea-9519-841697139ea8.png)

I know there are options to keep names unchanged during minification but it would be great to try find a solution at the source.
  
We should probably not rely on the class name but create another property, something like "pluginName" which would then be added to the global object?

**Comment by dexster** [comment]
I was wondering why this wasn't happening with other plugins. I see they are created like this:

```
export const CSSPlugin = {
	name: "css",
```

**Comment by jackdoyle** [comment]
Hm, I can't seem to reproduce that issue, but we did fix a different issue which may be related - ScrollTrigger no longer relies on the "name" being implicitly defined. I suspect in 3.3.1 (due out soon), this won't be an issue anymore. Would you like to preview it?

**Comment by dexster** [comment]
Yup. Let's see if it solves this

**Comment by jackdoyle** [comment]
You can npm install this file: https://assets.codepen.io/16327/gsap-beta.tgz

Better?

**Comment by dexster** [comment]
That fixed it. Thanks
