### ISSUE TITLE
Property 'staggerTo' does not exist on type 'Timeline[Lite, Max]'

### ISSUE THREAD

**Issue by anzorasadov** [greensock/GSAP#386]
I am getting an issue when I try to move my previously created vanillajs animation sequence into my vue application (running on typescript). Here is the code (altered to not distract from the core issue): 

```js
    var tl = new TimelineMax()

    tl.set(elems, {  x: 1350 })
      .add('anim', 1)
      .to(otherElems, 0.8, { x: 0, ease: Power1.easeInOut }, 'anim')
      .staggerTo(elems, 0.8, { x: 0, ease: Power1.easeInOut }, 0.03, 1, null, null, 'anim')
```

The issue I am getting is:
`Property 'staggerTo' does not exist on type 'TimelineMax'.`

**Comment by ZachSaucier** [comment]
Hey anzorasadov. That code seems to compile for me using the latest version of GSAP with our updated Typescript definitions (GSAP 3.3 had a significant upgrade in the Typescript definitions and 3.3.1 being released this weekend has even more improvements). What version of GSAP are you using?

We highly recommend using [GSAP 3](https://greensock.com/3/) and the formatting that comes with it. It has a smaller file size, a sleeker API, and a bunch of new features!

You could rewrite the code above in all GSAP 3 formatting by doing:

```
const tl = gsap.timeline({defaults: { duration: 0.8, ease: 'power1.inOut' });

tl.set(elems, {  x: 1350 })
  .add('anim', 1)
  .to(otherElems, { x: 0 }, 'anim')
  .to(elems, { x: 0, stagger: 0.03 }, 'anim')
```

Or even 

```
const tl = gsap.timeline({defaults: { duration: 0.8, ease: 'power1.inOut' });

tl.set(elems, {  x: 1350 })
  .to(otherElems, { x: 0 }, 1)
  .to(elems, { x: 0, stagger: 0.03 }, '<')
```

**Comment by anzorasadov** [comment]
Thanks for the quick response. I developed the animation sequence in version 2 a while back and moved it into my Vue environment where my gsap version is 3.3.0. I realised that 5 minutes after posting the issue, changed up my code, works perfectly fine. thank you!
