### ISSUE TITLE
ScrollTrigger bug

### ISSUE THREAD

**Issue by wlinglinux** [greensock/GSAP#390]
The ScrollTrigger callback function onEnter is not triggered in a Vue;I have checked the update method, and the variable change is undefined
![image](https://user-images.githubusercontent.com/286261/84482306-1261ec00-acca-11ea-841d-4951eebed3e7.png)

**Comment by wlinglinux** [comment]
But adjusting the browser window is fine

**Comment by ZachSaucier** [comment]
I'm no good with Vue but it seems to be working fine for me: https://codepen.io/GreenSock/pen/dyGMqje?editors=0010

Can you please create a minimal demo that recreates the issue?

**Comment by wlinglinux** [comment]
Once initialized, call function window.ScrollTrigger.refresh()  is OK。
