### ISSUE TITLE
ScrollTrigger dependency was not found

### ISSUE THREAD

**Issue by stephanedemotte** [greensock/GSAP#391]
Hello, i try to import `ScrollTrigger`

```
import { ScrollTrigger } from "gsap/ScrollTrigger"
```

I got `This dependency was not found:`, 

I've downloaded the lastest version of gsap from my dashboard and i use `gsap-bonus.tgz`.

I can import all other plugin, like `SplitText` etc... but ScrollTrigger is the the only one i can't import.

Thanks !

**Comment by ZachSaucier** [comment]
Hey Stephane. Can you confirm that you're loading ScrollTrigger 3.3.3? That's the latest version. You might need to remove/uninstall the old version of GSAP that you had before and reinstall using the latest version.

**Comment by stephanedemotte** [comment]
Yep i've replaced, my old `gsap-bonus.tgz", in my `package.json` i have ` "gsap": "./gsap-bonus.tgz"` it's the 3.3.3 version :/

**Comment by ZachSaucier** [comment]
Did you try removing the /gsap directory from your npm-modules? What framework are you using?

**Comment by stephanedemotte** [comment]
i don't use the node_modules, i use `gsap-bonus.tgz`, it's in a vue-cli project

When i import `ScrollTrigger`
<img width="644" alt="Screen Shot 2020-06-15 at 9 59 04 AM" src="https://user-images.githubusercontent.com/2158130/84666449-1589f180-aeef-11ea-9dfa-9d74d780e831.png">
<img width="928" alt="Screen Shot 2020-06-15 at 9 59 21 AM" src="https://user-images.githubusercontent.com/2158130/84666457-1884e200-aeef-11ea-8889-ba47057da081.png">

When i import `SplitText`
<img width="799" alt="Screen Shot 2020-06-15 at 9 59 36 AM" src="https://user-images.githubusercontent.com/2158130/84666486-2175b380-aeef-11ea-9a0e-bf44b9174d40.png">
<img width="510" alt="Screen Shot 2020-06-15 at 9 59 42 AM" src="https://user-images.githubusercontent.com/2158130/84666493-2470a400-aeef-11ea-8d44-b1d414395218.png">

When i unzip the `tgz`
<img width="410" alt="Screen Shot 2020-06-15 at 10 00 04 AM" src="https://user-images.githubusercontent.com/2158130/84666537-318d9300-aeef-11ea-8d1f-3be898224a9a.png">

`ScrollTrigger` exist

It's really wierd :/

**Comment by stephanedemotte** [comment]
Ok sorry i have to replace 
```
    "gsap": "./gsap-bonus.tgz",
```
by

```
    "gsap": "file:gsap-bonus.tgz",
```

With that it's ok, sorry for the noize !
