### ISSUE TITLE
Typescript declaration for 'set' missing in tween.d.ts

### ISSUE THREAD

**Issue by alexvetter** [greensock/GSAP#392]
It seems like the static function `set` is missing in type definition file [`tween.d.ts`](https://github.com/greensock/GSAP/blob/master/types/tween.d.ts).

https://github.com/greensock/GSAP/blob/ff8ed36fe52b41fec5bd22daecda76fb7dea5518/src/gsap-core.js#L2448

The definition should be as simple as follows:

```typescript
static set(targets: TweenTarget, vars: TweenVars): Tween;
```

**Comment by ZachSaucier** [comment]
Thanks for catching that. It'd be good for us to update that file and add JSDoc comments as well. I can get to it this week.
