### ISSUE TITLE
animation with clearProps value of 'transformOrigin' clears entire transform

### ISSUE THREAD

**Issue by tombigel** [greensock/GSAP#393]
the clearProps attribute in css plugin supports both camelCase and kebab-case attributes in it's list, but specifically transformOrigin doesn't work in camelCase, only in kebab-case.
Further more, if transformOrigin is present in the clearProps string it will be treated as if 'transform' was passed to clearProps.

GSAP 3.X 
Demo:
https://codepen.io/tombigel/pen/RwrVVMg

**Comment by jackdoyle** [comment]
Good catch, @tombigel . And thanks so much for the reduced test case! 

This should be resolved in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better?

**Comment by jackdoyle** [comment]
Should be resolved in the latest release.
