### ISSUE TITLE
Weird behavior with import

### ISSUE THREAD

**Issue by knynkwl** [greensock/GSAP#394]
Version ^3.3.4

I was running into some strange things with my build, and found out that it was from importing gsap.

I am running a webpack build and stripped down my app.js to just three lines:
```
import {gsap} from 'gsap'
gsap.to(document.body, 1, { opacity: 0 })
console.log('test');
```

When reloading, I don't get any console message.

When removing 
```
import {gsap} from 'gsap'
gsap.to(document.body, 1, { opacity: 0 })
```

I get the console message `test`

Any idea what could be happening?

**Comment by knynkwl** [comment]
I should say importing any other npm package is working fine when testing.

**Comment by jackdoyle** [comment]
My guess would be that in your environment "document" or "document.body" is undefined when that code is executed, thus it's throwing an error? (unrelated to GSAP). Tough to troubleshoot blind though. I know that thousands of people use GSAP via NPM and Webpack...shouldn't be a problem at all. 

Maybe try console.log(document.body) there and see if that shows up?

**Comment by knynkwl** [comment]
Yeah it's very strange I've never come across this with gsap. document.body is showing up fine.

It's when I add the import statement everything disappears, like I'm a hitting some kind of return.

**Comment by jackdoyle** [comment]
Very difficult to troubleshoot blind. Can you provide the most reduced test case possible so we can reproduce the issue on our end?

**Comment by knynkwl** [comment]
Sure thing, here's my a scaled down version. Running `npm start` will start webpack and watch for files. I just tested it and it's doing the same behavior, maybe it's something to do with my webpack config?

https://drive.google.com/file/d/1-piOxBlYt1s_WqxMDWQQXbpt_50yDudT/view?usp=sharing

**Comment by knynkwl** [comment]
Looks like something with `gsap-core.js` I went through the files and commented out each import and it seems to be breaking once getting to gsap-core. That file is too gib for me to debug but that's as for as I got.

**Comment by knynkwl** [comment]
@jackdoyle I think I have figured it out. It's a webpack optimization setting that is causing the issue.

Setting `optimation.splitChunks.chunks = 'all'` is the culprit. Setting it to any other value works, it just doesn't like `all` I think I have some settings configured wrong. 

Thanks!

**Comment by jackdoyle** [comment]
Thanks for letting us know.
