### ISSUE TITLE
Declaration for gsap/all

### ISSUE THREAD

**Issue by Rechdan** [greensock/GSAP#395]
I was having issues with "gsap/all" being not declared, so I made this declaration file:

```ts
declare module 'gsap/all' {
	import gsap from 'gsap';
	import CSSPlugin from 'gsap/CSSPlugin';

	var gsapWithCSS = gsap.registerPlugin(CSSPlugin) || gsap, // to protect from tree shaking
		TweenMaxWithCSS = gsapWithCSS.core.Tween;

	export { gsapWithCSS as gsap, gsapWithCSS as default, CSSPlugin, TweenMaxWithCSS as TweenMax };

	export { TweenLite, TimelineMax, TimelineLite, Power0, Power1, Power2, Power3, Power4, Linear, Quad, Cubic, Quart, Quint, Strong, Elastic, Back, SteppedEase, Bounce, Sine, Expo, Circ, wrap, wrapYoyo, distribute, random, snap, normalize, getUnit, clamp, splitColor, toArray, mapRange, pipe, unitize, interpolate, shuffle } from 'gsap/gsap-core';

	export * from 'gsap/Draggable';
	export * from 'gsap/CSSRulePlugin';
	export * from 'gsap/EaselPlugin';
	export * from 'gsap/EasePack';
	export * from 'gsap/MotionPathPlugin';
	export * from 'gsap/PixiPlugin';
	export * from 'gsap/ScrollToPlugin';
	export * from 'gsap/ScrollTrigger';
	export * from 'gsap/TextPlugin';
}
```

Not sure if it really covers everything, I copied and modified the content from all.js, but now VS Code is recognizing it 😁

**Comment by OSUblake** [comment]
It's already declared, but it has trouble finding it for some reason. 🤷‍♂️

If you import from `gsap` at least one time, it will find the declarations, or you can specify where the declarations are in your tsconfig.

```json
{
  "compilerOptions": {
    ...
  },
  "files": [
    "node_modules/gsap/types/index.d.ts"
  ]
}
```

**Comment by Rechdan** [comment]
> It's already declared, but it has trouble finding it for some reason. 🤷‍♂️
> 
> If you import from `gsap` at least one time, it will find the declarations, or you can specify where the declarations are in your tsconfig.
> 
> ```json
> {
>   "compilerOptions": {
>     ...
>   },
>   "files": [
>     "node_modules/gsap/types/index.d.ts"
>   ]
> }
> ```

Don't knew that hack, thanks for sharing it!
