### ISSUE TITLE
MotionPathPlugin.cacheRawPathMeasurements doesn't have a type definition

### ISSUE THREAD

**Issue by theosherry** [greensock/GSAP#396]
As per title, there's no type definition for this method.

We're told in the [documentation](https://greensock.com/docs/v3/Plugins/MotionPathPlugin/static.getPositionOnPath()) to use this method so I'm assuming it's meant to be a public method.

**Comment by jackdoyle** [comment]
Thanks for pointing that out - we'll get it into the next patch release.

**Comment by jackdoyle** [comment]
Should be resolved in the latest push.
