### ISSUE TITLE
Vue.js import DrawSVGPlugin not working

### ISSUE THREAD

**Issue by raulmelo** [greensock/GSAP#397]
What happened to the Plugin?
not working with Vue.js 
```js
<script>
import { TimelineLite,TweenMax } from "gsap/all";
import { DrawSVGPlugin } from "gsap/DrawSVGPlugin";
const plugins = [DrawSVGPlugin];
export default {
  mounted() {
    
  }
};
</script>

```

Terminal 
This dependency was not found:
` gsap/DrawSVGPlugin in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/Skill/section/progress-skill.vue?vue&type=script&lang=js&`

**Comment by ZachSaucier** [comment]
Hey raulmelo. What version of GSAP are you loading?

If you're loading GSAP 3 we highly recommend that you don't use the Lite/Max stuff anymore. You can just load the gsap object instead. See the [GSAP 3 Migration Guide](https://greensock.com/3-migration) for more info.

If you're using GSAP 3 you need to make sure you register external plugins using [.registerPlugin()](https://greensock.com/docs/v3/GSAP/gsap.registerPlugin()). See [the installation guide](https://greensock.com/docs/v3/Installation?checked=core,drawSVG) for more info. It even has a handy install helper that generates the import code that you can copy and paste until you get more comfortable with it.

**Comment by jackdoyle** [comment]
Also, in case you weren't aware, DrawSVGPlugin is a members-only benefit for Club GreenSock - it is NOT in the regular github/NPM repo. You need to download it from greensock.com

Sign up at https://greensock.com/club

**Comment by raulmelo** [comment]
Hey @jackdoyle  and @ZachSaucier, Thank you very much, I will become a member of GSAP to have the DrawSVGPlugin plugin.

**Comment by jackdoyle** [comment]
That's great! Welcome aboard. If you need anything else, please don't hesitate to post your question in our forums. It's a great place to learn. https://greensock.com/forums
