### ISSUE TITLE
Jest does not work with `gsap/PixiPlugin`

### ISSUE THREAD

**Issue by RodrigoHamuy** [greensock/GSAP#398]
Steps to reproduce

1. Go to https://repl.it/repls/FirmMiserableSpools#sum.js
2. Click `run`.

Expected: Test should run.

Currently: You get the following error:

```
/node_modules/gsap/PixiPlugin.js:371
    export var PixiPlugin = {
    ^^^^^^
    SyntaxError: Unexpected token 'export'
```

Observations:

Jest can't work with ES6 modules. Can PixiPlugin be exported in a format that Jest can digest? Thanks.

**Comment by ZachSaucier** [comment]
Hey Rodrigo. Just import the non-modules version:

```
require("gsap/dist/PixiPlugin");
```

**Comment by RodrigoHamuy** [comment]
Amazing, thanks @ZachSaucier. Is there something similar for `pixi-projection` too?

**Comment by RodrigoHamuy** [comment]
Works like a charm 👍

**Comment by ZachSaucier** [comment]
I've never head of [pixi-projection](https://github.com/pixijs/pixi-projection). GSAP doesn't have any tools like that, no.
