### ISSUE TITLE
ScrollTrigger refreshPriority interface required property

### ISSUE THREAD

**Issue by dexster** [greensock/GSAP#400]
3.4.1 has a breaking change due to the refreshPriority in the ScrollTriggerInstanceVars interface not being optional.

Please add new properties as optional if possible or up the minor version (should be major but I realise that's not always best depending on versioning strategy).

I've added the refreshPriority to my code and set it to 1 for now as I can't find documentation on this property.

**Comment by ZachSaucier** [comment]
Hey dexster. I presume you are using Typescript? 

You're right that `refreshPriority` should be optional. In the scroll-trigger.ts file you can fix this on your side simply by changing the following line (line 407):

```
refreshPriority: number;
// to 
refreshPriority?: number;
```

We'll make sure that this is included in the next minor version (which should be pushed very soon).

**Comment by jackdoyle** [comment]
Sorry about that! Silly mistake on my part. Should be fixed in the most recent release.
