### ISSUE TITLE
Updating to any version higher than 3.4.0 breaks my animations

### ISSUE THREAD

**Issue by daviddelusenet** [greensock/GSAP#401]
I'm using React in combination with GSAP and I've the following code:

```tsx
const payOffEnter = useCallback(() => {
  if (titleWrapperRef.current) {
    return gsap.to(titleWrapperRef.current, {
      paused: true,
      opacity: 1,
      delay: 0.2,
      duration: 0.7,
      translateX: 0,
    });
  }
}, [titleWrapperRef])();

const payOffLeave = useCallback(() => {
  if (titleWrapperRef.current) {
    return gsap.to(titleWrapperRef.current, {
      opacity: 0,
      paused: true,
      duration: 0.3,
      ease: 'power1.in',
      translateX: `${Spacers.medium}`,
    });
  }
}, [titleWrapperRef])();

const onEnterCallback = useCallback(() => {
  payOffLeave.kill();
  payOffEnter.play(0);
}, [payOffEnter, payOffLeave]);

const onLeaveCallback = useCallback(() => {
  payOffEnter.kill();
  payOffLeave.play(0);
}, [payOffEnter, payOffLeave]);
```

When I update any GSAP version higher than `3.4.0` (so `3.4.1` or `3.4.2` at the moment) this code doesn't work properly anymore. The `payOffEnter` animation completes but doesn't change the styling the second time it plays.

**Comment by ZachSaucier** [comment]
Hey David. Any idea _why_ it doesn't work properly? Can you please try to create a minimal demo of the issue and share that with us? [CodeSandbox.io](https://codesandbox.io/) is good for that sort of thing.

**Comment by daviddelusenet** [comment]
No idea and don't have the time to create a Codepen, sorry.

My website contains of different sections placed below each other. This section calls the `onEnterCallback` function when it enters the viewport and calls `onLeaveCallback` when it leaves the viewport.

**Comment by ZachSaucier** [comment]
> This section calls the onEnterCallback function when it enters the viewport and calls onLeaveCallback when it leaves the viewport.

Are you using ScrollTrigger to do this? Or something else like an intersection observer?

**Comment by ZachSaucier** [comment]
A couple of comments based on your code:

- You should use `x` instead of `translateX`. 
- You kill off one animation each time that one of your callbacks fire - Are you recreating those animations? Otherwise they won't work a second time. This should be true regardless of the version of GSAP that you're using.

___

Here's how I'd do it (not React-ified):
```
gsap.utils.toArray('section').forEach(section => {
  const anim = gsap.from(section, {
    opacity: 0,
    x: 100,
    duration: 0.3,
    ease: 'power1.in'
  });
  
  ScrollTrigger.create({
    trigger: section,
    animation: anim,
    toggleActions: "play reverse play reverse"
  });
});
```
[Demo](https://codepen.io/GreenSock/pen/eYJxeQj?editors=0010)

**Comment by jackdoyle** [comment]
@daviddelusenet It is indeed rather difficult to figure out what's going on without a demo, but I suspect the problem is that you kill() a tween and then try to play() it. Do you mind me asking why you're doing that? Why kill() at all? That's definitely not a good idea. You should only kill() a tween when you want it DEAD and you don't want to use it anymore. :)

**Comment by daviddelusenet** [comment]
@jackdoyle thanks for your response.

The documentation says something else: https://greensock.com/docs/v3/GSAP/Tween/kill()

```
Note: after an animation is killed, it is possible to bring it back by calling a playback method, like play() or resume().
```

This is what I'm doing. Should I use `pause()` instead?

**Comment by jackdoyle** [comment]
Thanks for pointing out the inaccuracy in the docs. That's fixed. And yes, if you want to reuse it later, pause() is a much better option. 

In your code, though, you're calling play(0) immediately after kill(). In that case, there's absolutely no point in calling kill() or pause(). Make sense?

**Comment by daviddelusenet** [comment]
@jackdoyle I'm killing one tween and playing another.

**Comment by daviddelusenet** [comment]
How I have solved it:

```
payOffLeave.pause();
payOffEnter.restart();
```
