### ISSUE TITLE
ScrollToPlugin with offsetY

### ISSUE THREAD

**Issue by neo** [greensock/GSAP#402]
I notice that scrolling to the elements that's close to the bottom (which could never reach to the top) would still take into account the `offsetY` value, and never reach the top plus the offset position. And I'm wondering if it's expected and intended or a bug. Because for me, I would hope to the "scrollTo" element be as close to the target position (top edge plus the offset) as possible. Thank you!

**Comment by neo** [comment]
side note, thank you for this great library! it just works and it always has been. super reliable and robust!

**Comment by jackdoyle** [comment]
Glad you're enjoying the tools, @neo! 

I'm not sure I understand your question - do you have a minimal demo we can look at? 

The browser won't let the page scroll past the top/bottom. So, for example, if you have a 50px tall element that's at the VERY bottom of the page, and you try to scrollTo that element and the viewport is 800px tall, the closest that element could possibly get to the top would be 750px because the browser would refuse to let it go any further. Does that help at all?

**Comment by neo** [comment]
Thank you for your timely reply!

To use the example you gave, when I also have a 30px offsetY, I think it now would go to 780px (750 + 30), but I was thinking would be great if it still goes to 750 because it didn't reach 30 from the top.

So I asked here and wondering if this is intended or could be a bug. Thanks!

**Comment by jackdoyle** [comment]
Ah, I see what you mean. I can improve that in the next release which you can preview at https://assets.codepen.io/16327/ScrollToPlugin3.min.js

Better?

**Comment by neo** [comment]
yes! I tried it out and I think it worked! thank you very much!
and also thank you for the timely support without asking whether I have the paid membership or not 😁 but we do have a business subscription to support the great work! thank you again!

**Comment by jackdoyle** [comment]
> thank you for the timely support without asking whether I have the paid membership or not 😁 but we do have a business subscription to support the great work! thank you again!

Ah, thanks so much for your support! And yes, we do our best to treat everyone the way we'd want to be treated which means not taking an approach of "sorry, we won't help you unless you've got a Club GreenSock membership". 

Happy tweening!

**Comment by neo** [comment]
Thank you! Tweening happily!

**Comment by neo** [comment]
Hi Jack!

Just checking in and wondering if you're going to cut a release soon, if not, I would probably include what you provided into my codebase directly. 😳 

Thank you again for the great support!

**Comment by jackdoyle** [comment]
We'll probably push within the next week or so. Feel free to use the preview version I sent you.

**Comment by neo** [comment]
thank you!
