### ISSUE TITLE
eventCallback Question

### ISSUE THREAD

**Issue by wpitallo** [greensock/GSAP#405]
https://greensock.com/docs/v3/GSAP/Tween/eventCallback()

Does this apply to GSAP 3.0?

.eventCallback( type:String, callback:Function, params:Array ) : [Function | self]
Gets or sets an event callback like "onComplete", "onUpdate", "onStart", "onReverseComplete" or "onRepeat" (onRepeat only applies to TweenMax or TimelineMax instances) along with any parameters that should be passed to that callback.

Specifically: onRepeat only applies to TweenMax or TimelineMax instances? As these no longer exist? 

Will these also work with only gsap-core?

**Comment by jackdoyle** [comment]
Yes, it applies to GSAP 3. Absolutely. That comment about "(onRepeat only applies to TweenMax or TimelineMax instances)" shouldn't be in the docs - I just deleted it. Sorry about the confusion there. It was from the legacy docs.

If you're having trouble with the functionality, we'd be happy to help - just please provide a minimal demo and we'll take a peek.

**Comment by wpitallo** [comment]
Ok cool thanks, no no problem at all, actually thought it might be an error with the docs.

Thanks for the help!
