### ISSUE TITLE
ScrollTrigger toggleClass.className property mismatch in TS definition and code implementation

### ISSUE THREAD

**Issue by wira** [greensock/GSAP#406]
TS definition is using `toggleClass.class` while code implementation is using `toggleClass.className`.
The result is a warning of 'Argument type {} is not assignable to parameter type TweenVars'

Reference code:
https://github.com/greensock/GSAP/blob/master/types/scroll-trigger.d.ts#L369

**Comment by jackdoyle** [comment]
Good catch - we'll fix that in the next release.

**Comment by jackdoyle** [comment]
Should be fixed in the latest release
