### ISSUE TITLE
GSAP ScrollToPlugin Issue in Nuxt.js project

### ISSUE THREAD

**Issue by huangxiaoxuan0621** [greensock/GSAP#408]
I am making the scroll effect with GSAP and vue-scrollmagic in my Nuxt.js project. The code is the following as:

import {gsap, TweenMax} from 'gsap'
import ScrollToPlugin from "gsap/ScrollToPlugin";
const plugins = [ScrollToPlugin];

export default {
    name: 'Test',
    mounted() {
        this.startAnimations(this.$refs)
    },
    methods: {
        startAnimations: function(refs) {
            var tween = TweenMax.to(refs.slide1, 0.5, {scrollTo:{y: 500}})
            const scene = this.$scrollmagic.scene({
                triggerElement: refs.slide1,
                triggerHook: 0,
                duration: "100%"
            })
            .setPin(refs.slide1)
            .setTween(tween)
            this.$scrollmagic.addScene(scene)
        }
    },
}

In this case, I have got the error as the following:

gsap-core.js?a5cf:3362 Uncaught TypeError: Failed to execute 'scrollTo' on 'Element': parameter 1 ('options') is not an object.

How can I solve this issue?

**Comment by ZachSaucier** [comment]
Hey huangxiaoxuan0621. A couple of notes:

- We recommend GSAP 3 and using the GSAP 3 syntax. You won't need to import TweenMax or anything like that. See the [GSAP 3 Migration Guide](https://greensock.com/3-migration/) for more info.
- We do not recommend ScrollMagic. We _highly_ recommend using the official GSAP scroll plugin, [ScrollTrigger](http://greensock.com/scrolltrigger/) instead. It's better in every way!

As for your error, please create a minimal demo of the issue using something like CodePen or CodeSandbox. You can learn more about how to do so [in this thread](https://greensock.com/forums/topic/9002-read-this-first-how-to-create-a-codepen-demo/).

**Comment by huangxiaoxuan0621** [comment]
Thanks for your quick response.
How can I install GSAP3 using the NPM command on my Nuxt.js project?

**Comment by ZachSaucier** [comment]
See [the GSAP Installation page](https://greensock.com/docs/v3/Installation) for details regarding installation 🙂

**Comment by huangxiaoxuan0621** [comment]
Already installed the package using `npm install gsap`, it's version2 or 3? How can I check gsap package version?

**Comment by ZachSaucier** [comment]
As stated, please [create a minimal demo](https://greensock.com/forums/topic/9002-read-this-first-how-to-create-a-codepen-demo/) because it's really hard for us to help blindly 🙂

**Comment by jackdoyle** [comment]
My best guess is that you forgot to register the ScrollToPlugin. 

```javascript
gsap.registerPlugin(ScrollToPlugin);
```

**Comment by huangxiaoxuan0621** [comment]
Thank, Mr. Jack
import { TweenMax, ScrollToPlugin, ScrollTrigger, gsap } from "gsap/all";

export default {
    name: 'Test',
    mounted() {
        gsap.registerPlugin(ScrollToPlugin)
        gsap.registerPlugin(ScrollTrigger)
        this.startAnimations(this.$refs)
    },
    methods: {
        startAnimations: function(refs) {
            //gsap.to(refs.slide1, 0.5, {scrollTrigger: refs.slide1, x:500})
            var tween = TweenMax.to(refs.slide1, 0.5, {scrollTo: {y:500}})
            const scene = this.$scrollmagic.scene({
                triggerElement: refs.slide1,
                triggerHook: 0,
                duration: "100%"
            })
            .setPin(refs.slide1)
            .setTween(tween)
            this.$scrollmagic.addScene(scene)
In this case, I have got the following as:
ERROR calling method 'setTween()': Supplied argument is not a valid TweenObject

**Comment by jackdoyle** [comment]
ScrollMagic is **NOT** a GreenSock product and we cannot support it. I **strongly** recommend switching to ScrollTrigger which can do everything ScrollMagic does plus a LOT more, and is fully integrated with GSAP 3. The error you're getting is from ScrollMagic. You're welcome to try to contact ScrollMagic's author for help, but last I checked there were almost 500 open issues in that Github repo, and it hasn't been updated in a very long time. 

If you still need help with anything GSAP-specific, please provide a minimal demo in CodePen or something. See https://greensock.com/demo

Also it doesn't make much sense that you seem to be importing/registering ScrollTrigger, but your code is actually using ScrollMagic. See https://greensock.com/scrolltrigger for details about ScrollTrigger.

**Comment by huangxiaoxuan0621** [comment]
Thanks, Mr.Jack
I have just tried with scrollTrigger.

        gsap.registerPlugin(ScrollToPlugin)
        gsap.registerPlugin(ScrollTrigger);
        gsap.utils.toArray(".slide").forEach((panel, i) => {
            console.log($(panel).height() * (i+1))
            var tl = TweenLite.to(panel, .5, {scrollTo:{y:$(panel).height() * (i+1), autoKill:false},ease: Linear.easeNone})
            ScrollTrigger.create({
                animation: tl,
                trigger: panel,
                start: "top top",
                pin: true,
                pinSpacing: false
            });
        });
But the scrollTo is still not working.

**Comment by ZachSaucier** [comment]
Please make a complete minimal demo as [we've told you to](https://greensock.com/demo). Without one, we cannot help you.

**Comment by huangxiaoxuan0621** [comment]
https://codepen.io/andystent/pen/GRgjBdJ
I want to make my page as the above

**Comment by ZachSaucier** [comment]
> I want to make my page as the above

That does not help us. We need to see _your code_ that recreates the issue.

**Comment by huangxiaoxuan0621** [comment]
Honestly, my project is based on Nuxt.js
I don't know how to make a minimal demo with Nuxt.js

**Comment by ZachSaucier** [comment]
Start with [this demo](https://codesandbox.io/s/fast-waterfall-w72f9). Make it recreate the issue that you're facing while stripping out all of the unnecessary parts.

**Comment by huangxiaoxuan0621** [comment]
https://codesandbox.io/s/dreamy-fog-tqehl
This is a minimal demo

**Comment by ZachSaucier** [comment]
That demo doesn't recreate the issue (it just has many errors). But alas.

It looks like you're trying to do something like [this thread](https://greensock.com/forums/topic/24428-using-scrolltrigger-and-scrollto-as-fullpagejs-does/?tab=comments#comment-116284). The main issue is that you're importing things incorrectly. In Nuxt you should load the UMD version, as covered in the installation docs:

```
import { gsap } from "gsap/dist/gsap";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
```

Then you can use the approach in the thread I link to above: https://codesandbox.io/s/goofy-kilby-0389x?file=/pages/index.vue

**Comment by huangxiaoxuan0621** [comment]
Thank you so much
It works perfectly.

**Comment by huangxiaoxuan0621** [comment]
Scroll up not working.
Now it only works with scroll down
Could you please let me know it?

**Comment by ZachSaucier** [comment]
```
gsap.utils.toArray(".slide").forEach((panel, i) => {
      ScrollTrigger.create({
        trigger: panel,
        end: "bottom bottom",
        onEnter: () => goToSection(panel),
        onEnterBack: () => goToSection(panel),
      });
    });
```

**Comment by huangxiaoxuan0621** [comment]
Wonderful!!!

**Comment by jormaturkenburg** [comment]
If there was an Oscar for best and friendliest support of a software library. Greensock would win it every single year. You guys are something else <3

**Comment by OSUblake** [comment]
> In Nuxt you should load the UMD version, as covered in the installation docs:

You don't have import the UMD files if you add this to the build part of the nuxt.config.js file.
```js
build: {
    transpile: ["gsap"], // no need to import UMD
    /*
     ** You can extend webpack config here
     */
    extend(config, ctx) {}
  }
```

**Comment by jackdoyle** [comment]
@jormaturkenburg your comment made my day! Thanks for noticing the effort we put in. Means a lot.
