### ISSUE TITLE
ScrollTo not working properly

### ISSUE THREAD

**Issue by huangxiaoxuan0621** [greensock/GSAP#409]
I am going to make a sliding effect like https://codepen.io/andystent/pen/GRgjBdJ on Nuxt.js.
So I had tried with the code snippet below.

 gsap.utils.toArray(".slide").forEach((panel, i) => {
            console.log($(panel).height() * (i+1))
            var tl = TweenLite.to(panel, .5, {scrollTo:{y:$(panel).height() * (i+1), autoKill:false},ease: Linear.easeNone})
            ScrollTrigger.create({
                animation: tl,
                trigger: panel,
                toggleActions: "restart none reverse none"
            });
        });

But the scrollTo is not working.

**Comment by ZachSaucier** [comment]
Please stick to the other thread (#408).
