### ISSUE TITLE
IE10 vs GSAP 3.5.0

### ISSUE THREAD

**Issue by flaugere** [greensock/GSAP#410]
Hi,

I don't know browser support policies but we find one error with IE10 since 3.5.0.
Error message : Object expected
Line concerned : https://github.com/greensock/GSAP/blob/719be8da0e4b02e616a0d617393279474a85ab60/dist/gsap.js#L2731

Thanks for your work.

**Comment by jackdoyle** [comment]
Yes indeed, we're aware of this and already have a fix in place for the next release. Thanks for letting us know.  3.5.1 should work great all the way back to IE9.
