### ISSUE TITLE
Parent component GASP scrolltrigger listens the button event in child component

### ISSUE THREAD

**Issue by huangxiaoxuan0621** [greensock/GSAP#411]
I have a Nuxt.js project. And there are 2 components ( parent, child )
The parent component is implementing the scrollTo effect by scroll trigger plugin.
If the button clicks on the child component, the scroll triggers. How can I prevent the scroll trigger when the button clicks.

Index.vue

<template>
    <div>
        <section class="section-slide">
            <div class="module-background">
                <Carousel />
            </div>
        </section>
        <section class="section-slide" >
            <div class="module-background">
                <ScooterSection />
            </div>
        </section>
        <section class="section-slide">
            <div class="module-background">
                <ContactForm />
            </div>
        </section>
    </div>
</template>
...........
import { gsap } from "gsap/dist/gsap";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

..........
    computed: {
        mainSectionNumber () {
            return this.$store.state.mainSectionNumber
        }
    },
    mounted() {

        gsap.registerPlugin(ScrollToPlugin, ScrollTrigger);

        gsap.utils.toArray(".section-slide").forEach((panel, i) => {
            ScrollTrigger.create({
                trigger: panel,
                onEnter: () => this.goToSection(panel, i)
            });

            ScrollTrigger.create({
                trigger: panel,
                start: "bottom bottom",
                onEnterBack: () => this.goToSection(panel, i)
            });
        });
    },

    methods: {
        goToSection(section, index, anim) {
            gsap.to(window, {
                scrollTo: { y: section, autoKill: false },
                duration: 0.5
            });

            if (anim) {
                anim.restart();
            }
            this.$store.commit('changeMainSectionNumber', index);
        }
    }
}

ScooterSection.vue
export default {
    data() {
        return {
            activeColor: 'white',
        }
    },
    methods: {
        changeColor(color){
            this.$store.commit('changeColor', color);
            this.activeColor = color
        }
    }
}
</script>

**Comment by jackdoyle** [comment]
Hi @huangxiaoxuan0621. Typically Github issues are for filing issues that you think exist in the project, not for general questions about how to do things in Nuxt. If you have a GSAP-specific question, please post in our forums at https://greensock.com/forums and we'd be happy to help. If it's a Nuxt or Vue related question, it's probably best to post in forums that are focused on those topics. 

I glanced at your code and I didn't notice anything about button click handlers. I don't think there's much we can do to help you here, sorry. I'm actually not even sure what you're asking specifically regarding GSAP. I wish I could be of more assistance, but we just don't have the resources to provide general consulting services. We're eager to help with any GSAP-specific questions that are made clear though. 

Good luck with your project!
