### ISSUE TITLE
Question -> Using pixi ticker to drive GSAP

### ISSUE THREAD

**Issue by wpitallo** [greensock/GSAP#413]
Hi, 

Not sure if this is a good place for questions but was wandering if its possible to use PIXI ticker to drive GSAP?

Thanks for the help.

Regards,

Warren

**Comment by OSUblake** [comment]
I think it's better the other way around.

```js
const app = new PIXI.Application({
  autoStart: false
});

gsap.ticker.add(() => {
  
  // if you need the delta
  const delta = gsap.ticker.deltaRatio();
  
  this.renderer.render(app.stage);
});
```

**Comment by wpitallo** [comment]
Thanks so much for the feedback :)

What if we wanted to do it the other way tho? So pixi driven ticker?

Why do you recommend doing the other way around?

**Comment by OSUblake** [comment]
You'd have to do something like this, passing in the time since it started.
https://greensock.com/docs/v3/GSAP/gsap.updateRoot()

**Comment by OSUblake** [comment]
> Why do you recommend doing the other way around?

So the render and animations are completely in sync. Using PIXI's ticker, it's not guaranteed that it is running in sync with GSAP's ticker. It could be a frame ahead or behind. Not always, but it could happen.

**Comment by OSUblake** [comment]
Thinking about it, I guess it doesn't matter if you manually update the root.

**Comment by wpitallo** [comment]
Thanks so much appreciate the help!
