### ISSUE TITLE
immediateRender on tweenFromTo with zero duration throws TypeError

### ISSUE THREAD

**Issue by chototoro** [greensock/GSAP#414]
Hi there,

When calling tweenFromTo() with a zero duration (i.e. fromPosition = toPosition), and with immediateRender property set to true, the following error is thrown:

`Uncaught TypeError: Cannot read property '_dur' of undefined`

Here is a minimal test case: https://codepen.io/chototoro/pen/JjXrQgv
Setting a slightly above zero duration (fromPosition = toPosition + 0.0001), or setting immediateRender to false removes the error.

A possible workaround is to ensure that fromPosition != toPosition, and set immediateRender to false if it's not, but it's not a solution if the tweenFromTo() result is added to a parent timeline.

**Comment by ZachSaucier** [comment]
Hey chototoro. I'm curious: Under what circumstances are you seeing this in your actual project? Most the time you should use a different control method like .pause() to set the time if the duration is 0.

**Comment by chototoro** [comment]
Hi Zach, i admit it's quite an edge case :)
I'm using .tweenFromTo() a bit as a trimming tool, in order to extract a portion (marked by two in/out labels) of a temporary timeline, and add this portion to the main timeline. On some rare cases, during app initialization, the in/out labels are both placed on the same position, and result in a .tweenFromTo() with a 0 duration.
Since these cases only occur in my app when the temporary timeline is empty, i can easily detect it and avoid the .tweenFromTo() call, because it wouldn't do anything anyway.
But if someone wanted to extract a 0 duration portion of a non-empty timeline (a bit like a screenshot?), one would encounter the TypeError and need a workaround: with .pause(atTime) as you suggest, or with fromPosition = toPosition + 0.0001, to keep the .tweenFromTo() logic).

**Comment by jackdoyle** [comment]
Thanks for pointing it out. I believe this is resolved in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better?

**Comment by chototoro** [comment]
I just tested the preview, and it is indeed resolved, great! Thank you very much Jack! :)
