### ISSUE TITLE
Since 3.5.1 - Cannot read property 'pause' of undefined

### ISSUE THREAD

**Issue by matt3224** [greensock/GSAP#415]
Since updating from 3.5.0 to 3.5.1 this error has appeared. I have downgraded to 3.5.0 for the time being
```
TypeError: Cannot read property 'pause' of undefined
    at _refreshAll (/Users/Matt/Sites/mosaic/frontend/node_modules/.pnpm/gsap@3.5.1/node_modules/gsap/ScrollTrigger.js:441:20)
    at Function.ScrollTrigger.refresh (/Users/Matt/Sites/mosaic/frontend/node_modules/.pnpm/gsap@3.5.1/node_modules/gsap/ScrollTrigger.js:1506:41)
```

**Comment by jackdoyle** [comment]
Hey @matt3224 - would you be able to provide a minimal demo that shows that problem? Nobody else has reported something like that, and I'm curious to see it in context. I'm not saying there isn't a bug - I'm just saying it's tough to troubleshoot blind so a minimal demo would be greatly appreciated.

**Comment by matt3224** [comment]
Hey @jackdoyle I couldn't think of a way to create a minimal demo. I'm using Svelte/Sapper and pulling content from a CMS, this causes a possible delay in the dom being ready and i find that i have to manually fire .refresh in onMount, similarly i need to run refresh in onDestroy too.

onDestroy is a method that runs in the server and the browser and when doing a cold load .refresh is running and failing presumably because it got no access to the dom. if i wrap it in a check then the errors disappears but my scrolltriggers no longer mount between pages.

That is the gist of my issue, it's a little contrived but when using sapper it appears to be the only way to get things to work. Whatever changed between 3.5.0 and 3.5.1 throws the above error.

I have made a reproduction in-case that helps (https://github.com/matt3224/sapper-gsap) but it's not a great replication as im not pulling in data and .refresh isnt needed because pages load too quickly

**Comment by jackdoyle** [comment]
Yeah, it's definitely not a good idea to call refresh() before the DOM is even available, but in the next release I added some conditional logic to at least avoid the error you ran into. You can preview it here (minified): https://assets.codepen.io/16327/ScrollTrigger.min.js

If you need the raw source for your bundler, here's a .tgz file you can NPM install: https://assets.codepen.io/16327/gsap-beta.tgz

Better?

**Comment by matt3224** [comment]
Great, thanks! I'll give it a test

**Comment by jackdoyle** [comment]
Should be resolved in the latest release.

**Comment by patrickdevelopes** [comment]
I'm still receiving the error.

**Comment by jackdoyle** [comment]
@patrickdevelopes it sounds like you must be calling ScrollTrigger.refresh() BEFORE the window/document/body exists. I would definitely recommend against doing that. 

I'll add some code to the next release to sense that condition and skip the refresh() call in that case.
