### ISSUE TITLE
GSAP Login

### ISSUE THREAD

**Issue by wpitallo** [greensock/GSAP#416]
Hi I just registered on the site and I get an email validation however when I click the link it takes me back to the validating page:

https://greensock.com/register/?do=validating

**Comment by ZachSaucier** [comment]
Hey wpitallo. Are you trying to validate the account WarrenPi? It's the only account I saw with your username (wpitallo) in the username or email address. 

If so, it's already validated. You should be able to use it.

**Comment by wpitallo** [comment]
The email I used is my company account. 

warren.pitallo@derivco.co.za

**Comment by ZachSaucier** [comment]
Maybe you were logged into the wrong account? I manually validated your account so it should be good to go now.

**Comment by wpitallo** [comment]
No 100% did not. Only thing I did do that you might want to check is that I clicked re-send verification mail as it was taking long and that took me to an error page. Then when I clicked the link in the email it took me back to https://greensock.com/register/?do=validating.

It is working now though, thank you!
