### ISSUE TITLE
3.5.1 Draggable - Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by mystrdat** [greensock/GSAP#418]
Hello,

I'm using latest Nuxt.js stack with GSAP 3.5.1 and the minified Draggable plugin loaded from the `/static` folder.
When I register the plugin, I get a `Cannot read property 'style' of undefined` error.

I have found the same error mentioned [here](https://gitmemory.com/issue/greensock/GSAP/376/614730925), but no additional information and no test case. In my usecase, I am already using other plugins (SplitText, DrawSVGPlugin) in the same way without issues.

I've build a minimal test case here: https://github.com/mystrdat/nuxt-gsap-draggable-error

`npm i`
`npm run dev`
The plugin is initiated here https://github.com/mystrdat/nuxt-gsap-draggable-error/blob/master/pages/index.vue

**Comment by ZachSaucier** [comment]
What /static directory are you talking about? I don't see one in the GitHub repo or in the .zip download from the GreenSock website. 

The [GSAP installation page](https://greensock.com/docs/v3/Installation) has a lot more details about how to get things imported and registered correctly including all of the following.

I recommend [configuring Nuxt to use ES modules](https://nuxtjs.org/api/configuration-build/#transpile) via:

```
build: {
  transpile: [
    "gsap"
  ]
}
```

Then using the modules version of GSAP (which you can install by adding the .tgz file from the /npm-install-this directory to your project then doing `npm install gsap-bonus.tgz` as covered in the [modules installation video](https://vimeo.com/391314787)). 

You should be able to import and register the plugins like this I believe:

```
import { gsap } from "gsap";
import { Draggable } from "gsap/Draggable";
import { DrawSVGPlugin } from "gsap/DrawSVGPlugin";
import { SplitText } from "gsap/SplitText";

if (process.client) {
  gsap.registerPlugin(Draggable, DrawSVGPlugin, SplitText);
}
```

**Comment by mystrdat** [comment]
@ZachSaucier 
https://github.com/mystrdat/nuxt-gsap-draggable-error/blob/master/static/Draggable.min.js

**Comment by jackdoyle** [comment]
Yeah, Draggable needs access to things in the window to work, but typically you can simply wait to gsap.registerPlugin(Draggable) until it exists (as Zach suggested). GSAP 3 was indeed rewritten in a way that'd solve issues that existed in v2 and earlier where it required the window immediately when loaded. 

@mystrdat were you saying that waiting for the window to exist before running gsap.registerPlugin(Draggable) and the rest of your code doesn't work for you?
