### ISSUE TITLE
InertiaPlugin file is missing from build npm package

### ISSUE THREAD

**Issue by IljaDaderko** [greensock/GSAP#425]
I was trying to use InertiaPlugin via

```ts
import { InertiaPlugin } from "gsap/InertiaPlugin"
```

but got errors related to resolving this. Upon digging further it seems that there is no related file for this in `node_modules/gsap`, I tried clean installing them several times, but I always end up with following files. I looked in `all.js` and it seems that `InertiaPlugin` is commented out under "Bonus Exports". Perhaps documentation should reflect how to import this plugin correctly?

<img width="758" alt="Screenshot 2020-11-06 at 13 20 38" src="https://user-images.githubusercontent.com/3154053/98360692-ef4a2700-2032-11eb-9a9b-ab5e870494dd.png">

**Comment by ZachSaucier** [comment]
Hey Ilja. The InertiaPlugin is a premium [Club GreenSock](https://greensock.com/club/) plugin (Shockingly Green or above). Are you a Club GreenSock member? If so you can install GSAP via the GreenSock private NPM registry or via the .tgz file downloaded from the GreenSock website as our [installation docs](https://greensock.com/docs/v3/Installation) and [video](https://vimeo.com/391314787) cover and the InertiaPlugin and other Club GreenSock plugins will be included.

**Comment by IljaDaderko** [comment]
Ah, missed that it was premium, no worries.
