### ISSUE TITLE
ScrollTrigger documentation vs video walkthrough - pinning

### ISSUE THREAD

**Issue by tommers-walker** [greensock/GSAP#427]
First off thanks for an amazing plugin, still wrapping my head around it but it's super powerful. One thing I spotted/don't understand is the section in the video walkthrough regarding pinning vs the documentation, which states:

"Warning don't animate the pinned element itself because that will throw off the measurements (ScrollTrigger is highly optimized for performance and pre-calculates as much as possible). Instead, you could nest things such that you're animating only elements INSIDE the pinned element."

Unless I've misunderstood, the video seems to be animating the pinned element?
![Screenshot 2020-12-16 at 12 54 38](https://user-images.githubusercontent.com/25368754/102351456-6366db80-3f9e-11eb-9f8f-206a90f67df4.png)

Likewise, the codepen example:
```
const anim = gsap.to(".c", {
  x: 400,
  rotation: 360,
  duration: 3
});

ScrollTrigger.create({
  trigger: ".c",
  animation: anim,
  // Uncomment these to see how they affect the ScrollTrigger
  markers: true,
  start: "top center",
  end: "top 100px",
  toggleClass: "active",
  pin: true,
  scrub: 1,
  onUpdate: self => {
    console.log("progress:", self.progress.toFixed(3), "direction:", self.direction, "velocity", self.getVelocity());
  }
});
```

**Comment by ZachSaucier** [comment]
Hey tommers-walker. The main situation where animating the pinned element could be an issue is if you're animating it in the direction of the scroll (usually the y axis).
