### ISSUE TITLE
Update installation page (gsap-bonus.tgz file)

### ISSUE THREAD

**Issue by lmuzquiz** [greensock/GSAP#428]
on the NPM / Build Tools section on the https://greensock.com/docs/v3/Installation it says: 

![Screen Shot 2020-12-22 at 17 38 57](https://user-images.githubusercontent.com/11865448/102943046-96b4d900-447c-11eb-9118-9cfbcfa3b788.png)

I don't think there is such gsap-bonus.tgz file anymore. 

Thanks

**Comment by ZachSaucier** [comment]
Hey Luis. The gsap-bonus.tgz file is within the npm-install-this directory of the downloads.

**Comment by lmuzquiz** [comment]
Yeah, i just realized i have to suscribe to get that gsap-bonus, Thanks!

**Comment by jackdoyle** [comment]
@lmuzquiz the gsap-bonus.tgz is for anyone with even a free GreenSock account - you don't have to be a paying Club GreenSock member. Even free users get CustomEase - that's in the gsap-bonus.tgz for that level.
