### ISSUE TITLE
A way to trigger ScrollTrigger events

### ISSUE THREAD

**Issue by minimit** [greensock/GSAP#429]
Hello would be nice to have a way to trigger events, for example I want a ScrollTrigger animation ONLY on initial rendering, only to the elements inside the viewport when ScrollTrigger gets initialized.

This could be possible if we had a way to trigger ScrollTrigger events, for example `ScrollTrigger.onEnter()`.

See for example this demo https://codepen.io/minimit/pen/ExgodeR

Could be possible to do the inverse, for example animate only elements outside the viewport if we use this code:
`if (self.progress !== 0) {`

**Comment by ZachSaucier** [comment]
Hey minimit. I'm a bit confused as to your end goal. Why are you using ScrollTrigger at all if you only want to fire some animation when the page loads?

**Comment by minimit** [comment]
Because it inherently could be an usage. Anyway I've found it's possible by manually setting the gsap animations.

This example if you need to fade in elements only if **inside viewport on page load**.

```
ScrollTrigger.batch(triggers, {
  once: true,
  onEnter: batch => {
    gsap.killTweensOf(batch)
    gsap.to(batch, { opacity: 1, duration: 0.5, ease: 'quart.out', stagger: 0.15 })
  },
  onRefresh: (batch, scrollTriggers) => {
    for (const self of scrollTriggers) {
      if (self.progress === 0) {
        gsap.set(self.trigger, { opacity: 1 })
      }
    }
  },
})
```

This example if you need to fade in elements only if **outside viewport on page load**.

```
ScrollTrigger.batch(triggers, {
  once: true,
  onEnter: batch => {
    gsap.killTweensOf(batch)
    gsap.to(batch, { opacity: 1, duration: 0.5, ease: 'quart.out', stagger: 0.15 })
  },
  onRefresh: (batch, scrollTriggers) => {
    for (const self of scrollTriggers) {
      if (self.progress !== 0) {
        gsap.set(self.trigger, { opacity: 1 })
      }
    }
  },
```
