### ISSUE TITLE
PixiPlugin TypeScript interface Vars x and y type not string

### ISSUE THREAD

**Issue by panhezeng** [greensock/GSAP#430]
now 

`  x?: number;
    y?: number;
`
should
`  x?: number | string;
    y?: number | string;
`

`
 pixi: {
            // eslint-disable-next-line @typescript-eslint/ban-ts-comment
            // @ts-ignore
            y: "+=200",
          },
`

**Comment by jackdoyle** [comment]
Thanks for letting us know - we'll get that into the next release.

**Comment by panhezeng** [comment]
Thanks, not just x and y, all number Vars should be add string type ?

**Comment by jackdoyle** [comment]
Should be resolved in the latest release.
