### ISSUE TITLE
React: Component is displayed for one milisecond in the initial state

### ISSUE THREAD

**Issue by FNPCMDs** [greensock/GSAP#432]
Hi! I'm having a issue with GSAP in NextJS (React). As you can see in the following video, the component is displayed before (I think) useEffect() is called. It is happening with gsap.from, gsap.fromTo, gsap.set, etc. Also there is no difference with the prod and dev build of react.

![2021-02-05 02-36-32-1](https://user-images.githubusercontent.com/25681464/106995941-b79c6980-675e-11eb-9ee9-45700eb47792.gif)

CodeSandbox: https://codesandbox.io/s/adoring-smoke-75mrn?file=/src/App.js

**Comment by ZachSaucier** [comment]
Hey FNPCMDs. This is called a flash of unstyled content and we have a post about it here: http://greensock.com/fouc/

Given I don't use React much I don't know the most React way of preventing it, but the concept shown in the video of the linked page is the same no matter what tooling you use.

**Comment by FNPCMDs** [comment]
> Hey FNPCMDs. This is called a flash of unstyled content and we have a post about it here: http://greensock.com/fouc/
> 
> Given I don't use React much I don't know the most React way of preventing it, but the concept shown in the video of the linked page is the same no matter what tooling you use.

Ohhh thanks u!! I didn't found that in Google. I'm going to close the issue.

Greetings!
