### ISSUE TITLE
Question about a util to parse the TweenVars (CSSVars)

### ISSUE THREAD

**Issue by neo** [greensock/GSAP#433]
Hi!

I've been thinking to create a util that converts the `TweenVars` into a React style object (think applying the same fromVars to  the style attribute). So I'm looking to see if there's any existing helper/util that I could utilize or at least some similar code that I could refer to.

Thank you and cheers!

**Comment by ZachSaucier** [comment]
Hey neo. Can you please provide a situation where that'd be helpful? Also if you could provide an example conversion (of a TweenVars becoming the React style object) that'd be helpful. 

We at GreenSock are hoping to understand more about why React developers do or do not use GSAP and how we might be able to better accommodate using GSAP in a more React-y way so this question is of particular interest to us at this point in time. So any other feedback you have relating to GSAP in React is also welcome 🙂 

Not sure if this is helpful: There's a library called [react-gsap](https://bitworking.github.io/react-gsap/) that uses GSAP in a more React-y way. Is this at all helpful to what you're trying to accomplish? We are trying to estimate how much an approach like it solves the "issues" that React developers see when using GSAP.

**Comment by neo** [comment]
Hi Zack! Thank you for the timely reply!

For this specific idea, it's an attempt of me trying to make SSR/SSG react sites with intro animations working. After generating the HTML and before react kicks in for hydration, we'd need to hide the content by either CSS or inline styles that come with the HTML. So I'm thinking it might work if I inline the same styles that `from` is using.

In general, I do want to make the animations more declarative although I know it's not a very easy task. Unfortunately I don't think react-gsap would help much because, to me personally, I think it's just a jsx wrapper of the same gsap. The closest thing to what I've been thinking/exploring is [Framer Motion](https://www.framer.com/api/motion) (formerly known as popmotion).

In my opinion, the "issues" (at least one of the main ones) with React + GSAP is the imperative control of animations is not straightforward to be integrated with the declarative ways of doing React. And having built a number of sites making into the GSAP showcase, I do have a lot to say about React + GSAP 😂  so I'd be more than happy to chat with you or Jack further about anything in general.

Cheers!!

**Comment by ZachSaucier** [comment]
> After generating the HTML and before react kicks in for hydration, we'd need to hide the content by either CSS or inline styles that come with the HTML.

Excuse my ignorance here, but if there's enough time for GSAP to run to generate the proper starting inline styles couldn't it just apply those styles to your elements as well? Instead of passing them to your code to inline them. 

Perhaps it'd help us understand the situation if you made a minimal demo on CodeSandbox or something.

> Unfortunately I don't think react-gsap would help much because, to me personally, I think it's just a jsx wrapper of the same gsap.

Indeed it is. What would a more declarative version of GSAP be like besides just a JSX wrapper? How would the current GSAP need to change?

> having built a number of sites making into the GSAP showcase, I do have a lot to say about React + GSAP 😂

That's great! Jam3 makes some pretty fantastic sites 🙂 

>  I'd be more than happy to chat with you or Jack further about anything in general.

Thanks, we'll definitely take you up on that.

**Comment by neo** [comment]
> Excuse my ignorance here, but if there's enough time for GSAP to run to generate the proper starting inline styles couldn't it just apply those styles to your elements as well? Instead of passing them to your code to inline them.

It's actually a relatively annoying and sometimes confusing problem with SSR/SSG sites, because the DOM isn't available during the server generating phase. All the DOM related logic (and manipulation) would have to happen in a browser environment.

And I just realize today that the framer motion library actually handles the server side rendering situation – it might be worth looking into how they achieve that.

Lastly, the idea I mentioned wouldn't be the perfect solution either, because it would show a blank page (if the start of the animations is for things to be hidden) for users with their JS turned off. The only perfect solution we had found was with CSS.

> What would a more declarative version of GSAP be like besides just a JSX wrapper? How would the current GSAP need to change?

I actually have been exploring this myself and haven't reached an answer... (yet!) But I had the chance to briefly use Angular's first party animation module which is built on top of the Web Animation API (I think), and I really enjoy how you could define a couple states and optionally the transitions between those states and then just toggle the state. I think this is the closest to my definition of being declarative. And I had realized the idea is very similar to what [f1](https://github.com/jam3/f1) was trying to achieve (cc @mikkoh 😆 )

> That's great! Jam3 makes some pretty fantastic sites 🙂

Thank you!! And they are only possible with the help of GSAP!

**Comment by ZachSaucier** [comment]
> the framer motion library actually handles the server side rendering situation

That sounds like quite a task!

> it would show a blank page (if the start of the animations is for things to be hidden) for users with their JS turned off. The only perfect solution we had found was with CSS.

Can't hiding things with CSS cause some things to not be indexed properly?

I would think that using `<noscript>` to make sure elements are visible would be the way to go: [Demo](https://jsfiddle.net/Zeaklous/8n4h1z7x/1/).

> I really enjoy how you could define a couple states and optionally the transitions between those states and then just toggle the state. I think this is the closest to my definition of being declarative.

That reminds me of GSAP's recent [Flip Plugin](https://greensock.com/docs/v3/Plugins/Flip/). Have you seen it yet? Is this the sort of thing you're wanting, but for it to handle React state changes for you?

**Comment by mikkoh** [comment]
I've been a bit out of the loop when it comes to animations the past few years. But if there's anything I can contribute it might be my ideology with `f1` + `react-f1`. There are very few animation libraries/technologies that are state deterministic for JS/web animation. Almost all UI is deterministic and so using a non-deterministic library for UI animations produces more bugs than needed. 

In hindsight I would have maybe used CSS Animations to create animations and then simply had library that drives chooses/those animations. At that time there was too big of a debate between JS animations and CSS animations. I wonder if that has changed with the rise of React Native.

One advantage of having deterministic states is that you can build tooling much more easily to create this kind of UI. For instance you could create designs in Figma/Sketch. Determine states from the Figma/Sketch design and apply animations after. At Jam3 we were using After Effects for this. The start of a Composition was the start state and end of the animation was the end state. With `f1` you wrote how these animations tied together.

**Comment by ZachSaucier** [comment]
Thanks a lot for the input!

> There are very few animation libraries/technologies that are state deterministic for JS/web animation.

My guess about why few animation libraries/technologies that are state deterministic exist is because 

1. It's difficult to do — you not only have to have a full animation engine but _also_ the ability to get what the start and final state is correctly and 
2. That is a subset of what animation libraries (like GSAP) can do. So as animation library maintainers it is hard for us to see the desire to limit people in such a way (because something like can GSAP can do those deterministic transitions _and more_). 

But if that's the biggest use case perhaps there's a use case for something like the Flip Plugin that works more seamlessly and automatically with state transitions like those found using frameworks like React. 

Did you check out the Flip Plugin? I really think it's very close to what you seem to be requesting, but I'd love to hear if and where it's not the sort of thing that you're looking for. 

Side note: A question [came up today](https://greensock.com/forums/topic/27137-flip-with-react/) about using the Flip Plugin with React state transitions that might be of interest to you. I'm working on a demo that shows it working now, though it might be some time before I get it working because of my lack of experience in React.

**Comment by neo** [comment]
Hi Mikko! 😆  Thank you for your input!! And we miss you!

Zack, I meant to mention the Flip Plugin in my first reply but kept forgetting 😅  I just learned about it the other day and thought it should open up a LOT of possibilities, will def try it out and report back!

And I totally agree that a more declarative way of using a subset of GSAP is not really within the scope of GSAP, that's why I have been exploring ways to do it; and hopefully in the future, I could do a deterministic and declarative wrapper of GSAP that's for React.

Thank you both!!

**Comment by ZachSaucier** [comment]
> I totally agree that a more declarative way of using a subset of GSAP is not really within the scope of GSAP, that's why I have been exploring ways to do it; and hopefully in the future, I could do a deterministic and declarative wrapper of GSAP that's for React.

As I said before, if the lack of a more direct way to do this sort of thing in React is a big reason why more React developers don't use GSAP, maybe it _is_ in scope 🙂 Maybe it just requires a few clear demos of how to set it up. Or maybe it requires a React-focused wrapper of GSAP and the Flip Plugin. We'll continue investigating this topic and keep you posted on what we find. We'd love it if you did the same with us!

**Comment by ZachSaucier** [comment]
FYI the [thread I mentioned earlier](https://greensock.com/forums/topic/27137-flip-with-react/?tab=comments#comment-132750) got an answer from one of the GreenSock mods who uses React more. Hopefully it shows how simple it is to do that sort of thing with the Flip Plugin.

To confirm: What you're wanting is for that to happen but in a more declarative way?
