### ISSUE TITLE
Use wheel instead of mousewheel

### ISSUE THREAD

**Issue by karlcow** [greensock/GSAP#434]
[mousewheel is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event). This creates breakage in Firefox. 

`wheel` events are supported everywhere.

**Comment by jackdoyle** [comment]
No problem - I can make that change in the next release. Thanks for pointing it out.

**Comment by karlcow** [comment]
@jackdoyle note that I created a pull request for it. 
Tell me if there is something missing for you, I can adjust 
https://github.com/greensock/GSAP/pull/435

**Comment by jackdoyle** [comment]
Thanks! We don't accept pull requests, but I've already got the changes made in the upcoming release, so we should be all set.

**Comment by jackdoyle** [comment]
Should be resolved in the latest release.
