### ISSUE TITLE
@link to your webdoc [request]

### ISSUE THREAD

**Issue by djmisterjon** [greensock/GSAP#439]
you have beautiful docs for dev! congras :)
I love when a project is hard documented. 😁

Next step can be to add relative @link to your webdoc for all methods?
https://greensock.com/docs/v3
example:
![image](https://user-images.githubusercontent.com/24865815/111357821-098ab600-8660-11eb-9288-ca5c4ee1a721.png)
![image](https://user-images.githubusercontent.com/24865815/111357937-2921de80-8660-11eb-8298-540b8ecc09d2.png)

not using much gsap, so for me it is necessary to manually consult the docs on your website for mostly all methods, and I find its unproductive to do this all time by searching.
Maybe a little link added for one click ? 
It juste a geeks' suggest for improves docs but probably of no real interest to most veterans.

**Comment by ZachSaucier** [comment]
Hey djmisterjon, thanks for the kind words and suggestion.

From what I can tell, there isn't a real standard for this? I was looking at [this thread](https://github.com/Microsoft/TypeScript/issues/35524) and some other pages around the internet.

With that being said, a quick test gives a hyperlink when I add something like `@link https://greensock.com/docs/v3/Plugins/Draggable/static.create()` to the JSDoc comments for a given method in VS Code. It does _not_ have proper formatting if I include curly braces around the line like is suggested in some places. 

So I'm betting this is the way we should go forward for now. Do you have any experience doing this? @OSUblake can you confirm?

**Comment by OSUblake** [comment]
I don't know if I've ever use `link` before, but it should be fine without the curly brace. It will just show as plain text if it doesn't understand a command, and VS code automatically converts urls to hyperlinks. It might be worth seeing how it looks in other editors.

**Comment by djmisterjon** [comment]
yes link is not supported yet or maybe never by `ts server` (for vscode , dont know others IDE) 
https://github.com/Microsoft/TypeScript/issues/35524
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html

I use the word  `@link` for example purpose.
I find that more aesthetic and respect jsdoc syntax logic for documentations, but these a very personal choice !
Both are fine for me :)
 Vscode is my only editor , sry i cant give more info about others.
