### ISSUE TITLE
Application occasionally crashes when using scroll trigger and navigating between pages in NextJS

### ISSUE THREAD

**Issue by Lyndon-Sobolik** [greensock/GSAP#440]
There is race condition in the ScrollTrigger package that cause CPU to go to 100% and the application to become unresponsive. Not sure if this is happening in other application as well, but it is reproducible on my NextJS application.

To reproduce:
1. Scroll in an upwards direction on a page that has a scroll trigger set
2. While scrolling, click on on a link the will navigate you away from the page
3. Repeat (there is a timing component, so it only happen about 10% of the time)

GSAP version: 3.6.0

The issue can be fixed by adding a safety check to line `281` in `ScrollTrigger.js` so that it changes from:
```
while (_i--) {
    _triggers[_i] && _triggers[_i].update(0, recordVelocity);
}
```

to be:
```
while (_i-- > 0) {
    _triggers[_i] && _triggers[_i].update(0, recordVelocity);
}
```

**Comment by jackdoyle** [comment]
I see what you mean, @Lyndon-Sobolik and that should be fixed in the next release which you can preview at https://assets.codepen.io/16327/ScrollTrigger.min.js

Thanks for the suggested solution as well. Sorry about any hassle there.

**Comment by Lyndon-Sobolik** [comment]
@jackdoyle Thanks for the super quick reply. Looking forward to the next release!

**Comment by jackdoyle** [comment]
Should be resolved in the latest release.
