### ISSUE TITLE
timeline.fromTo does not return a tween

### ISSUE THREAD

**Issue by qualitymanifest** [greensock/GSAP#442]
Looking [here](https://github.com/greensock/GSAP/blob/40bd026e9500e15a9b73c0f5aa02044c2235e8d4/types/timeline.d.ts#L173), the jsdoc indicates that `timeline.fromTo` returns a tween, but typescript indicates that it returns `this` which would be the timeline itself. It appears that the typescript type is correct, and the timeline is returned.

I am still able to get a handle on the timeline's tween via `timeline.getById(tweenId)`, is this the correct way to achieve that?

Thanks

**Comment by jackdoyle** [comment]
You're absolutely right - the definitions file will be fixed in the next release. Those methods return the timeline, not a tween. 

If your goal is to get the last animation that was added to the timeline, you can use the [.recent()](https://greensock.com/docs/v3/GSAP/Timeline/recent()) method.
