### ISSUE TITLE
[3.6.1][Draggable]: Dragend triggers click method

### ISSUE THREAD

**Issue by ubalensi-yoobic** [greensock/GSAP#443]
Hey guys ! I have recently been upgrading GSAP to 3.6.1, this is working nicely, thanks !
However, I have noticed that for the Draggable, when the `dragend` / `release`event get fired, it will trigger the `click`event right after.

So, as a "quick fix" in the meantime, I just made sure the click get fired only if the last event is !== 'dragend'.

Could that issue be related to some changes made for the 3.6.1 ?

Thanks

**Comment by jackdoyle** [comment]
Hm, I can't seem to reproduce this, @ubalensi-yoobic - can you please provide a [minimal demo](https://greensock.com/demo)?
