### ISSUE TITLE
Cannot Import ScrollTrigger in Next 10.1.3

### ISSUE THREAD

**Issue by nickwild-999** [greensock/GSAP#446]
When I `import { ScrollTrigger } from "gsap/ScrollTrigger"` in a plain vanilla Next 10.1.3 app I get the following error...
```
.../gsap-next2/node_modules/gsap/ScrollTrigger.js:748
export var ScrollTrigger = /*#__PURE__*/function () {
^^^^^^
SyntaxError: Unexpected token 'export'
```

**Comment by jackdoyle** [comment]
That typically means you're using an ES Module in an environment that doesn't understand ES Modules. It's something in your environment, unrelated to GSAP. 

If your build system can't understand modules, you could just import the UMD files by adding /dist/ to the path, like: 
```javascript
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
```

Happy tweening!

**Comment by nickwild-999** [comment]
Thanks so much for your quick answer @jackdoyle that was it!
