### ISSUE TITLE
onComplete callback not being called on empty paused timelines

### ISSUE THREAD

**Issue by tchapi** [greensock/GSAP#448]
Hi
I'm not sure if this expected behavior or not, but when creating a paused timeline with nothing in it, the `onComplete` callback is not fired on 3.6.1

```javascript
const timeline = gsap.timeline({
   paused: true,
   onComplete () {
      console.log("timeline completed")
   }
})
timeline.play()
```
the log is not created, but in the previous version I was using (3.5.1), it was, so I'm not sure if I need to change something or if it's a bug

Thanks a lot for this wonderful lib !

**Comment by jackdoyle** [comment]
Yeah, that's a bit of a tricky scenario because on one hand, the playhead hasn't moved at all thus it seems like it shouldn't "complete" but on the other hand, it is a zero-duration timeline (which is pretty weird actually) so you could make an argument that onComplete should fire. I've updated the next release to do that - you can preview it here: https://assets.codepen.io/16327/gsap-latest-beta.min.js (minified)

Better?

**Comment by tchapi** [comment]
Hi @jackdoyle  and thanks a lot for your answer !

I agree that it's tricky. My main point was that the behaviour changed for 3.6.1 which was a bit unexpected.

My use-case (_just so you can image a real world scenario_) is that I'm creating a timeline at some point, with an `onComplete` callback that I want to fire, and then, according to different parameters, I add sub-timelines to it. There are some cases where I don't need to add anything at all, so the timeline ends up _empty_, but I still want the callback to be fired. In my mind, the `onComplete` is a bit like a `finally` in a `try / catch` control flow: always firing at the end, whatever happens.

I had modified my script to use a `call()` call, which seems to work fine :

```javascript
const timeline = gsap.timeline({ paused: true })

// Lot of stuff involving if (this) { timeline.add(that) }

timeline.call(() => {
    console.log("timeline completed")
})

timeline.play()
```

What would be the recommended way in this scenario you think ?

**Comment by jackdoyle** [comment]
> What would be the recommended way in this scenario you think ?

Either way should be fine, at least in future releases. Sorry about any confusion there.
