### ISSUE TITLE
CustomEase not found in v3.6.1

### ISSUE THREAD

**Issue by mtskf** [greensock/GSAP#449]
Hi there,
I've just found CustomEase is not included in the latest version.
Was it deplicated?

**Comment by jackdoyle** [comment]
CustomEase has never been in the public downloads/repositories - it's a perk of signing up for a GreenSock account (even the free level) at greensock.com. Once you have an account, you can download it in the zip file from your account dashboard. 

CustomEase is super useful and it has not been deprecated at all. Still going strong. 

Happy tweening!
