### ISSUE TITLE
Issue with ScrollTrigger markers when using .scrollerProxy() and ASScroll smooth scroll library

### ISSUE THREAD

**Issue by StevenStavrakis** [greensock/GSAP#452]
When using the [ASScroll Library](https://github.com/ashthornton/asscroll) for smooth scrolling, problems are experienced if scrollTrigger markers are set to true. When scrolling, if the smooth scroll completes, the page will jump several hundred pixels in the direction of the scroll. According to the creator of the library, this might have something to do with `markers: true` setting the scroll container to have `position: relative`, however, manually overriding this with `position: fixed !important` doesn't seem to fully resolve the issue as explained [here](https://github.com/ashthornton/asscroll/issues/52#issuecomment-833843349).

**Comment by jackdoyle** [comment]
@StevenStavrakis  got a minimal demo we can look at? We don't really support 3rd party libraries, but I don't mind looking at a minimal demo to see if there's an easy fix. 

By the way, why not just turn markers off? You wouldn't leave them on when you launch anyway - they're just meant to be a convenience during development.

**Comment by StevenStavrakis** [comment]
@jackdoyle 

[This is the demo provided in the ASScroll repo for working with ScrollTrigger](https://codepen.io/ashthornton/pen/PoZRwPW)

If you set `markers: true` on `line 17` and try scrolling, you'll see the issue.

Once the scroll trigger behavior is sorted, turning the markers off is perfectly viable, however, not being able to use them complicates development somewhat.

**Comment by jackdoyle** [comment]
How about this?:
https://codepen.io/GreenSock/pen/rNyOXBY?editors=0010

It uses a preview of the upcoming release. I'm experimenting with adding a fixedMarkers: true option on the .scrollerProxy(). And it also allows the scroller to remain position: fixed (instead of making it relative). 

Lastly notice that I had to add the markers as the newScrollElements in the enable() call so that ASScroll moves those appropriately.

**Comment by StevenStavrakis** [comment]
At first, it looked a bit odd, but I must have changed some values because after going over it again and reloading it looks like it's working perfectly. Good to hear it will be coming with the next release of gsap, thanks!

**Comment by jackdoyle** [comment]
You may have had a cached version of the file loaded(?)

Glad to hear it looks okay now.

**Comment by ashthornton** [comment]
This is excellent, thanks for adding support for the crazy world of smooth scroll yet again @jackdoyle ! Look forward to the next release.
