### ISSUE TITLE
Draggable Doesn’t Work On Mobile

### ISSUE THREAD

**Issue by jkantner** [greensock/GSAP#454]
I created [this demo](https://codepen.io/jkantner/pen/vYxgdbM) using a rotation-type Draggable, and it won’t work on iPhone or iPad. I even made sure the “draggable” element (`.temp__dial`) had the highest `z-index` since it was absolutely positioned. I’m using GSAP 3.

**Comment by jackdoyle** [comment]
It looks like you had errors in your JavaScript. Check the console. I think you meant to refer to this.fW and this.fH instead of just fW and fH.

**Comment by jkantner** [comment]
Okay, got it. I ended up removing that block of code anyway since it was redundant.
