### ISSUE TITLE
The problem I have when using GSAP with NextJS + Typescript.

### ISSUE THREAD

**Issue by bbg** [greensock/GSAP#456]
Hi everyone,

I want to use GSAP in my project with NextJS + Typescript. However, I am getting the error you will see in the screenshot.

My code to import the library;

```js
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
```

or

```js
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
```

Error;
<img width="1046" alt="Screen Shot 2021-05-25 at 19 25 56" src="https://user-images.githubusercontent.com/13348876/119540701-67412a00-bd96-11eb-9507-89af700dd927.png">

Version information;
- "gsap": "^3.2.6"
- "next": "^10.2.0"
- "typescript": "^4.2.4"

I tried all the methods mentioned in the forums but could not fix this error

**When I try with NextJS without Typescript, I get the same error.**

Thanks

**Comment by jackdoyle** [comment]
Already answered in the forums: 
https://greensock.com/forums/topic/28321-the-problem-i-have-when-using-gsap-with-nextjs-typescript/?tab=comments#comment-140077
