### ISSUE TITLE
ScrollToPlugin: window.default

### ISSUE THREAD

**Issue by miksh7** [greensock/GSAP#458]
Is there any reason to set this plugin as window.default?

```
	exports.ScrollToPlugin = ScrollToPlugin;
	exports.default = ScrollToPlugin;
```
We have another 3rd-party library which inits itself as below

```
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('global/window'), require('global/document')) :
  typeof define === 'function' && define.amd ? define(['global/window', 'global/document'], factory) :
  (global = global || self, global.videojs = factory(global.window, global.document));
}(this, function (window$1, document) {
  window$1 = window$1 && window$1.hasOwnProperty('default') ? window$1['default'] : window$1;
  document = document && document.hasOwnProperty('default') ? document['default'] : document;
...
```

so window$1 becomes equal to ScrollToPlugin causing the entire lib failure.

**Comment by jackdoyle** [comment]
exports.default needs to be set that way so that this works: 
```javascript
import ScrollToPlugin from "gsap/ScrollToPlugin";
```
Nobody else has run into anything similar or at least nobody has reported it to us in the several years that GSAP 3 has been out and GSAP is used on millions of sites, so I wonder if this is more of a setup issue on your end? If you've got a minimal demo that shows the issue in your particular scenario, we'd be happy to take a peek.

**Comment by OSUblake** [comment]
Wasn't this addressed here?
https://github.com/videojs/video.js/issues/6386

**Comment by miksh7** [comment]
yes, this is that videojs issue but i don't see if it was fixed.
At the moment, our vendor uses Video.js 7.6.6, this lib is loaded dynamically on the page so we can't make it run after your plugin.

**Comment by jackdoyle** [comment]
What version of GSAP are you using? Obviously I'd recommend the latest :)

**Comment by miksh7** [comment]
yes, i use latest. As a workaround i had to comment out
exports.default = ScrollToPlugin;

I'll look for solution.
