### ISSUE TITLE
Zoom Teleport/Warp Effect

### ISSUE THREAD

**Issue by fleeasura123** [greensock/GSAP#459]
Good day! I am very fascinated by this effect. 

![zoom teleport warp](https://user-images.githubusercontent.com/53055963/121693415-b065dd80-cafb-11eb-805e-44e4e2051d64.gif)

Any tips how can we implement it on TweenLite or other animation technologies?
Or demos I can see.. Or what should I learn to implement such effect?

Any help is appreciated.

**Comment by jackdoyle** [comment]
This is definitely something that's better to post in the forums: 
https://greensock.com/forums 

You can certainly use GSAP to animate that, and to get the warping effect you'd use something like PixiJS or WebGL or ThreeJS maybe. 

Good luck!

**Comment by jackdoyle** [comment]
I just saw this tweet and it looked like maybe exactly what you need: 
https://twitter.com/PixiJS/status/1403437660639698948

**Comment by fleeasura123** [comment]
@jackdoyle Thank very much for the help!
