### ISSUE TITLE
ScrollTrigger plugin throws warning "Consider marking event handler as 'passive' to make the page more responsive."

### ISSUE THREAD

**Issue by irfancankalelikargo** [greensock/GSAP#460]
I am using gsap with ScrollTrigger plugin with React application. Since scroll trigger event listeners does not use `passive: true` on event subscription, Chrome version Version 91.0.4472.101 throws following warning on Verbose mode enabled.
`
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive`

Here is usage: 

```
	  scroller.addEventListener("wheel", function () {
	    return getTween.tween && getTween.tween.kill() && (getTween.tween = 0);
	  });
```

Here is the suggested usage that resolves warning: 

```
	  scroller.addEventListener("wheel", function () {
	    return getTween.tween && getTween.tween.kill() && (getTween.tween = 0);
	  }, { passive: true });
```

**Comment by jackdoyle** [comment]
Sure, we can do that in the next release. Thanks for the suggestion. And just to be clear, that's not an "error" - it's just a warning :)

**Comment by irfancankalelikargo** [comment]
@jackdoyle Thanx for heads up and next release update! I have updated issue accordingly.

**Comment by MaxVeilleuxMTL** [comment]
@jackdoyle I am still getting this issue using the `gsap-bonus.tgz` file in my npm installation.

Could you please push that fix in the full gsap bundle?

Here's a couple of screenshot that can help locate the missing `{ passive: true }` param :)

<img width="438" alt="lighthouse-warning" src="https://user-images.githubusercontent.com/49200337/148838628-270f5b14-8a6e-4d14-8839-89e3d30ac833.png">
<img width="402" alt="scrolltrigger-not-passive" src="https://user-images.githubusercontent.com/49200337/148838645-c5ba6b1a-8175-4034-bc59-055b1e7fe439.png">
<img width="393" alt="gsap-package-3-9-1" src="https://user-images.githubusercontent.com/49200337/148838670-26e41a15-0384-4269-b1fb-5df5d265156e.png">
<img width="344" alt="gsap-bonus-tgz" src="https://user-images.githubusercontent.com/49200337/148838683-d340a1c8-55c7-4440-b59e-91659f3cb76e.png">

Thanks a lot, cheers!

**Comment by jackdoyle** [comment]
Yep, that has been in the gsap-bonus.tgz for a while. I wonder if you've got a cached version? Are you positive it says version 3.9.1 at the top of the ScrollTrigger file?

**Comment by MaxVeilleuxMTL** [comment]
@jackdoyle Damn you're right, I was stuck at 3.6.0 XD sorry about that.

Thanks for that quick answer :) cheers!
