### ISSUE TITLE
Demo CodePen Home Pair with CSS Scroll Snapping  broken

### ISSUE THREAD

**Issue by BaranovRoman** [greensock/GSAP#462]
Sections jump through one on scroll
https://codepen.io/GreenSock/pen/YzyaKrq

**Comment by jackdoyle** [comment]
I don't see any problems. Can you please provide more details? What do you think is broken exactly?

**Comment by BaranovRoman** [comment]
> I don't see any problems. Can you please provide more details? What do you think is broken exactly?

Hm.. I check this on several devices, when I scroll once page jump from first to third section, macOs actual chrome and mouse X7

**Comment by jackdoyle** [comment]
It is supposed to snap to sections, yes. I checked on several browsers and I don't see anything misbehaving at all. Can anyone else confirm that it isn't working for them? And for the record the whole CSS snapping in that demo has absolutely nothing to do with GSAP or ScrollTrigger - it's purely leveraging CSS in the browser (native browser technology). So if you're seeing a problem, it's likely a bug in your browser or something like that.

**Comment by BaranovRoman** [comment]
> It is supposed to snap to sections, yes. I checked on several browsers and I don't see anything misbehaving at all. Can anyone else confirm that it isn't working for them? And for the record the whole CSS snapping in that demo has absolutely nothing to do with GSAP or ScrollTrigger - it's purely leveraging CSS in the browser (native browser technology). So if you're seeing a problem, it's likely a bug in your browser or something like that.

Yeah, I see that works on css, check it on more devices
macos with touchpad or magic mouse - all fine on safari and chrome
also all fine on windows chrome with mouse
But on macos with "mechanical" mouse sections jumps, I think it's more features of work macos with not magic mouse/touchpads, but i'm almost sure earlier it's works fine

**Comment by jackdoyle** [comment]
I'm not sure what to say. Again, none of this has anything to do with GSAP/ScrollTrigger as far as I can tell. The snapping is pure CSS. Let us know if you think there's something else we need to do.

**Comment by OSUblake** [comment]
I saw the same problem. Definitely not a ScrollTrigger issue as the problem is still there if you remove ScrollTrigger. I updated the CSS in the demo and changed the scroller element. Does it work better now?
https://codepen.io/GreenSock/pen/YzyaKrq
