### ISSUE TITLE
where is InertiaPlugin ?!!!

### ISSUE THREAD

**Issue by daeehamid** [greensock/GSAP#464]
hi 
how can i use InertiaPlugin in vue/gsap ?!
According to the document I have to import plugin like this : 
`` import {InertiaPlugin} from "gsap/dist/InertiaPlugin"; ``
But There is no plugin called InertiaPlugin in the dist directory!!!

"gsap": "^3.7.1",
"nuxt": "^2.15.7"

**Comment by phucbm** [comment]
The InertiaPlugin is a part of Club GreenSock, you can get the plugin file from the account dashboard if you're already a member.

**Comment by jackdoyle** [comment]
Yes, @phucbm is exactly right. 

https://greensock.com/club

You can use any of the bonus plugins for FREE as much as you want on codepen using these files (which are locked to that domain): https://codepen.io/GreenSock/full/OPqpRJ/

Happy tweening!
