### ISSUE TITLE
ScrollTrigger pinned element position issues with content visibility 

### ISSUE THREAD

**Issue by gravyraveydavey** [greensock/GSAP#465]
Hey GSAP Team, 

I was experiencing an issue with ScrollTrigger, where the pinned sections wrapping my animations were jumping and scrolling beyond their intended boundaries, but only on certain pages.

It was behaving just like the note under the 'pinReparent' property description in the docs - however adding that property didn't solve the problem. 

It turns out the issue was with the CSS property of `content-visibility: auto;` set on an earlier sibling to the pinned animation node in the dom. Removing this property fixed the behaviour, and pinning lined up exactly where it should once again. 

On reflection it makes sense that it would screw up the positioning calculations as it changes how (chromium based) browsers handle their layout / paint / size / style rendering for elements _out of viewport_. 

So maybe not a strict issue - but certainly a 'gotcha' to watch out for! One i would say is worth adding to the docs or the 'common ScrollTrigger mistakes' page. 

Hopefully this saves someone else some debugging hours who like myself doesn't fully understand how content-visibility property works under the hood but was hoping to leverage it for some performance wins!

**Comment by jackdoyle** [comment]
Thanks for the suggestion, @gravyraveydavey - I've added a note to the docs in the FAQ section accordingly.
