### ISSUE TITLE
Question: Advanced documentation?

### ISSUE THREAD

**Issue by dimitriadamou** [greensock/GSAP#469]
Hey there, I am new to GSAP and have only shallowly used it for several days, is there documentation focused on the internals ? Or is this repository the result of transpiled/compiled code,  I understand if that is for commercial purposes.

**Comment by jackdoyle** [comment]
Welcome, @dimitriadamou ! 

The raw source code is included in the repository - in the /src/ directory. Like https://github.com/greensock/GSAP/blob/master/src/gsap-core.js

If you have any specific questions, feel free to post in our forums at https://greensock.com/forums

Enjoy!

**Comment by dimitriadamou** [comment]
Hi @jackdoyle 

Thanks, I was wondering if that was the actual source code or a transpiled version - I have already been crawling through that, I will continue to do so.
