### ISSUE TITLE
pixi.js 6.0 PIXIPLUGIN

### ISSUE THREAD

**Issue by mozkoq** [greensock/GSAP#470]
Didn't find a way to work with the new version.

Because there is no global object in it.
PIXI, 

Maybe we have new way to use PixiPlugin with pixi.js@6.0?

**Comment by OSUblake** [comment]
See if this helps. You can make the global yourself, or pass in what the plugin is looking for.
https://greensock.com/forums/topic/21287-pixiplugin-doesnt-seem-ready-for-pixi-v5/?tab=comments#comment-99986

**Comment by mozkoq** [comment]
Ty, works for me.

Solution:
```
        PixiPlugin.registerPIXI({
            DisplayObject: DisplayObject,
            Graphics: Graphics,
            filters: {
                MotionBlurFilter: MotionBlurFilter,
                ColorMatrixFilter: ColorMatrixFilter,
                BlurFilter: BlurFilter,
            },
            VERSION: "6.1.2",
        });
```

**Comment by OSUblake** [comment]
We've added this to documentation. 
https://greensock.com/docs/v3/Plugins/PixiPlugin/static.registerPIXI()
