### ISSUE TITLE
[enhancement] Scrolltrigger pinned position with bottom instead of top (sometimes) to fix mobile jump on scroll

### ISSUE THREAD

**Issue by minimit** [greensock/GSAP#476]
All **mobile device resize the viewport on scroll**.

There's a problem with Scrolltriggers pinned on bottom of the page on mobile: it jumps on mobile scroll.

This **doesn't happend on pinned elements on top of the page** because positioning is done with `top`, but when you have a **pinned elements on the bottom** of the page the pinned element jumps on scroll, it gets positioned the right way when the `resize` event triggers but the resize event has a delay it waits for the ui to show/hide.

A solution could be to use `bottom` instead of `top` for pinned elements on the bottom of the page.

When to use bottom instead of top is not clear to me, if it's possible to do automatically depending on `start` and `end` triggers or must be done manually with a new Scrolltrigger option.

**Comment by jackdoyle** [comment]
Could you please provide a minimal demo that shows exactly what you're talking about? Like perhaps a CodePen? Just the very basic concept, not a whole site.

**Comment by minimit** [comment]
Sorry for the delay, [here's a simple demo](https://cdpn.io/minimit/debug/JjrJVvN/VJMxxEDDaGKM) check it with iphone to see the bottom div jumping on scroll. Be sure to use codepen debug mode or the scroll doesn't work as intended. The code in editor mode is [here](https://codepen.io/minimit/pen/JjrJVvN).

**Comment by minimit** [comment]
It doesn't fix because the resize event gets executed after the full scroll stops and the address bar is completely moved, there's a jump on the position either way.

Positioning with `bottom` instead of `top` could fix this issue since the bottom value would not change on resize. But it's a complex thing to do feel free to close this issue.

**Comment by jackdoyle** [comment]
I see what you mean. Yeah, tricky - I'm not sure many people would really want/need this so I'm not inclined to add the kb to ScrollTrigger at the moment unless there's more demand for it but I appreciate the suggestion!
