### ISSUE TITLE
[enhancement] Scrolltrigger do not refresh on mobile resize if vertical only resize to fix mobile jump on scroll

### ISSUE THREAD

**Issue by minimit** [greensock/GSAP#477]
All **mobile device resize the viewport on scroll**.

With Scrolltrigger on mobile the triggers jump on scroll because the viewport changes. A fix I've implemented is to remove `resize` from `ScrollTrigger.config` `autoRefreshEvents` and triggering `ScrollTrigger.refresh()` on resize **but not if `matchMedia('(hover: none)').matches` and the resize is only vertical**.

This way on mobile the Scrolltrigger doesn't refresh on mobile scroll resize.

Could be useful on a Scrolltrigger settings.

**Comment by jackdoyle** [comment]
Thanks for sharing your solution, @minimit 

The problem is that assumes you don't have any CSS that depends on the viewport height. It's extremely common, though, to have panels that are 100vh height, for example, so if we implemented your suggestion I think all the start/end positions would be thrown off and never get corrected. See what I mean?

**Comment by minimit** [comment]
Yes I see but if you use `100vh` it needs to refresh on scroll, BUT it's really processive intensive to do that calculations on mobile scroll, and there are [some workarounds](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser) to have a `vh` on resize only on width change. It's really ugly the experience on mobile otherwise.

For this would be nice also in future also with the new [intrinsic-width](https://caniuse.com/intrinsic-width) to have this option available.

**Comment by jackdoyle** [comment]
I read your posts a few times and I'm still fuzzy on what exactly you're suggesting here. Could you please clarify? You're welcome, of course, to set things up exactly the way you described (the existing API already allows you to do that) - was there something you thought we needed to do to ScrollTrigger specifically? Are you suggesting some shortcut setting like mobileResizeRefresh: false that would disable the refresh whenever the window resizes (basically doing exactly what you described)? And then just trust that people won't build things with 100vh?

**Comment by minimit** [comment]
Yes I already do that in my project. I was just suggesting an option to not trigger the resize on touch devices when only the height changes on resize event.

I'm removing the resize from autoRefreshEvents and triggering mine on resize.
```
// removed resize we trigger it manually
ScrollTrigger.config({
  autoRefreshEvents: 'visibilitychange,DOMContentLoaded,load',
})
// window resize
const resize = e => {
  Xt.eventDelay({
    e,
    ns: 'xtScrolltriggerRerfreshFix',
    func: () => {
      ScrollTrigger.refresh()
    },
  })
}
removeEventListener('resize', resize)
addEventListener('resize', resize)
```

`Xt.eventDelay` is a bit complex function but inside has this code inside that do the check.
```
// we check also if outerWidth changes because on android doesn't change with ScrollTriggers
// we check also innerWidth for resize desktop (e.g. inspect and resize)
const w = window.innerWidth + window.outerWidth
const h = window.innerHeight + window.outerHeight
if (
  Xt.dataStorage.get(window, 'xtEventDelayWidth') === w && // when width changes
  (matchMedia('(hover: none)').matches || Xt.dataStorage.get(window, 'xtEventDelayHeight') === h) // when height changes not touch
) {
  // only width no height because it changes on scroll on mobile
  return
}
// save
Xt.dataStorage.set(
  window,
  `eventDelaySaveTimeout`,
  setTimeout(() => {
    Xt.dataStorage.set(window, 'xtEventDelayWidth', w)
    Xt.dataStorage.set(window, 'xtEventDelayHeight', h)
  }, Xt[`${e.type}Delay`])
)
```

**Comment by minimit** [comment]
Do as you like but to fix mobile scroll resize on scroll this is the only option.

**Comment by jackdoyle** [comment]
Just to make sure we're on the same page...

1. This proposed change would lead to the ScrollTrigger values being inaccurate when the mobile browser resizes, right? In other words, the "jump" you're trying to avoid is actually ScrollTrigger **correcting** things based on the new window size...but you're just saying that sometimes you (and other users) may prefer inaccuracy over the jump/correction, right? 
2. You could probably avoid the jump if you define the "viewport" part of your start/end values as numbers rather than percentages, assuming the trigger doesn't shift around too on resize.

**Comment by minimit** [comment]
> Just to make sure we're on the same page...
> 
> 1. This proposed change would lead to the ScrollTrigger values being inaccurate when the mobile browser resizes, right? In other words, the "jump" you're trying to avoid is actually ScrollTrigger **correcting** things based on the new window size...but you're just saying that sometimes you (and other users) may prefer inaccuracy over the jump/correction, right?

Yes but only if the resize doesn't change viewport `width` values.

> 2. You could probably avoid the jump if you define the "viewport" part of your start/end values as numbers rather than percentages, assuming the trigger doesn't shift around too on resize.

Probably but I think `number` in start and end values are not used as much as `viewport` (as `"bottom center"` this values we are talking about).
