### ISSUE TITLE
[enhancement] accept function in ease params

### ISSUE THREAD

**Issue by stephanedemotte** [greensock/GSAP#480]
Hello

Can be cool to accept a function in the ease params 

Example use case
```
import { sample } from 'lodash-es'
gsap.to('.el', { 
  x: 100,
  ease: () => sample(['expo.out', 'expo.in', 'circ.inOut'])
})
```

Thanks !

**Comment by jackdoyle** [comment]
You can already use a function - an ease function. It wouldn't work to make it a function that then returns an ease because obviously you couldn't have both. :)
