### ISSUE TITLE
Kill event listeners

### ISSUE THREAD

**Issue by kodermax** [greensock/GSAP#485]
This method does not remove listeners: scroll, resize, wheel,...
```
      ScrollTrigger.getAll().forEach((st) => st.kill())
```

How can I remove them?

![image](https://user-images.githubusercontent.com/590985/148409627-d32a828d-a5f2-41fd-b580-c06bb9cc85d6.png)

**Comment by jackdoyle** [comment]
ScrollTrigger itself needs listeners for global operations. Is there a particular reason you're trying to remove those? Or maybe I'm misunderstanding your question.

**Comment by kodermax** [comment]
I only use scrolltrigger on one page of my react app, and when navigating to another page, I don't need those listeners.

**Comment by jackdoyle** [comment]
Those listeners won't really cause any harm, but I can probably add some new static methods in the next release like: 

ScrollTrigger.disable()
ScrollTrigger.enable()

And that disable() call should get rid of all the listeners. You can try out a preview of the next release (minified) here: https://assets.codepen.io/16327/ScrollTrigger.min.js - let me know if that works better for you.

**Comment by kodermax** [comment]
Yes, it will be perfect for me. Thanks!
