### ISSUE TITLE
Incorrect totalDuration() value after timeScale() is applied on child timeline

### ISSUE THREAD

**Issue by chototoro** [greensock/GSAP#488]
Hi there,

It seems that applying a timeScale on a child timeline is not changing the totalDuration of the parent timeline if the playhead has not moved yet.

I set up a reduced case: https://codepen.io/chototoro/pen/ZEXNQLp

As you can see, the totalDuration() value of the parent timeline is not refreshed after the timeScale() call. I thought at first that there might be a slight delay (hence the setTimeout in the demo), but it is in fact related to the playhead of the parent being on 0. Is it normal behavior, perhaps something to avoid a zero-division?

For now, as a workaround, calling seek(0.001), then immediately seek(0) on parent timeline correctly updates totalDuration().
Edit: Workaround doesn't seem to work on more complex timelines.

**Comment by jackdoyle** [comment]
Thanks for the reduced test case, @chototoro ! 

That should be resolved in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

Better? 

It basically has to do with internal performance optimizations that skip re-calculating the duration unless there were changes to the child animations so you could make any other change to the timeline that might affect its duration, even if it's adding/removing a simple child that doesn't actually animate anything, like tl.to({}, {}, 0).remove(tl.recent()); which would trigger it to re-calculate things. 

Sorry about any confusion there.

**Comment by chototoro** [comment]
It works perfectly! 👍 Thank you @jackdoyle!
