### ISSUE TITLE
Parallax with ScrollTrigger is In Viewport not working ...

### ISSUE THREAD

**Issue by ValordProd** [greensock/GSAP#491]
Hey all,

I'm actually trying to apply my scrolltrigger parallax effect only when my element in in viewport but I can't make it works ...
Has someone already went through something similar ? Can someone help me wake it works ?

Here's the demo : [https://codepen.io/ValentinBossens/pen/jOaNMRj](url)

```
if (ScrollTrigger.isInViewport(".block-1")) {
  gsap.to(".block-1", {
    yPercent: 100,
    ease: "none",
    scrollTrigger: {
      trigger: ".block-1",
      start: "top bottom",
      end: "bottom top",
      scrub: true,
      markers: true,
      id: 'block-1'
    }, 
  });
}
```

Thanks in advance.

Valord

**Comment by jackdoyle** [comment]
I wonder if you're looking for something like this?: 
https://codepen.io/GreenSock/pen/XWzKvQM?editors=1010

I would definitely encourage you to post this type of question in the forums at https://greensock.com/forums rather than creating a Github issue.

**Comment by ValordProd** [comment]
Hey @jackdoyle ,

Thank you for your help, it's exactly what I was looking for !

If I have other questions, I'll definitely post them directly in the Greensock forums.
Thanks again

**Comment by jackdoyle** [comment]
No problem. Glad it helped!
