### ISSUE TITLE
ScrollTrigger.StartEndFunc type declaration missing parameter

### ISSUE THREAD

**Issue by millerrafi** [greensock/GSAP#493]
Hi, I'm getting a TypeScript warning on code that looks like this:

```ts
  ScrollTrigger.create({
    trigger,
    start: ({ trigger }) => {
      return (trigger as HTMLElement).offsetHeight > window.innerHeight * 0.3
        ? // it's tall
          'top 80%'
        : // it's short
          'bottom 105%';
    }
  });
  ```
  
  The warning is this:
  ```
  Type '({ trigger }: { trigger: any; }) => "top 80%" | "bottom 105%"' is not assignable to type 'string | number | StartEndFunc'.
  ```
  
  The simple fix appears to be updating [the declaration](https://github.com/greensock/GSAP/blob/c92a7fc5b3201239eb9f4caf0a96401eb20f1dc4/types/scroll-trigger.d.ts#L603) with a parameter:
  
 ```ts
   type StartEndFunc = (self: ScrollTrigger) => string | number;
  ``` 
  
  Happy to submit a PR if helpful. Thank you!

**Comment by jackdoyle** [comment]
Thanks for pointing that out - we'll get it into the next release.
