### ISSUE TITLE
ScrollToPlugin its not working，please help me，thanks u

### ISSUE THREAD

**Issue by freedomwebcn** [greensock/GSAP#495]
codePen:
https://codepen.io/wzckhwgz-the-reactor/pen/NWwZGNm?editors=1111

**Comment by jackdoyle** [comment]
There are several problems:

1. You were targeting the wrong element (one that doesn't scroll)
2. You didn't specify that you wanted it to scroll in the "x" direction (default is "y")
3. You're using VERY old versions of GSAP. I'd strongly recommend updating to the modern files which are smaller, more powerful, and more capable. See https://greensock.com/3-migration. You don't NEED to upgrade - I'm just recommending it. 

https://codepen.io/GreenSock/pen/QWOXyzq?editors=0011

(already answered your duplicate post in the forums). 

Happy tweening!

**Comment by freedomwebcn** [comment]
> There are several problems:
> 
> 1. You were targeting the wrong element (one that doesn't scroll)
> 2. You didn't specify that you wanted it to scroll in the "x" direction (default is "y")
> 3. You're using VERY old versions of GSAP. I'd strongly recommend updating to the modern files which are smaller, more powerful, and more capable. See https://greensock.com/3-migration  You don't NEED to upgrade - I'm just recommending it.
> 
> https://codepen.io/GreenSock/pen/QWOXyzq?editors=0011
> 
> (already answered your duplicate post in the forums).
> 
> Happy tweening!

thanks,its working
