### ISSUE TITLE
Help with scrollTrigger

### ISSUE THREAD

**Issue by tonirpk** [greensock/GSAP#496]
Hello,
So I was inspired by this design https://codepen.io/tonirpk/pen/gOoYrdg
I was wondering how can I make my window's view stay on the same element that I'm animating while scrolling until the animation is over then move to the next element?

**Comment by tonirpk** [comment]
Had to make the postion sticky in case someone was wondering.

**Comment by jackdoyle** [comment]
You could also use ScrollTrigger's "pin" feature.
