### ISSUE TITLE
Getting Trusted Type error from Draggable.js

### ISSUE THREAD

**Issue by ericuldall** [greensock/GSAP#502]
We currently use gsap in our chrome extension content script and we have an element injected onto the page that is draggable. It works pretty good in general except on sets the have a Trusted Types CSP (https://web.dev/trusted-types/). It seems the following line is causing issues:

https://github.com/greensock/GSAP/blob/master/src/Draggable.js#L556

That line needs to be set as a trusted type in order to work correctly under the new CSP. I'm not sure exactly what that assignment is doing but would be great if there was a quick fix for this.

Any ideas?

**Comment by OSUblake** [comment]
Is it just the innerHTML that is causing the issue?

**Comment by ericuldall** [comment]
I assume so (not 100% certain), and i'm not sure what the purpose of that innerHTML is.

**Comment by ericuldall** [comment]
The errors is somewhat vague: 
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/3223296/167497801-67edd6b5-a47d-4e67-9f99-9c44be91d5eb.png">

**Comment by OSUblake** [comment]
If the child does need some content for some reason, maybe try `child.textContent` instead of `child.innerHTML`.

**Comment by ericuldall** [comment]
It works after commenting out the innerHTML call, so that is definitely the culprit. If we can get some verification on if it's necessary (not sure why css would need to be in the inner html of a div) maybe it can be completely removed.

**Comment by OSUblake** [comment]
Yeah, we'll need to wait for Jack to answer why the innerHTML is being set and if it's really needed.

**Comment by ericuldall** [comment]
For what it's worth, my element is still draggable without it 🤷

**Comment by ericuldall** [comment]
created PR #503 to address the issue, if Jack confirms vestigial assignment

**Comment by jackdoyle** [comment]
I suspect that was originally intended to have some content in the element, perhaps to prevent collapse but the width/height assignment should accomplish that anyway so I'd guess it's safe to remove. That part of the code was written years ago so it's tough to remember. I assume everything worked fine for you when you removed it? We can aim to do that in the next release.

**Comment by ericuldall** [comment]
Yes works normally as far as I can tell.
