### ISSUE TITLE
support Node.js ESM?

### ISSUE THREAD

**Issue by ichitaro** [greensock/GSAP#505]
I am not familiar with module bundlers, but I was wondering if the GSAP's  package.json should be modified in the future as follows:
```javascript
{
  "main": "./index.js",
  "types": "./types/index.d.ts",
  "type": "module",
  "exports": {
    ".": {
      "types": "./types/index.d.ts",
      "require": "./dist/gsap.js",
      "default": "./index.js"
    },
    "./ScrollTrigger": {
      "types": "./types/scroll-trigger.d.ts",
      "require": "./dist/ScrollTrigger.js",
      "default": "./ScrollTrigger.js"
    },
    // ...otherPlugins
  }
}
```

I understand how to transpile and use the ESM version of GSAP in Next.js / Nuxt.js.

For Nuxt.js:
https://greensock.com/docs/v3/Installation#npm-club

For Next.js:
```bash
npm install --save next-transpile-modules
```

```javascript
// next.config.js
const withTM = require('next-transpile-modules')(['gsap'])
module.exports = withTM({ /* Next Config */ })
```

```javascript
// and import individual classes like:
import { gsap } from 'gsap'
import ScrollTrigger from 'gsap/ScrollTrigger'

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger)
}
```

However, since Native ESM is now supported in Next12, I believe that if GSAP's package.json is modified like above, then next-transpile-modules will no longer be needed.

I am not sure if this will work for all major module bundlers. But for example, Three.js has this style.
https://github.com/mrdoob/three.js/blob/dev/package.json

## Is this just an SSR issue?
When I import GSAP and its plugins directly in my application code, everything works fine!

However, it seems difficult to create my own NPM package that depends on GSAP plugins as `"peerDependencies": { "gsap": "^3.x.x" }`.

e.g. `useScrollTrigger()` React Hook (that also works with Next.js)

Sorry if I'm misguided, but I think it would be better to add "exports" field to GSAP's package.json to let the module bundler know that plugins such as ScrollTrigger have own entry point.

**Comment by ichitaro** [comment]
Sorry, I understood my question was misplaced.

I found that if I create a separate package that depends on gsap with `peerDependencies` and want to use it in Next.js, I can simply add that to `next-transpile-modules` along with gsap. And my package should not be `type: "module"`.

**Comment by jackdoyle** [comment]
Thanks for reporting back.
