### ISSUE TITLE
如何实现全屏无缝滚动

### ISSUE THREAD

**Issue by orochitian** [greensock/GSAP#509]
根据官方给出的示例来看，通过ModifiersPlugin实现无缝滚动必须要有固定的宽度。
我需要实际滚动的宽度自适应浏览器宽度，有没有比较正确的做法？

**Comment by jackdoyle** [comment]
If you have a GSAP-specific question, the best thing to do is post it in the forums along with a minimal demo so we can see it in context and offer a solution. https://greensock.com/forums

You might want to look at the helper function in the docs for seamlessly looping on the x-axis: 
https://greensock.com/docs/v3/HelperFunctions#loop

Happy tweening!
