### ISSUE TITLE
Cannot remove first event listener from Draggable

### ISSUE THREAD

**Issue by marten-wirelab** [greensock/GSAP#510]
There's a bug in the code for `Draggable.removeEventListener`:
https://github.com/greensock/GSAP/blob/4d2d07bfd5d5890e3aa1a13f0eb16a7758b02f2e/src/Draggable.js#L625-L628

If the index of the listener is 0, it cannot be removed, as 0 is falsy, meaning `i` will be -1, so the item will not be removed from the listeners list.
This is a problem when attaching handlers in a `useEffect` hook in React, because they need to be detached whenever the dependencies of the effect change.

I'm currently working around this by attaching a dummy handler to each of the events I'll be using later, so any later handlers will never get an index of 0.

**Comment by jackdoyle** [comment]
Thanks for pointing that outI It'll be fixed in the next release.

**Comment by jackdoyle** [comment]
Fixed in latest release.
