### ISSUE TITLE
Timeline saved in proxied variable (gsap in vue3)

### ISSUE THREAD

**Issue by artekkk** [greensock/GSAP#512]
In vue3 variables defined in data() are transformed to proxies (es6) by default. A timeline saved in a proxied variable can't be manipulated. Can this be intercepted/handled by gsap?

Example:

```
data() {
    return {
        tl: null,
    };
},
mounted() {
    this.tl = gsap.timeline({ paused: true });
    this.tl.to('element', { x: 100, duration: 1 }); // tween can not be applied
}
```

Current workaround in vue3:

https://vuejs.org/api/reactivity-advanced.html#toraw

import { toRaw } from 'vue';

toRaw(this.tl).to('element', { x: 100, duration: 1 });

**Comment by jackdoyle** [comment]
Hi @artekkk 

That definitely sounds like a Vue question. I'm not very familiar with Vue, but GSAP was specifically designed to be framework agnostic, so it works great with Vue, React, Angular, vanilla, etc. 

Why would you need to create some kind of proxy element anyway? Why not just directly work with GSAP objects? That's normally how I've seen it done in Vue. 

If you're still struggling, it'd be great if you could provide a minimal demo that clearly illustrates the problem (like a CodePen). But again, this definitely sounds like a Vue question, not a GSAP one.
