### ISSUE TITLE
 ScrollTrigger.matchMedia - Failed to execute 'querySelectorAll' on 'Document': '(min-width: 1328px)' is not a valid selector.

### ISSUE THREAD

**Issue by abereghici** [greensock/GSAP#514]
ScrollTrigger.matchMedia throws an error in the latest version of gsap (3.11.0):
```
{"name":"SyntaxError","message":"Failed to execute 'querySelectorAll' on 'Document': '(min-width: 1328px)' is not a valid selector.","stack":"Error: Failed to execute 'querySelectorAll' on 'Document': '(min-width: 1328px)' is not a valid selector.\n }
```
for the code 
```
 ScrollTrigger.matchMedia({
      '(min-width: 1328px)': () => {},
});
```

This is working fine with gsap(3.10.4).

**Comment by jackdoyle** [comment]
Sorry about that, @abereghici . That should be resolved in the next release which you can preview at https://assets.codepen.io/16327/ScrollTrigger.min.js

Better?

**Comment by amberyufangchiu** [comment]
faced same problem. thank you @abereghici

**Comment by abereghici** [comment]
thanks @jackdoyle !

**Comment by jackdoyle** [comment]
Fixed in the latest release.
