### ISSUE TITLE
MotionPathPlugin + PixiJS throws error on CSSPlugin

### ISSUE THREAD

**Issue by diegomachado** [greensock/GSAP#516]
I'm using GSAP with Typescript on a project that only uses PixiJS and I'm getting the following error when I add multiple MotionPaths to a Timeline:

<img width="364" alt="gsap-motionpath-pixijs" src="https://user-images.githubusercontent.com/104657/193608471-488d3081-0c7b-4a7a-9b9c-3e00cc9c30f9.png">

As you can see, the error is triggered on the CSSPlugin which is not even used on my game.
Anyone can point me in the right direction on possible causes or solutions?

**Comment by jackdoyle** [comment]
Hi @diegomachado  What version are you using? Please make sure you're using the very latest.

Would you mind either providing a minimal demo (like in CodePen) or trying the latest beta file which is at https://assets.codepen.io/16327/gsap-latest-beta.min.js ? I suspect it's already resolved.

**Comment by diegomachado** [comment]
Hi @jackdoyle, thank you for your fast response!

I was still doing some tests before anwsering you and I'm happy to tell that you were right, I was using the `3.11.1` version, updating it to `3.11.3` seems to fix the bug as far as I have tested. 

I'll let you know if something similar comes up again.

**Comment by jackdoyle** [comment]
No problem! Glad to hear it's working now.
