### ISSUE TITLE
css `transform` style was completely overwritten by draggable plugin

### ISSUE THREAD

**Issue by Paper-Folding** [greensock/GSAP#517]
I tried to use draggable plugin, initially I have my DOM element applied with `transform: scale3d(1.25, 1.25, 1)`.
After I applied draggable plugin to it and  then drag it, my old transform style was replaced by `transform: translate3d([x], [y], [z])`, I think that must be draggable plugin's deal, how can I make draggable plugin do not overwrite my transform style?

**Comment by jackdoyle** [comment]
Got a minimal demo? I'm not seeing any problems at all: 
https://codepen.io/GreenSock/pen/bGMjmXp

The demo has two elements on top of each other with exactly the transform you supplied. They match up perfect even after one of them gets Draggable applied. Am I missing something?

**Comment by Paper-Folding** [comment]
> Got a minimal demo? I'm not seeing any problems at all: https://codepen.io/GreenSock/pen/bGMjmXp
> 
> The demo has two elements on top of each other with exactly the transform you supplied. They match up perfect even after one of them gets Draggable applied. Am I missing something?

Thank you for your reply! Here I modified your minimal demo and got the issue showing up:  
https://codepen.io/paper-folding/pen/RwyBdGb  

Click the "scale for 1.25" button to make the rectangle apply a `scale3d(1.25, 1.25, 1)`, and then drag the rectangle, you shall see the dragging rectangle was shrunk back to original scale.

**Comment by jackdoyle** [comment]
Oh! Yeah, you definitely should not do that. ALWAYS set your transforms via GSAP.  Here's an explanation: 
https://greensock.com/mistakes#transforms

And here's a fork showing that it works and it's much simpler too: 
https://codepen.io/GreenSock/pen/dyejrKy?editors=1010

**Comment by jackdoyle** [comment]
This also explains why doing transforms via GSAP is helpful: https://www.youtube.com/watch?v=MjN22sQp5pU

**Comment by Paper-Folding** [comment]
That reminds me: Now that I am newly importing gsap to handle animation, I should get rid of my old code. Really appreciate your help!

**Comment by jackdoyle** [comment]
No problem. Happy to help! Enjoy your animation adventures.
