### ISSUE TITLE
How to add Linear gradient to svg's path

### ISSUE THREAD

**Issue by NEBA0317** [greensock/GSAP#518]
when I add linear gradient property in fill, it does not working

```
  const tl = gsap.timeline({ repeat: -1 });

  tl.fromTo(
    "#tree1-1-1",
    {
      fill: "linear-gradient(62.48deg, #ffdcc9 0%, #ffdad2 0%, #76ffe9 36.08%, #fff3d4 68.45%, #ffffd4 100%)",
      ease: "sine.inOut",
      duration: 2,
    },
    {
      fill: "linear-gradient(62.48deg, #ffdcc9 0%, #ffdad2 0%, #76ffe9 36.08%, #fff3d4 68.45%, #ffffd4 100%)",
      ease: "sine.inOut",
      duration: 2,
    }
  );
```

**Comment by jackdoyle** [comment]
I see a few problems: 
- That's an invalid fill value in HTML/CSS (unrelated to GSAP). Perhaps you meant backgroundImage? 
- You're setting an ease and duration in the "from" part of a tween. Those only go in the "to" part. 
- BOTH the start and end values match. Didn't you want to animate something? 

Here's a quick demo with backgroundImage: 
https://codepen.io/GreenSock/pen/JjZPLyB?editors=0010

Maybe you meant to use a path that has a stroke and then use that as a mask of an element that's filled with a gradient? 

If you still need help, please post your question in the forums at https://greensock.com/forums along with a minimal demo and we'd be happy to take a peek.
