### ISSUE TITLE
QuickTo & ScrollTo plugin seems not working together

### ISSUE THREAD

**Issue by lavolpecheprogramma** [greensock/GSAP#519]
Hi!
i tried to use the quickTo method with scrollTo plugin, but it seems not working properly.
Am i doing something wrong?

[Here a reproduction](https://codepen.io/lavolpecheprogramma/pen/dyKPMEz?editors=1111)

This is the error in console.
![Schermata 2022-10-26 alle 16 55 35](https://user-images.githubusercontent.com/19146698/198061053-069605c5-23f7-4c06-81a8-a8b80903dbc9.png)

Thanks for your time.

**Comment by jackdoyle** [comment]
From the docs: 

> this is only for direct properties or CSS-related properties of the target. You cannot, for example, use an attr:{} value or morphSVG, etc.

You're trying to use quickTo() with a plugin which won't work. Part of the reason it can optimize performance so much is because it skips all the plugin parsing and other stuff. 

You could easily use a proxy, though: 
https://codepen.io/GreenSock/pen/oNygBwE?editors=0010
