### ISSUE TITLE
GSAP Markers positioning bug

### ISSUE THREAD

**Issue by valecss** [greensock/GSAP#520]
Hi all, I am trying to develop a site using GSAP's ScrollTrigger plugin, which set up like this:

```vue
<template>
    <div class="layout-container">
        <div class="landing-container">
            ...
            <section class="development">...</section>
            ...
        </div>
    </div>
</template>

<script>
...
gsap.to(".landing-container", {
  scrollTrigger: {
    trigger: ".development",
    start: "top top",
    end: "400% center",
    markers: true,
    pin: ".layout-container",
    onUpdate: (e) => {
        ...
    },
  },
});
...
</script>
```

But as per the attached video, at the first start of the page the markers are not in the indicated position ("top ..."), but more above, yet when I resize the page they come back. Once the markers are cached they are correct even when I reload the page, but they return to the wrong position after SHIFT+ F5.

https://user-images.githubusercontent.com/55705175/200953737-74f3a749-00b8-44f8-a465-db6e7148a883.mp4

**Comment by valecss** [comment]
Okay, I found a "solution."

I understand from this [stackoverflow](https://stackoverflow.com/questions/71258268/gsap-sets-scrolltrigger-markers-before-images-load-and-animation-does-not-run-on), GSAP initializes the markers when the DOM content is loaded, however, it doesn't wait for the "loading" time of the images, and if I'm not mistaken, when an image is loading, the height property if not set is "dynamic" as the image is loading from top to bottom. So the solution I found is to write a function that waits X seconds, or listens for an event on the loading state the images are ready, and initializes GSAP and animations.

**Comment by jackdoyle** [comment]
ScrollTrigger.refresh() triggers all the start/end positions to get calculated (and markers positioned), and that is automatically called both on "DOMContentLoaded" and "load" events. Typically the "load" doesn't fire until all the images are fully loaded and rendered. However, my guess is that you're either using lazy loading (which interferes with that behavior) or you're using some kind of framework that's dynamically injecting things into the DOM, so ScrollTrigger can't possibly know when the DOM is done being shifted around. So in that scenario, you simply have to call ScrollTrigger.refresh() manually, like in a lifecycle event or basically whenever you know that layout is fully settled. 

You don't need to wait to create all your tween/ScrollTriggers. It's fine to create them as soon as the elements exist, but simply call ScrollTrigger.refresh() when you need the start/end values to get recalculated. 

Does that clear things up?
