### ISSUE TITLE
Suggestion: Add onRepeatDelay eventCallback

### ISSUE THREAD

**Issue by Rohaq** [greensock/GSAP#526]
There are already callbacks for `onStart`, `onComplete`, and `onRepeat` - but there's no callback present for when a `repeatDelay` is triggered. `onRepeatDelay` feels fairly complimentary to the existing `onRepeat` callback in regards to event management.

This could be useful for say, emitting an event to another component on the start of the `repeatDelay`, or changing sprite images to allow for simple start/stop animations.

**Comment by jackdoyle** [comment]
Thanks for the suggestion, @Rohaq 

We're always looking to make things better, so we're very open to things like this.

If I'm totally honest, a few things cause me to be reluctant to add something like this: 
- kb - I've been doing this for 13+ years and I don't think I've ever had the need for something like this nor has anyone else requested it, so I'm just not sure it'd be worth making everyone pay the kb price for it. 
- Functionally, I worry about some edge cases. Like should it fire when entering the "repeatDelay" portion from either direction (forward and reverse)? What if the user jumped the playhead to a time that's right in the middle of the repeatDelay (like using seek()) - should it fire? I imagine some people would write their code only thinking about it firing the moment the playhead reaches the repeatDelay part in the forward direction, so their logic may depend on that...but then break when a seek() occurs to an intermediary position. 
- Would people want onRepeatDelay to fire when that time starts or ends? Will we then gets requests for onRepeatDelayStart and onRepeatDelayEnd? What should happen when yoyo: true is enabled? 

Plus, can't you already get this functionality with the current API? For example, let's say you've got this tween:
```javascript
gsap.to(".box", {
	x: 500,
	duration: 1,
	repeat: 3,
	repeatDelay: 1,
	onRepeat: () => console.log("onRepeat")
});
```

Here's how you could change it to get an onRepeatDelay in the forward direction: 
```javascript
gsap.timeline({
	onRepeat: () => console.log("onRepeat"),
	repeatDelay: 1,
	repeat: 3
}).to(".box", {
	x: 500,
	duration: 1,
	onComplete: () => console.log("onRepeatDelay")
});
```
See what I mean?

**Comment by Rohaq** [comment]
The issue in my particular use case, I'm animating a Vue 3 component, and trying to use these callbacks to change the image on particular animation events. Whenever I tried to use a timelines, it didn't work, since I was reliant on repeatRefresh to prevent the animation from resetting position on repeat.

Here's what I have at the moment:

```ts
// initial sprite image = spriteStill
var fakeOut = gsap
    .to(root.value, {
      translateX: "+=20",
      repeatRefresh: true,
      ease: "power1.in",
      onStart: changeFrame,
      onStartParams: [spriteSus],
      onRepeat: changeFrame,
      onRepeatParams: [spriteSus],
      onComplete: changeFrame,
      onCompleteParams: [spriteSlam],
    })
    .delay(randInt(1, 3))
    .repeat(randInt(1, 5))
    .repeatDelay(randInt(1, 3));
```

So it starts with `spriteStill` as the image, edges forward a few times with random values, changing the sprite on the start and on repeat - which obviously does nothing right now, but if I could do a callback on `repeatDelay`, I could switch it back to `spriteStill`.

That said, good points about the reverse/yoyo. I'm not sure. I've slapped together a lifecycle diagram for the basic process as in my own use case below, but an expanded lifecycle diagram of the eventCallback processes would be useful. How do these already operate with `onRepeat` and `onComplete` event callbacks specified?

As for the requests for `onRepeatDelayStart` and `onRepeatDelayEnd` - the latter case is already covered by `onRepeat`, and the former is what I'm actually already suggesting in `onRepeatDelay`.

Hopefully these diagrams help explain it a little more clearly?

Current Event Lifecycle:
![image](https://user-images.githubusercontent.com/246865/219969194-2b158749-53db-4ea9-be4b-ad53231546c5.png)

Proposed Event Lifecycle:
![image](https://user-images.githubusercontent.com/246865/219969214-10d102ea-d987-49fe-944c-50f2c9b10eb7.png)

**Comment by jackdoyle** [comment]
> Whenever I tried to use a timelines, it didn't work, since I was reliant on repeatRefresh to prevent the animation from resetting position on repeat.

I'm a little fuzzy on what you mean here. Did my sample code not work for you? Can you provide a super simple minimal demo (like in CodePen) that clearly illustrates the problem (and why you can't use the solution I provided)? I'm sure once I see the actual demo, it'll become more clear to me.

**Comment by Rohaq** [comment]
Sorry, I should have been clearer - I tried using timelines to do what I needed before and had no luck because it broke the `repeatRefresh` effect - so the animation ended up moving, delaying, and then resetting to its original position on repeat, instead of inching forward each time as I wanted - but it's possible may have done it wrong.

I'll retry it with your example and see if it'll do what I need in the meantime, and if not I'll set up an example - but I still think this could have value for animation event driven actions, and would massively simplify the process.

**Comment by jackdoyle** [comment]
Yeah, a demo would be super amazingly helpful, both to illustrate whatever problem you ran into with the repeatRefresh (I'm curious what that was about) as well as if the solution I provided doesn't work the way you wanted.

**Comment by Rohaq** [comment]
Okay, I think I've put together a decent enough demo for this. It's late and I've gotta sleep, but I've implemented both my original animation, and your suggested one:

https://codepen.io/Rohaq/pen/vYzLWMK

**Comment by jackdoyle** [comment]
I noticed several problems: 
- You didn't follow my instructions for the solution - you used onStart instead of onComplete. 
- You set repeatRefresh: true on the child tween which has no repeat set at all, so there will be no refreshing (you can't repeatRefresh if there's no repeat). You'd need to set repeatRefresh: true on the parent that actually has a repeat value set. 
- In "#mine" (yours), you've got it setting to amber onRepeat and also onStart (same value), but in the "#suggested" you've got it setting to amber and then red but I assume that's because you actually wanted it to turn red just during the repeatDelay part, right?

Once I corrected the problems, it seems to work as expected, right?: 
https://codepen.io/GreenSock/pen/bGxExvx?editors=0010

**Comment by Rohaq** [comment]
That's what I get for trying to toss a demo together last minute!

That's awesome, I had to add an `onStart` to the timeline to change frames, but otherwise it works great! Thanks for all your help!: https://codepen.io/Rohaq/pen/poOyEYm

I may still fork off and try adding the callback myself - I'm interested in answering some of the questions you asked previously about possible interactions with other behaviours.

**Comment by jackdoyle** [comment]
Super, thanks.
