### ISSUE TITLE
timeline.from() destroys timeline.revert()

### ISSUE THREAD

**Issue by YassBaer** [greensock/GSAP#527]
Hey there,

It seems like having a timeline.from() call at the beginning of your animation breaks the effect of timeline.revert(). I have a timeline doing multiple things and on the last Tween I have an onComplete Callback reverting the timeline. I needed to do this to start another animation on the same object with a clean slate. However the inline styles do net get removed entirely, in fact just the one coming from the .from()-Tween remains. That disrupts the second animation, because it assumes a wrong starting position messing with the .from() i've used there. 

This might also be a problem on the revert functions on gsap or context objects, I have not tested those.

Hope this can be fixed and my explanation of the problem was clear.
Feel free to reach out to me if it wasn't.
Cheers

**Comment by jackdoyle** [comment]
Hi @YassBaer I don't have a lot of time right now to dig into this, but would you happen to have a minimal demo that clearly illustrates the problem? That would be a tremendous help. 

Here's a starter CodePen that loads all the plugins. Just click "fork" at the bottom right and make your minimal demo: https://codepen.io/GreenSock/pen/aYYOdN

**Comment by jackdoyle** [comment]
I can't seem to replicate the problem, @YassBaer 

Here's a super simple demo that seems to work exactly the way it should: 
https://codepen.io/GreenSock/pen/MWqeKdd?editors=0010

Am I missing something? Can you fork that demo and break it?

**Comment by jackdoyle** [comment]
That's a good suggestion, @sadeghbarati Thank you!

Don't have time to look into exactly how to implement that right now, but we'll consider it for the future.
