### ISSUE TITLE
How to trigger per each scroll with scrolltrigger or gsap in react typescript

### ISSUE THREAD

**Issue by lazarus2019** [greensock/GSAP#530]
I have like 10 paragraphs and I expect that will appear each scroll

**Comment by jackdoyle** [comment]
Hi @lazarus2019 

This is a great question to post in the forums at https://greensock.com/forums. Make sure you provide a minimal demo too. Here's a Stackblitz starter template that you can just fork: 
https://stackblitz.com/edit/react-cxv92j

Once we see your question in the forums with a minimal demo (even if that demo isn't working the way you want - just something simple), we'd be happy to offer some advice.
