### ISSUE TITLE
3.11.5 new error with MotionPath: "Failed to execute 'getComputedStyle'"

### ISSUE THREAD

**Issue by StephenHaney** [greensock/GSAP#531]
Hey all – when I updated to 3.11.5, my MotionPath plugin started crashing with the error `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

I'm not targeting an HTMLElement, I'm targeting a babylon.js mesh's `position` property. This was working as expected in 3.11.4.

I've reverted and pinned 3.11.4 for now. Any pointers on what is happening? Appreciate any help!

Here is my code.
```
    gsap.to(this.damageNumber.position, {
      motionPath: [
        { x: x + 0.5 * xDirection, y: y + 0.1 + 0.667 * amplitude },
        { x: x + 1.1 * xDirection, y: y - 0.7 - 0.8 * amplitude },
      ],
      duration: flingDuration,
      delay: scaleDuration + 0.1,
    });
```

```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at _parseTransform2 (CSSPlugin.js:793:12)
    at _get2 (CSSPlugin.js:397:13)
    at Object._saveStyle2 [as save] (CSSPlugin.js:96:75)
    at CSSPlugin.js:99:27
    at Array.forEach (<anonymous>)
    at Object._saveStyle2 [as save] (CSSPlugin.js:98:52)
    at CSSPlugin.js:166:18
    at Array.forEach (<anonymous>)
    at _getStyleSaver2 (CSSPlugin.js:165:39)
    at Plugin.init3 [as init] (MotionPathPlugin.js:260:37)
```

**Comment by jackdoyle** [comment]
I do apologize - this should be fixed in the next release which you can preview at: 
https://assets.codepen.io/16327/gsap-latest-beta.min.js

One of the improvements we made in 3.11.5 inadvertently introduced this problem if the target of your motionPath tween is not a DOM element. Please try replacing the core GSAP file with the beta file I linked to above and let us know if it resolves things for you. If you need an ES Module instead, let me know and I can get you that.

**Comment by StephenHaney** [comment]
I'm using npm and esm imports. Happy to help test, but also no need to provide a fix for me until the new version ships.

I always pin dependencies (no such thing as a non-breaking change imo) so I don't mind hanging out on 3.11.4 until the new version ships.

**Comment by jackdoyle** [comment]
Sure, here's a .tgz file that you can npm install: 
https://greensock.com/temp/gsap-beta.tgz

(link valid for at least the next 5 days)

Does that help?
