### ISSUE TITLE
timeline kill tween bug,next add an tween,the tween's data  turn  to lastData directly 

### ISSUE THREAD

**Issue by yanchenjun00** [greensock/GSAP#535]
1.first timeline kill an tween which is running ,
2.add an tween 
Result: the tween's data  turn  to lastData directly 

tween,kill(targte,"x,y"),next  add an tween also  turn  to lastData directly

**Comment by jackdoyle** [comment]
Hi @yanchenjun00 

I read your post several times but I'm still very confused. What is "lastData"? Do you have a minimal demo (like a CodePen) that clearly illustrates the issue? I'd love to help but I'm lost.
