### ISSUE TITLE
`child.parent.remove is not a function` when killing a context with stagger 

### ISSUE THREAD

**Issue by nagman** [greensock/GSAP#536]
This is a very specific bug:

I'm working with react (Next.js 13, to be precise), and I have a gsap.context inside a `useIsomorphicLayoutEffect` hook:

```ts
useIsomorphicLayoutEffect(() => {
  const ctx = gsap.context(() => {
    gsap.fromTo('.hr', { scaleX: 0 }, { scaleX: 1, stagger: 0.1 });
  });

  return () => {
    ctx.kill();
  };
}, []);
```

Each time I reload the page, I get this blocking error:
```

Unhandled Runtime Error
TypeError: child.parent.remove is not a function
```
And it points to the `ctx.kill();` method.

If I remove the `stagger` property, it works... 🤷‍♂️  
Or if I directly kill my gsap timeline without using the context, it works too.

But I want both the context and the stagger :'(

I haven't found anything on the web that talks about a `child.parent.remove` method related to the stagger or the context.

**Comment by jackdoyle** [comment]
Great catch, @nagman Sorry about that - it should be resolved in the next release which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

If you need a .tgz to npm install, let me know.
