### ISSUE TITLE
ScrollTrigger endTrigger isn't scoped by context/matchMedia

### ISSUE THREAD

**Issue by antonjb** [greensock/GSAP#537]
Hi greensock,

I believe there is an issue with ScrollTrigger's endTrigger not being scoped by gsap.context or gsap.matchMedia.

Here is a CodePen of the issue I'm experiencing: https://codepen.io/antonjb/pen/mdzqGxK

Steps to reproduce:
1. Comment out the first instance of `.stopper`
2. The Marker will move down to the second instance of `.stopper` and scrolling will work
3. Uncomment the first instance and the end marker moves up to the first stopper despite the scope being set to the containing `.wrapper` element

There's also an extra `.square` element, which is the trigger, if you uncomment that, the start marker does not change, meaning that the scope is working for the trigger.

Scroll end marker in the correct place

![CleanShot 2023-05-04 at 14 54 24](https://user-images.githubusercontent.com/1066856/236131801-ae73c031-25a1-467e-b05d-b065d167fdb5.png)

When the extra stopper is uncommented, it's in the incorrect place

![CleanShot 2023-05-04 at 14 55 17](https://user-images.githubusercontent.com/1066856/236131925-ff75d7e1-d915-4907-8410-53ff247dabf8.png)

**Comment by antonjb** [comment]
My current workaround is to use the [selector utility method](https://greensock.com/docs/v3/GSAP/UtilityMethods/selector())

```js
const matchMediaCTX = gsap.matchMedia($ref)
const q = gsap.utils.selector($ref)

matchMediaCTX.add('(min-width: 769px', () => {
    ScrollTrigger.create({
        start: 'center center',
        end: 'center center',
        trigger: ".sticky",
        endTrigger: q(".stopper"),
        pin: true,
        scrub: true,
    })
})
```

**Comment by jackdoyle** [comment]
Thanks for pointing this out and providing an excellent minimal demo. Super helpful! This should be resolved in the next release. It only affects when you use selector text for the endTrigger. Your workaround solves it well, and you could also just pass in a reference to the actual element rather than selector text.
