### ISSUE TITLE
https://greensock.com/ The offical website can't visit

### ISSUE THREAD

**Issue by HDZZZ** [greensock/GSAP#540]
![1686014294667](https://github.com/greensock/GSAP/assets/25112956/684a280e-5b67-4067-ab78-2117134d429f)
I can't visit the website, so I can't look at the documents and examples.

**Comment by jackdoyle** [comment]
The site seems to be fine - is it still not working for you? I wonder if it's a problem with the network on your end.

**Comment by HDZZZ** [comment]
I always use a VPN to access the website. I can only access it when the VPN is close.

**Comment by jackdoyle** [comment]
Ah, so it's an issue with your VPN I guess.
