### ISSUE TITLE
Pixi Plugin filter regression 3.12.0

### ISSUE THREAD

**Issue by alexmaslarski** [greensock/GSAP#541]
There is a regression for pixi-plugin when applying filters. It says `Class costructor  cannot be invoked without new` when applying a brightness filter for example.

![image](https://github.com/greensock/GSAP/assets/38736057/4380ab28-2a4e-4950-ac13-6cbf165f9b03)

**Comment by jackdoyle** [comment]
Hi @alexmaslarski. Good catch - sorry about that, it's fixed in the next release which is due out soon. In the meantime, you can just use a previous version, like 3.11.5

**Comment by jackdoyle** [comment]
Fixed in 3.12.2
