### ISSUE TITLE
how to import GSDevTools

### ISSUE THREAD

**Issue by cieldon32** [greensock/GSAP#542]
where is the GSDevTools

**Comment by jackdoyle** [comment]
GSDevTools is a membership benefit of Club GreenSock. See https://greensock.com/club

It's not in the public Github repo or NPM. But when you sign up, you get access to a private NPM repo as well as a zip download with the bonus plugin files. You can try out all the bonus plugins for free as much as you want on CodePen, Stackblitz, CodeSandbox, and locally by using the gsap-trial NPM package. You just can't deploy that. See https://greensock.com/try-plugins

Happy tweening!
