### ISSUE TITLE
timeline's onComplete not working

### ISSUE THREAD

**Issue by cieldon32** [greensock/GSAP#543]
code: https://stackblitz.com/edit/react-vkscem?file=src%2FApp.js,src%2Fbox%2Findex.jsx,src%2Fbox%2Feffects.js,src%2Fstone%2Findex.jsx,src%2Fstone%2Fstyles.js,src%2Fstone%2Feffects.js,src%2Fbox%2Fstyles.js,src%2Fstyle.css

in the stone's tl, it's effects are getFish and calcFish. getFish's repate is 5. 
when the getFish is completed, tl will paly calcFish. but I don't know how to make it.

**Comment by jackdoyle** [comment]
I read your question and your code a few times and I'm still very confused. Can you please elaborate on exactly what th problem is? 

Here are some tips that will increase your chance of getting a solid answer:

- A clear description of the expected result - "I am expecting the purple div to spin 360degrees"
- A clear description of the issue -  "the purple div only spins 90deg"
- A list of steps for someone else to recreate the issue - "scroll down to the grey container" 
- A minimal demo - if possible, using no frameworks, with minimal styling, only include the code that's absolutely necessary to show the issue. Please don't include your whole project. Just some colored <div> elements is great.

This looked very strange to me: 
```javascript 
const tl = gsap.timeline({
      onComplete: () => {
        console.log('onComplete');
      },
    });
    ctx.add('getFish', (score) => {
      ctx.revert();
      tl.getFish([$stone.current, $score.current], { score });
    });
```
Why are you reverting the whole context INSIDE a function where you're adding to the context? And what is tl.getFish()? That's not a method of a timeline...did you registerEffect() for that or something? Also, why are you creating your timeline OUTSIDE of the context? You should put everything in the context for easy cleanup. 

The best place to get help like this is in the forums at https://greensock.com/forums. Post a minimal demo there along with a clear question and we'd be happy to help.

**Comment by cieldon32** [comment]
// There is a problem with the execution time of this code. It was executed before the animation started, but it was not executed after the animation ended.
console.log('onComplete');

**Comment by cieldon32** [comment]
I just want to be able to start calcFish after getFish in the component stone

**Comment by jackdoyle** [comment]
That looks like expected behavior to me - you're creating a timeline with an onComplete and then you're not adding anything to it on that same tick, so its duration is 0, thus on the very next tick it will fire its onComplete as it should since its playhead reached its end. 

Sorry, I'm very confused about what you're trying to do and why you're writing your code that way. If you need some help, please post in the forums at https://greensock.com/forums along with a minimal demo and we'd be glad to take a look.
