### ISSUE TITLE
When draggable is attached to svg in <object> element, body might not exist and causes error

### ISSUE THREAD

**Issue by jwbargsten** [greensock/GSAP#549]
I have a svg file that I load the following way:

```
<object id="svg" data="dependencies.svg" type="image/svg+xml"></object>
```
My gsap code looks a bit like this:

```
const svgContainer = document.querySelector("#svg");
svgContainer.addEventListener("load", () => {
  init();
})

let svg = null;
function init() {
  if(svg) {
    return;
  }
  svg = svgContainer.contentDocument.firstElementChild;
  gsap.set(svg, { force3D: true, transformOrigin: "left top" });
  draggable = Draggable.create(svg, {type:"x,y", edgeResistance:0.65, inertia:true});
...
```
The first click will cause an exception [here](https://github.com/greensock/GSAP/blob/6032c54a21981b389a5f5603a45083f38ed5acf9/src/utils/matrix.js#L35), because it seems that the `parentNode.body` is `null` in Chrome.

<img width="1421" alt="image" src="https://github.com/greensock/GSAP/assets/919322/34af855e-9685-4886-8f50-91631e9f9a51">

Perhaps it is an idea to check first if `_body` is null before proceeding (that would be the `i` variable in the screenshot).

The effect of this issue is that the user has to click twice to get dragging to start.

**Comment by jackdoyle** [comment]
Thanks for the suggestion. Would you be able to provide a minimal demo that illustrates the problem, like a CodePen or something? That'd be super helpful.

**Comment by jwbargsten** [comment]
CodePen won't work, because I can only access `<object>` elements from the same domain (e.g. [see here](https://greensock.com/forums/topic/12321-non-inline-svg-and-control-with-gsap/?do=findComment&comment=51783). I created a minimal example to explore here: https://bargsten.org/gsap/

**Comment by jackdoyle** [comment]
Thanks for the minimal demo. Does this resolve things for you? 
https://assets.codepen.io/16327/Draggable3.min.js

**Comment by jwbargsten** [comment]
That seems to work! Cool stuff.
