### ISSUE TITLE
rotateY 与 translateZ 顺序问题

### ISSUE THREAD

**Issue by ALiangTech** [greensock/GSAP#550]
_In regular CSS, the order that you list the transforms matters but GSAP always applies them in the same order for consistency: translation (x, y, z), then scale, then rotationX, then rotationY, then skew, then rotation (same as rotationZ)._

但是 我想要先rotateY  然后 translateZ 

请问如何做到这一点。

可以看我原因： [原因](https://codepen.io/hudahei/pen/zYMWJLZ)；
在上面链接的代码js中， 注释掉9-10行的代码， 放开16行代码，然后对比效果。

我想要这种效果

![image](https://github.com/greensock/GSAP/assets/40046221/fb37308f-57db-4a34-97ac-3f8345cf0f12)

仅仅只是 rotateY 与 translateZ 顺序的差别。

**Comment by jackdoyle** [comment]
Can't you just use a transformOrigin for that? 

Perhaps this will help: 
https://codepen.io/GreenSock/pen/RwLepdQ

**Comment by ALiangTech** [comment]
thanks
