### ISSUE TITLE
Nodejs support

### ISSUE THREAD

**Issue by benjaminbours** [greensock/GSAP#553]
Hi everybody,

First thanks for the great lib, I love it and use it for many years now.

But now I am working on a multiplayer web based game. I have an authoritative server responsible to own the game state and some positions in a 3d space.

I managed to use three.js properly with nodejs but when I import GSAP, I got this error
<img width="706" alt="Screenshot 2023-10-07 at 14 16 18" src="https://github.com/greensock/GSAP/assets/8804297/4b26542c-939c-4be2-9e5c-ab9c5bf974ba">

I assume its because in the core there is the css plugin. I didn't manage to find any way to remove some non used module for the core. I just want to animate object properties, to update the physics of the game, I don't need to render anything on the server.

Any ideas about how I could solve it?

Thanks in advance,

Benjamin

**Comment by jackdoyle** [comment]
Howdy, @benjaminbours 

That sounds like a pretty weird scenario - your environment must be returning undefined on document.createElement(). 

If you have no use for CSSPlugin, you can actually just import { gsap } from "gsap/gsap-core"; Does that work for you?

**Comment by benjaminbours** [comment]
Thank you for your answer @jackdoyle 

Indeed its a special scenario, I am not using gsap anymore on physical simulation running on the server. It is updating the clients every 100ms so I think any tween started there will have to be interpolate by the clients anyway, it makes no sens.

But still in the case of a platform that is an ascensor for multiple player in the same time for example, it can exist a big relation between the animation and the game state owned by the server. I need to investigate more about it.

I tried your suggestion, but I am using a tsconfig with `commonjs` module configuration. So when I try to do what you suggest, I have this error.

<img width="784" alt="Screenshot 2023-10-08 at 09 44 36" src="https://github.com/greensock/GSAP/assets/8804297/917ef454-380f-4cf7-9fd0-cbb19ba66c1f">

So I guess the nodejs support can still be improved but my use case was special and maybe a bad example I admit.

**Comment by jackdoyle** [comment]
Yeah, that sounds like your environment doesn't understand ES Modules which is a bit odd since they've been pretty much the standard for many years. Perhaps you just need to tweak something in your environment configuration to cause it to understand ES Modules(?)

**Comment by benjaminbours** [comment]
I am using [NestJS](https://nestjs.com/) and in their generated boilerplate project it is configured with `commonjs`. I can change it but it's creating other issues with this framework.

Regardless of my very use case, I think a transpiled version of this `gsap-core` without any plugin could be a good addition to have a very light version of the lib.

Anyway, the discussion is completely different from my initial issue, thanks for your time and the great job on GSAP!

**Comment by jackdoyle** [comment]
Yeah, we intentionally omitted gsap-core from the /dist directory because those files are generally for folks that aren't very familiar with how bundling works and it's EXTREMELY rare that anyone would want to use gsap-core (omit CSSPlugin). They might accidentally think gsap-core is what they should be loading into their projects intended for browsers/CSS, which would be wrong of course. It'd cause confusion. The only people we figured would want to use gsap-core (no CSSPlugin) would be more advanced developers doing very custom stuff and those would almost surely be using ES Modules in modern bundlers. 

Anyway, thanks for the feedback. Good luck with your project.
