### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by laurens94** [greensock/GSAP#554]
The Club Greensock url (https://greensock.com/club/) seems to be broken on the new website.

It's referenced in [README.md](https://github.com/greensock/GSAP#license)

**Comment by jackdoyle** [comment]
Sorry about that, Neil! With the entirely new site launch, we’re still working on some of the redirects. 

You definitely shouldn’t be using TimelineMax() - that’s a relic from many, many years ago. TweenLite, TweenMax, TimelineLite, and TimelineMax have all been nicely simplified and consolidated into a unified “gsap” object. 

Old:
var tl = new TimelineMax();

New:
var tl = gsap.timeline();

Here are the release notes: https://gsap.com/blog/3-release-notes 

If you need any more help, the forums are fantastic - https://greensock.com/community
