### ISSUE TITLE
Scroll Trigger Plugin Error

### ISSUE THREAD

**Issue by kmaphane** [greensock/GSAP#555]
Good day,

I am using Laravel, Alpine and Livewire with GSAP. 

This is my script 

<div
    x-data="{}"
    x-ref="navWrapper"
    x-init="
        () => {
            if (reducedMotion) return
            gsap.set($refs.navBackground, {
                autoAlpha: 0,
            })
            gsap.set($refs.menuIcon, {
                autoAlpha: 0,
                yPercent: -100,
            })
            gsap.set($refs.topIcon, {
                autoAlpha: 0,
                yPercent: -100,
            })
            gsap.set($refs.navLogo, {
                autoAlpha: 0,
                yPercent: -100,
            })
            gsap.to($refs.navBackground, {
                scrollTrigger: 'top 100vh',
                delay: 15,
                autoAlpha: 1,
            })
        }
    "
    class="relative px-1 py-2 nav-wrapper md:px-2 lg:px-4">

I get the following error:

![image](https://github.com/greensock/GSAP/assets/80934965/ed215eed-62a1-4fb2-95af-8e8a389703a8)

I have tried using both npm installation and cdn scripts but I land at the same error. 

with npm my setup was as follows:

import { gsap } from "gsap"

import { ScrollTrigger } from "gsap/ScrollTrigger"
import { PixiPlugin } from "gsap/PixiPlugin"
import { TextPlugin } from "gsap/TextPlugin"

gsap.registerPlugin(ScrollTrigger, PixiPlugin, TextPlugin)
window.gsap = gsap

I also get this error in the console 

![image](https://github.com/greensock/GSAP/assets/80934965/47f6342d-98b4-4e7c-af5b-a7b4ced69102)
 
These are my dependencies:

 "dependencies": {
        "gsap": "^3.12.2",
        "theme-change": "^2.5.0"
    }

Kindly advice.

**Comment by HassanZahirnia** [comment]
Hey, can try importing GSAP like below?

```js
import * as ScrollTrigger from 'gsap/ScrollTrigger'
```

And try registering 1 plugin at a time.

```js
gsap.registerPlugin(ScrollTrigger)
```
