### ISSUE TITLE
Typo on Docs Page

### ISSUE THREAD

**Issue by AdityaRaj0001** [greensock/GSAP#559]
Steps to Recreate the issue:

1. Visit https://gsap.com/docs/v3/
2. Observe there is this spelling mistake 
3. 
![image](https://github.com/greensock/GSAP/assets/92699283/b62f7ed2-28d7-4307-bbe7-2ac880006484)

**Comment by jackdoyle** [comment]
Hm, I'm struggling to understand what you think the spelling error is. I must be missing something obvious. Can you explain?

**Comment by AdityaRaj0001** [comment]
It can be "which all files are hosted on the public CDN" or just "which files are hosted on the public CDN"

**Comment by jackdoyle** [comment]
Oh, I see what you mean. Sleep deprived brain. Yes, "which files are hosted..." 

Thanks.

**Comment by AdityaRaj0001** [comment]
Thankyou for hearing me out even when you were sleep deprived :)

**Comment by AdityaRaj0001** [comment]
Can you help me locate the file for this. I'll hit a PR asap.

**Comment by AdityaRaj0001** [comment]
I get it Jack. See ya!
