### ISSUE TITLE
Pixi Plugin for new PixiJS v8

### ISSUE THREAD

**Issue by talhaozdemir** [greensock/GSAP#561]
Do you plan to make an update for PixiJS v8?

**Comment by jackdoyle** [comment]
We are certainly open to doing that if there's enough demand. Let us know what friction points there are, and if you can provide any minimal demos (like CodePens) that illustrate challenges or errors with using the current plugin on v8, that'd be very helpful. We just aren't very familiar with all the changes in Pixi that may affect things.

**Comment by talhaozdemir** [comment]
Thanks, I have prepared a tiny V8 demo.

[https://codepen.io/agonya-the-sasster/pen/RwvvpzB] (https://codepen.io/agonya-the-sasster/pen/RwvvpzB)

**Comment by jackdoyle** [comment]
Thanks for the demo! It looks like Pixi has moved some classes around and changed their API a bit, but it's not clear to me where things are at exactly since it's all in beta and not well documented yet. For example, there was a PIXI.Graphics and PIXI.DisplayObject. Do you know where those are now? Same with the filters.

**Comment by talhaozdemir** [comment]
Graphics is still there but DisplayObject is removed in v8. You can get more information from the [link](https://github.com/pixijs/pixijs/releases/tag/v8.0.0-beta.0) and filters also should be still there.

**Comment by jackdoyle** [comment]
Here's a fork that uses an updated PixiPlugin and it seems to work: 
https://codepen.io/GreenSock/pen/bGZewPY?editors=0010

Can you find any other odd behavior? I'm not very familiar with all that changed in Pixi that could affect the plugin.

**Comment by talhaozdemir** [comment]
I tried position, scale, angle, tint, blur, brightness, and it is working without any problems for these properties. Thanks.

**Comment by jackdoyle** [comment]
Excellent, thanks for checking. Let me know if you notice anything else that might need changing for v8 compatibility.

**Comment by stephanedemotte** [comment]
@jackdoyle How can we register the GSAP PixiPlugin in v8 without loading all PIXI components?

javascript
```
import { DisplayObject } from "@pixi/display";
PixiPlugin.registerPIXI({ DisplayObject });
```
This no longer works. The documentation seems outdated:
[GSAP PixiPlugin Documentation](https://gsap.com/docs/v3/Plugins/PixiPlugin/static.registerPIXI/)

@pixi/display is only for v7.

Thanks! 😊

**Comment by jackdoyle** [comment]
Yeah, seems to work fine: 
https://codepen.io/GreenSock/pen/qEWggRQ?editors=0010

Right?
