### ISSUE TITLE
v3.12.3 breaks positioning of scaled elements within inline svg

### ISSUE THREAD

**Issue by dsosborn** [greensock/GSAP#563]
I have an inline svg that contains several elements that are positioned with GSAP. Upgrading to gsap v.3.12.3 displaced many of these elements.

Reverting to 3.12.2 fixed the problem. 

Investigating further, it seems the problematic elements were ones that were scaled with no transformOrigin specified. Adding `transformOrigin: "0% 0%"` to all these elements seems to fix the issue. Without that, it seems like gsap is calculating the origin from the top left corner of the svg, whereas I believe it used to be the top left corner of the element.

To illustrate this, I made 2 codepens with the same code, different gsap versions

v3.12.2: https://codepen.io/DouggieO/pen/zYebqep 
v3.12.3: https://codepen.io/DouggieO/pen/GRzeZYa

**Comment by jackdoyle** [comment]
Sorry about that regression, @dsosborn. Thanks for pointing it out. 

It should be fixed in the upcoming patch which you can preview at https://assets.codepen.io/16327/gsap-latest-beta.min.js

**Comment by jackdoyle** [comment]
Fixed in 3.12.4. ✅

​
