### ISSUE TITLE
SplitText Elements with typescript

### ISSUE THREAD

**Issue by OversensitiveCat** [greensock/GSAP#564]
Hello,

I find quite useful to use the 'elements' property on a SplitText instance, but it's a bit tedious to extend every time the typescript Class to avoid an error. 

Why are you not adding a readonly property like chars, words, lines and selector ? 

Thanks

**Comment by jackdoyle** [comment]
Are you asking why "elements" is not a readonly property in the TypeScript definitions file? It should be, sorry. We'll add that to the next release. Thanks for the suggestion.

**Comment by OversensitiveCat** [comment]
Yes, exactly!
That's great, thank you.
