### ISSUE TITLE
Production in vercel , module not found 

### ISSUE THREAD

**Issue by Huaty** [greensock/GSAP#569]
I encountered an issue where the module 'gsap/ScrambleTextPlugin' couldn't be found. This problem arises when I use the command 'vercel --prod', but everything works fine when I run 'npm run dev'. I attempted the solution outlined in this article [https://www.privjs.com/blog/how-to-install-club-greensock-packages-on-vercel], but it was unsuccessful
<img width="598" alt="Screenshot 2024-01-10 at 1 47 40 AM" src="https://github.com/greensock/GSAP/assets/50129813/2ae16267-cac1-4554-9a81-e8daee46a233">

**Comment by jackdoyle** [comment]
Just checking - did you get it to work? I noticed you closed the issue, so I hope so. Or maybe you just decided to post in the forums and wait for an answer there(?): 
https://gsap.com/community/forums/topic/39525-vercel-prod-is-not-working/

**Comment by Huaty** [comment]
@jackdoyle Yeah, I manage to get it working, so I decided to close it. Thank you so much
