### ISSUE TITLE
Missing parameter for ScrollTrigger.clearScrollMemory in its TypeScript definition

### ISSUE THREAD

**Issue by Djules** [greensock/GSAP#571]
As stated in [the doc](https://gsap.com/docs/v3/Plugins/ScrollTrigger/static.clearScrollMemory()), `ScrollTrigger.clearScrollMemory(scrollRestoration: string)` function allows an optional parameter `scrollRestoration` to explicitly set the `window.history.scrollRestoration` value, but it is missing in the [TypeScript definition](https://github.com/greensock/GSAP/blob/3d86e43c3f47951482f76397023630d2d8960806/types/scroll-trigger.d.ts#L96C29-L96C29).

**Comment by jackdoyle** [comment]
Good catch! Sorry about that - we'll put that in the next release, due out very soon.

**Comment by jackdoyle** [comment]
Resolved in latest release. Thanks!
