### ISSUE TITLE
requestAnimationFrame does not work on WebXR

### ISSUE THREAD

**Issue by cyango** [greensock/GSAP#572]
I'd like to use this lib with my VR project. But I know that gsap depends on requestAnimationFrame. I also read in the docs that if the default raf is not supported then it defaults to setTimeout.

But when I enter on WebXR mode on my Meta Quest browser it does not call the onUpdate or onStart for example

What can be done to solve this?

Best regards.

**Comment by jackdoyle** [comment]
Can you please provide a minimal demo illustrating this problem? Like a CodePen or Stackblitz

GSAP does indeed fall back to using setTimeout() if requestAnimationFrame is not available.
