### ISSUE TITLE
Nextjs Gsap ScrollTrigger snapping not working

### ISSUE THREAD

**Issue by Shazam72** [greensock/GSAP#577]
# Nextjs Gsap ScrollTrigger snapping not working

## Issue Description:

**Problem Summary:**

GSAP ScrollTrigger snapping functionality doesn't work in a Next.js environment, although it works fine in a bare HTML/CSS/JS setup.

**Environment:**

- Next.js version: ^14.1.0
- GSAP version: ^3.12.5
- GSAP react (@gsap/react): ^2.1.0

**Reproducible Steps:**

1. Open the provided Codepen example.
2. Open the provided CodeSandbox Next.js example.
3. Observe that GSAP ScrollTrigger snapping functionality work perfectly fine in CodePen example 
4. Observe that GSAP ScrollTrigger snapping functionality doesn't work in CodeSandbox example
5. Compare with the provided CodePen bare HTML/CSS/JS example where the snapping functionality works correctly.

**Additional Details:**

- No error in console

**Code Samples / Sandbox Links:**

- [CodeSandbox Next.js Example](https://codesandbox.io/p/devbox/laughing-mclean-kpn8y8?workspaceId=57c17864-14fc-4e90-b966-a5ccb5e010e2&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsknato400072v6o0o6unszm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsknato100022v6ofgnzw85q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsknato200042v6oydacync1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsknato300062v6opvizae0h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsknato100022v6ofgnzw85q%2522%253A%257B%2522id%2522%253A%2522clsknato100022v6ofgnzw85q%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsknato300062v6opvizae0h%2522%253A%257B%2522id%2522%253A%2522clsknato300062v6opvizae0h%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clskns6wd00fd2v6oe5v8v4eg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253)
- [CodePen bare HTML/CSS/JS Example](https://codepen.io/Ryan-Goss/pen/OJqopEQ)

**Comment by jackdoyle** [comment]
Your CodeSandbox wouldn't even open for me, but I think I see what's going on - I created this Stackblitz instead: 
https://stackblitz.com/edit/stackblitz-starters-p1ycqi?file=app%2Fpage.tsx,app%2Flayout.tsx

I think the fundamental problem is that you're technically using two different gsap objects - one module-based one that useGSAP() imports, and then a UMD one that Next.js defaults to using since it doesn't use modules by default (if I remember correctly - I'm not a Next.js guy). So the key is to make sure you gsap.registerPlugin(useGSAP, ScrollTrigger) BEFORE you use either one of those so that the useGSAP() is linked to the same gsap object as the rest of your stuff is using. 

And Next.js complains about "style" being added to the <body> (even though the style attribute is empty), thus you may need to clear it out right after registering: 
```javascript
gsap.registerPlugin(useGSAP, ScrollTrigger);
if (typeof document !== 'undefined') { // to avoid Next.js complaining
  document.body.setAttribute('style', ''); 
  document.body.removeAttribute('style');
}
```

It seems to work in that Stackblitz, right? Sorry about any confusion there. It's a very particular edge case where you're importing 2 different gsap objects and not registering them before using them.

**Comment by Shazam72** [comment]
> Your CodeSandbox wouldn't even open for me, but I think I see what's going on - I created this Stackblitz instead: https://stackblitz.com/edit/stackblitz-starters-p1ycqi?file=app%2Fpage.tsx,app%2Flayout.tsx
> 
> I think the fundamental problem is that you're technically using two different gsap objects - one module-based one that useGSAP() imports, and then a UMD one that Next.js defaults to using since it doesn't use modules by default (if I remember correctly - I'm not a Next.js guy). So the key is to make sure you gsap.registerPlugin(useGSAP, ScrollTrigger) BEFORE you use either one of those so that the useGSAP() is linked to the same gsap object as the rest of your stuff is using.
> 
> And Next.js complains about "style" being added to the (even though the style attribute is empty), thus you may need to clear it out right after registering:
> 
> ```js
> gsap.registerPlugin(useGSAP, ScrollTrigger);
> if (typeof document !== 'undefined') { // to avoid Next.js complaining
>   document.body.setAttribute('style', ''); 
>   document.body.removeAttribute('style');
> }
> ```
> 
> It seems to work in that Stackblitz, right? Sorry about any confusion there. It's a very particular edge case where you're importing 2 different gsap objects and not registering them before using them.

Thank you. Your advices worked nice. To think that I missed such an important detail.... Since it worked fine in CodePen I was wondering if NextJS was the problem here but it appeared it was me who hadn't registered the two objets before using them. Many thanks to you GSAP' guy.

**Comment by jackdoyle** [comment]
Excellent! Glad it worked out. Thanks for letting us know.
