### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by harshpatel01** [greensock/GSAP#579]
npm ERR! errno CERT_HAS_EXPIRED
npm ERR! request to https://npm.greensock.com/@gsap%2fshockingly/-/shockingly-3.11.5.tgz failed, reason: certificate has expired

**Comment by jackdoyle** [comment]
So sorry about that! We're working hard to resolve that with the hosting company. Please stand by.

**Comment by jackdoyle** [comment]
In the meantime, there are some temporary solutions explained in this thread: 
https://gsap.com/community/forums/topic/40354-unable-to-build-project-with-shockingly/

Again, please accept our apologies. The hosting company is trying to figure it out and we're pressing them as hard as we can.

**Comment by jackdoyle** [comment]
This should be resolved now. Thanks for your patience and understanding!
