### ISSUE TITLE
Documentation missing for `Draggable.create`

### ISSUE THREAD

**Issue by Paper-Folding** [greensock/GSAP#588]
Doc Link: https://gsap.com/docs/v3/Plugins/Draggable/static.create()/  

After "Any of the following properties can be defined:", but there is no properties listed:  
![image](https://github.com/user-attachments/assets/79b72f2a-56aa-4b8c-b5c4-82405bf994c6)

**Comment by cassieevans** [comment]
Hi there!

Thanks so much for the heads-up on this. Helping all the future visitors to the page! Hero.

All sorted now.💚
