### ISSUE TITLE
Enhance "https://gsap.com/docs/v3/Eases/" 

### ISSUE THREAD

**Issue by Furqan-Nadir** [greensock/GSAP#600]
### Introduction
Let me get straight to the point and save all you guys time. I am a active GSAP user and want to open up a discussion on the responsiveness of **Easing** web page. 

### Problem With Current Page
![Untitled design (2)](https://github.com/user-attachments/assets/24ba6e72-c407-4aee-9eb0-4178fecd9e66)

As you can see that I, like many others prefer to work in a multitasking environment. 

![1](https://github.com/user-attachments/assets/43041561-7562-421f-b8cc-b5756157b53c)

This is how the **Easing** look like on the full screen.

![2](https://github.com/user-attachments/assets/c9f5d2a2-08ed-4529-83e7-4f7a33c24b04)
But when it's minimized or resized, the contents are lost. 

### Solution I propose

From a user perspective, I want to suggest making the graph a little smaller and let the contents appear on the screen for people like me who open multiple tabs at once. I understand that it looks good on smaller phone screens but I wanted to speak my mind.

### Open for Discussion
I encourage all the users to present their views below so that management can get a better understanding of what the community desire.

**Comment by cassieevans** [comment]
Hey! Thanks for the feedback.

A couple of quick fixes - 

If you zoom out you'll be able to see the entire menu. -
<img width="1477" alt="Screenshot 2024-10-24 at 09 38 37" src="https://github.com/user-attachments/assets/defe245d-af4b-467d-8251-fa11d1bbe5bf">

Alternately, just in case you weren't aware, you can click on the code block itself to get all the same functionality - there's currently no lost functionality with that side menu hidden.

<img width="636" alt="Screenshot 2024-10-24 at 09 40 13" src="https://github.com/user-attachments/assets/54d3bf66-acb6-41e3-b4bf-1ede9f0f4782">

I'll look into it though and see if we can keep the menu there until a smaller breakpoint.
